import {actionButton,node,facts,notice,choiceCard,taskRow,appletSurface,emptyState} from './primitives/components.ts';
export function mountUIGallery(host){
 host.classList.add('ui-gallery');
 const header=node('div','ui-gallery-toolbar');if(!host.querySelector('h2'))header.append(node('h1','','UI gallery'));const theme=actionButton({label:'Toggle night',run:()=>{const target=host;target.dataset.theme=target.dataset.theme==='night'?'day':'night';}});const scale=actionButton({label:'Large text',run:()=>{host.classList.toggle('ui-large');host.style.setProperty('--ui-text-body',host.classList.contains('ui-large')?'24px':'16px');host.style.setProperty('--ui-text-label',host.classList.contains('ui-large')?'20px':'14px');}});header.append(theme,scale);host.append(header);
 const section=(title)=>{const s=node('section','ui-pane');s.append(node('h2','',title));host.append(s);return s;};
 const demo=appletSurface({title:'Notes',subtitle:'Village HUD · Interactive example'}),tabs=node('div','ui-applet-tabs'),columns=node('div','ui-note-columns'),list=node('div','ui-applet-list'),editor=node('div','ui-note-editor');
 const notes=[{title:'Weekend plans',items:['Hike at Greenridge Trail','Try the new coffee shop','Organize workspace','Read a few chapters','Plan next week']},{title:'Project ideas',items:['Sketch a new idea','Review the first draft']},{title:'Reading list',items:['Choose the next book']}];let active=0,recent=false;
 function drawNotes(){tabs.replaceChildren();for(const label of ['All','Recent']){const b=node('button','',label);b.type='button';b.setAttribute('aria-selected',String(recent===(label==='Recent')));b.onclick=()=>{recent=label==='Recent';drawNotes();};tabs.append(b);}list.replaceChildren();for(const [i,n]of notes.entries()){if(recent&&i>0)continue;const b=node('button','',n.title);b.type='button';b.setAttribute('aria-current',String(active===i));b.onclick=()=>{active=i;drawNotes();};list.append(b);}editor.replaceChildren(node('h3','',notes[active].title));for(const item of notes[active].items){const label=node('label'),box=node('input');box.type='checkbox';label.append(box,node('span','',item));editor.append(label);}}
 const search=node('input','ui-input');search.placeholder='Search notes…';search.setAttribute('aria-label','Search example notes');search.oninput=()=>{for(const b of list.querySelectorAll('button'))b.hidden=!b.textContent.toLowerCase().includes(search.value.toLowerCase());};
 const side=node('div');side.append(search,list);columns.append(side,editor);demo.body.append(tabs,columns);demo.footer.append(actionButton({label:'Back',variant:'quiet',run:()=>{active=0;drawNotes();}}),actionButton({label:'Save',variant:'primary',run:()=>{demo.meta.textContent='Saved · Example only';}}));drawNotes();host.append(demo.element);
 const palette=section('Worldlet · Built-in palette'),swatches=node('div','ui-palette');
 for(const [label,color,ink] of [['Forest · #315F48','#315f48','#fff'],['Paper · #F4F0E5','#f4f0e5','#203b30'],['Ink · #203B30','#203b30','#fff'],['Honey · #EDC47D','#edc47d','#203b30']]){const swatch=node('div','ui-swatch',label);swatch.style.background=color;swatch.style.color=ink;swatches.append(swatch);}palette.append(swatches,node('p','','Forest for primary actions. Honey for Fox identity and small emphasis—not every button.'));
 const materials=section('World controls · monochrome frost'),scene=node('div','ui-material-demo');
 scene.append(actionButton({label:'Back to world',icon:'map',material:'glass'}),actionButton({label:'Companion',icon:'companion',material:'glass'}),actionButton({label:'View event',material:'glass'}));materials.append(scene,node('p','','The scene shows through; the label remains readable. Content below uses a quieter paper surface.'));
 section('Typography').append(node('p','ui-title','A place for your ideas'),node('p','ui-section-title','Your next trip'),node('p','','Body · 16 px / 400 · The world shows what matters. Fox helps you act.'),node('p','ui-caption','Caption · 12 px · Build metadata only'),facts([['Departure','25 September'],['Nightly price','$180']]));
 const controls=section('Buttons and states'),row=node('div','ui-row');controls.append(row);for(const variant of ['primary','secondary','quiet'])row.append(actionButton({label:variant,icon:'map',variant,run:()=>status.textContent='Selected '+variant}));row.append(actionButton({label:'Unavailable',disabled:true}),actionButton({label:'Loading',run:async()=>{await new Promise(r=>setTimeout(r,900));status.textContent='Finished';}}));const status=node('p','ui-caption','Try a button.');status.setAttribute('role','status');controls.append(status);
 const input=section('Input and feedback'),label=node('label','','Message Fox'),field=node('input','ui-input');label.append(field);input.append(label,notice('Listening · Release to send'),notice('Connection unavailable. Try again.','error'),actionButton({label:'Retry',icon:'chat',run:()=>status.textContent='Retry requested'}));
 const choices=section('Decision comparison'),grid=node('div','ui-choice-grid');choices.append(grid);let selected='';function draw(){grid.replaceChildren(...['Garden House','Station House'].map((title,i)=>choiceCard({title,description:i?'$140 / night':'$180 / night',details:[i?'Steps from trains':'Quiet courtyard','Fictional example'],selected:selected===title,onChoose:()=>{selected=title;draw();}})));}draw();
 const tasks=section('Task tracker');tasks.append(taskRow({title:'Japan trip',objective:'Choose a stay in Kyoto',label:'Japan trip',active:true,run:()=>status.textContent='Trip focused'}),taskRow({title:'Three things today',objective:'Review 1 new item',label:'Calendar update',state:'unseen',icon:'calendar',run:()=>status.textContent='Calendar focused'}));
 section('Empty state').append(emptyState('Nothing here yet','Start a note to get going.'),actionButton({label:'Connect a source',icon:'plus',run:()=>status.textContent='Example connection action'}));
}
