"""The same two World tools for every model; manifest generated by the World."""
import json
from jsonschema import validate

def describe(manifest, actions, target, action):
    if not target:
        return {'version':manifest['version'], 'targets':list(dict.fromkeys(a['target'] for a in actions))}
    matches = [a for a in actions if a['target'] == target]
    if not matches:
        return {'error':'Unknown target. Discover available targets first.'}
    if not action:
        return {'target':target, 'actions':[{'action':a['action'],'description':a['description'].split('. ')[0][:100], 'requiresPrivateContext':not a['public']} for a in matches]}
    found = next((a for a in matches if a['action'] == action), None)
    if not found:
        return {'error':'Unknown action for this target.'}
    return {'target':target,'action':action,'description':found['description'],'parameters':found['parameters'],'requiresPrivateContext':not found['public']}

def invoke(manifest, name, args, *, sample=False, setup=False, allow_actions=True, dispatch):
    definition = next((t for t in manifest['gatewayTools'] if t['name'] == name), None)
    if not definition:
        raise ValueError('Unknown World gateway.')
    validate(args, definition['parameters'])
    actions = manifest['sampleActions'] if sample else manifest['actions']
    if name == 'describe_world_tools':
        return describe(manifest, actions, args['target'], args['action'])
    if not allow_actions:
        raise ValueError('A greeting is text only. Wait for an explicit request.')
    route = next((a for a in actions if a['target']==args['target'] and a['action']==args['action']), None)
    if not route:
        raise ValueError('Unknown target or action. Discover capabilities first.')
    if setup and not route['public']:
        raise ValueError('Private-context permission is required. Open Worldlet privacy controls first.')
    values = json.loads(args['arguments'])
    validate(values, route['parameters'])
    resolved = ({'offset':0} if route['tool']=='read_content_page' else {}) | values | route['defaults']
    return dispatch(route['tool'], resolved)
