import RiveCanvas from '@rive-app/canvas-advanced-single';
import {FOX_STATE_ALIASES} from './fox-state-catalog.ts';
import FOX_RIVE_STATES from '../../../resources/styles/builtin/assets/companion/rive/states.json' with {type:'json'};

/** The painted Fox as a Rive file (resources/styles/builtin/assets/companion/rive,
 * generated by scripts/fox-rive/build.py). One state machine plays the 32 catalog
 * performances; the portrait sets the `state` number of its view model and Rive
 * blends from the pose on screen, interrupted blends included. Drawn into the
 * existing portrait canvas through Rive's Canvas2D renderer, on the portrait's
 * own frame clock. Every channel; the painted Fox stays the fallback. */
export type RiveFoxState=keyof typeof FOX_RIVE_STATES;
export function riveFoxState(state:string):RiveFoxState|undefined{
 const key=Object.hasOwn(FOX_STATE_ALIASES,state)?FOX_STATE_ALIASES[state]:state;
 return Object.hasOwn(FOX_RIVE_STATES,key)?key as RiveFoxState:undefined;
}
// Reduced motion shows the state's settled pose: the blend and opening beat
// play out at once, then the clock holds.
const REDUCED_SETTLE=1.2;
// The 640 px artboard plus headroom above (and matching side margins) so a
// jump or paws thrown overhead stay in view; the artboard does not clip.
const FRAME={minX:-24,minY:-48,maxX:664,maxY:640};
let runtime:ReturnType<typeof RiveCanvas>|undefined;

/** `riv` is the file as a data URL; the page allows no fetches. */
export async function loadRiveFox(riv:string,target:HTMLCanvasElement){
 const rive=await (runtime??=RiveCanvas({locateFile:file=>file}));
 const bytes=Uint8Array.from(atob(riv.slice(riv.indexOf(',')+1)),c=>c.charCodeAt(0));
 const file=await rive.load(bytes,undefined,false);
 const artboard=file.defaultArtboard();
 const machine=new rive.StateMachineInstance(artboard.stateMachineByName('Fox'),artboard);
 const data=file.defaultArtboardViewModel(artboard).defaultInstance();
 machine.bindViewModelInstance(data);artboard.bindViewModelInstance(data);
 const stateValue=data.number('state'),renderer=rive.makeRenderer(target);
 let disposed=false,shown:number|undefined,last:number|undefined,reducedShown:number|undefined;
 const select=(index:number)=>{if(index!==shown){stateValue.value=index;shown=index;}};
 return {
  supports:(state:string)=>riveFoxState(state)!==undefined,
  stats:()=>({renderer:'rive' as const,artboard:artboard.name,state:shown}),
  reset(){last=undefined;reducedShown=undefined;},
  draw(ctx:CanvasRenderingContext2D,state:string,_elapsed:number,now:number,reduced:boolean){
   if(disposed)throw Error('Rive Fox was disposed');
   if(ctx.canvas!==target)throw Error('Rive Fox target cannot change');
   const key=riveFoxState(state);
   if(!key)throw Error('Unauthored Rive Fox state: '+state);
   const index=FOX_RIVE_STATES[key];select(index);
   // Hidden pages stop drawing; a long gap resumes without replaying it.
   let seconds=last===undefined?0:Math.min(.1,Math.max(0,(now-last)/1000));last=now;
   if(reduced){seconds=reducedShown===index?0:REDUCED_SETTLE;reducedShown=index;}else reducedShown=undefined;
   machine.advanceAndApply(seconds);
   renderer.clear();renderer.save();
   renderer.align(rive.Fit.contain,rive.Alignment.center,{minX:0,minY:0,maxX:target.width,maxY:target.height},FRAME);
   artboard.draw(renderer);renderer.restore();
   rive.resolveAnimationFrame();
   return {key:'rive-v1:'+key,sheet:'rive',frame:0};
  },
  dispose(){
   if(disposed)return;disposed=true;
   machine.delete();data.delete();artboard.delete();renderer.delete();file.unref?.();
  }
 };
}
