import RiveCanvas from '@rive-app/canvas-advanced-single';
import {FOX_STATE_ALIASES} from './fox-state-catalog.ts';
import FOX_RIVE_STATES from '../../../resources/styles/builtin/assets/companion/rive/states.json' with {type:'json'};
import {CLASSIC_LOOK,companionLookKey,recolorCompanionPixels,type CompanionLook} from '../../../core/companion/index.ts';

/** The painted Fox as a Rive file (resources/styles/builtin/assets/companion/rive,
 * generated by scripts/fox-rive/build.py). One state machine plays the 32 catalog
 * performances; the portrait sets the `state` number of its view model and Rive
 * blends from the pose on screen, interrupted blends included. Drawn into the
 * existing portrait canvas through Rive's Canvas2D renderer, on the portrait's
 * own frame clock. Every channel; the painted Fox stays the fallback. */
export type RiveFoxState=keyof typeof FOX_RIVE_STATES;
export function riveFoxState(state:string):RiveFoxState|undefined{
 const key=Object.hasOwn(FOX_STATE_ALIASES,state)?FOX_STATE_ALIASES[state]:state;
 return Object.hasOwn(FOX_RIVE_STATES,key)?key as RiveFoxState:undefined;
}
// Reduced motion shows the state's settled pose: the blend and opening beat
// play out at once, then the clock holds.
const REDUCED_SETTLE=1.2;
// The 640 px artboard plus headroom above (and matching side margins) so a
// jump or paws thrown overhead stay in view; the artboard does not clip.
const FRAME={minX:-24,minY:-48,maxX:664,maxY:640};
let runtime:ReturnType<typeof RiveCanvas>|undefined;
// The character's painted layers; props (laptop, book, magnifier) keep their paint.
const CHARACTER_LAYERS=new Set(['armR','armL','lidsClosed','lidsHalf','head','earR','earL','body','tail']);
const FACE_LAYERS=new Set(['lidsClosed','lidsHalf','head']);

/** One painted layer recolored for a look, as PNG bytes Rive can decode. */
async function recolorLayer(bytes:Uint8Array,name:string,look:CompanionLook){
 const bitmap=await createImageBitmap(new Blob([bytes as BlobPart],{type:'image/png'}));
 const canvas=new OffscreenCanvas(bitmap.width,bitmap.height),ctx=canvas.getContext('2d',{willReadFrequently:true})!;
 ctx.drawImage(bitmap,0,0);bitmap.close();
 const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);
 recolorCompanionPixels(pixels.data,look,{face:FACE_LAYERS.has(name)});
 ctx.putImageData(pixels,0,0);
 return new Uint8Array(await (await canvas.convertToBlob({type:'image/png'})).arrayBuffer());
}

/** `riv` is the file as a data URL; the page allows no fetches. */
export async function loadRiveFox(riv:string,target:HTMLCanvasElement,initialLook:CompanionLook=CLASSIC_LOOK){
 const rive=await (runtime??=RiveCanvas({locateFile:file=>file}));
 const bytes=Uint8Array.from(atob(riv.slice(riv.indexOf(',')+1)),c=>c.charCodeAt(0));
 // A look swaps the character's layer textures on the same rig, so every look
 // plays all 32 performances and nothing is recompiled. Rive keeps the painted
 // textures it embeds; the loader only remembers them to recolor from.
 const layers=new Map<string,{asset:any,bytes:Uint8Array}>();
 const loader=new rive.CustomFileAssetLoader({loadContents:(asset:any,embedded:Uint8Array)=>{
  if(asset.isImage&&CHARACTER_LAYERS.has(asset.name)&&embedded?.length)layers.set(asset.name,{asset,bytes:new Uint8Array(embedded)});
  return false;
 }});
 const file=await rive.load(bytes,loader,false);
 const artboard=file.defaultArtboard();
 const machine=new rive.StateMachineInstance(artboard.stateMachineByName('Fox'),artboard);
 const data=file.defaultArtboardViewModel(artboard).defaultInstance();
 machine.bindViewModelInstance(data);artboard.bindViewModelInstance(data);
 const stateValue=data.number('state'),renderer=rive.makeRenderer(target);
 let disposed=false,shown:number|undefined,last:number|undefined,reducedShown:number|undefined;
 const select=(index:number)=>{if(index!==shown){stateValue.value=index;shown=index;}};
 let lookKey=companionLookKey(CLASSIC_LOOK),lookTicket=0;
 /** Wears `look`; resolves once every character layer shows it (or a newer look won). */
 async function setLook(look:CompanionLook){
  const key=companionLookKey(look),ticket=++lookTicket;
  if(key===lookKey)return;
  // Every layer is decoded before any is swapped, so the Fox never draws a
  // layer without its image (a black silhouette) between looks.
  const images=await Promise.all([...layers].map(async([name,layer])=>{
   const png=key===companionLookKey(CLASSIC_LOOK)?layer.bytes:await recolorLayer(layer.bytes,name,look);
   return [layer,await new Promise<any>(resolve=>rive.decodeImage(png,resolve))] as const;
  }));
  if(disposed||ticket!==lookTicket){for(const [,image] of images)image?.unref?.();return;}
  for(const [layer,image] of images){layer.asset.setRenderImage(image);image.unref?.();}
  lookKey=key;
 }
 if(companionLookKey(initialLook)!==lookKey)await setLook(initialLook);
 return {
  supports:(state:string)=>riveFoxState(state)!==undefined,
  stats:()=>({renderer:'rive' as const,artboard:artboard.name,state:shown,look:lookKey,layers:layers.size}),
  setLook,
  reset(){last=undefined;reducedShown=undefined;},
  draw(ctx:CanvasRenderingContext2D,state:string,_elapsed:number,now:number,reduced:boolean){
   if(disposed)throw Error('Rive Fox was disposed');
   if(ctx.canvas!==target)throw Error('Rive Fox target cannot change');
   const key=riveFoxState(state);
   if(!key)throw Error('Unauthored Rive Fox state: '+state);
   const index=FOX_RIVE_STATES[key];select(index);
   // Hidden pages stop drawing; a long gap resumes without replaying it.
   let seconds=last===undefined?0:Math.min(.1,Math.max(0,(now-last)/1000));last=now;
   if(reduced){seconds=reducedShown===index?0:REDUCED_SETTLE;reducedShown=index;}else reducedShown=undefined;
   machine.advanceAndApply(seconds);
   renderer.clear();renderer.save();
   renderer.align(rive.Fit.contain,rive.Alignment.center,{minX:0,minY:0,maxX:target.width,maxY:target.height},FRAME);
   artboard.draw(renderer);renderer.restore();
   rive.resolveAnimationFrame();
   return {key:'rive-v1:'+key,sheet:'rive',frame:0};
  },
  dispose(){
   if(disposed)return;disposed=true;
   machine.delete();data.delete();artboard.delete();renderer.delete();file.unref?.();
  }
 };
}
