import {conversationEntries,worldHistoryQuery,worldHistoryPage,worldEventAppend} from './items/index.ts';
import {activityObserve,activityEvent} from './activity/index.ts';
import {homeWritePlan,curatedSourceRead,todoistWriteReview,todoistWriteResult} from './applets/index.ts';
import {readItemHostRequest} from '../contracts/item-actions.ts';
import {readBrowserOutcomeRequest} from '../contracts/browser-receipt.ts';
import {beginBrowserReceipt,observeBrowserReceipt,resolveBrowserReceipt} from './browser/index.ts';
import {attentionCompletion,attentionPlanCurrent} from "./attention/index.ts";
import {readFoxHostRequest} from './companion/index.ts';
import {readBrowserSurfaceRequest} from '../contracts/browser-surface.ts';
import {browserDriverStart,browserDriverNext} from './browser/index.ts';
import {harnessHandshake,harnessReceive,harnessAuthHandoff,turnTrustObserve,turnTrustInherit,turnWriteAdmission,turnWriteNotice,worldItemSnapshot,worldItemRestore} from './agent/index.ts';
import {sourceEvidenceIssues,sourceEvidenceContext,attentionBatchInput} from './attention/index.ts';
import {analysisSourceContent,mergeAnalysisCandidates,orderAnalysisRecords,analysisBatch} from './applets/index.ts';
import {appletChangedSources,appletInvalidateFacts,appletObservations,appletAnalysisPending,appletAnalysisRetrying,appletAnalysisParked,appletAnalysisFailed,appletAnalysisCommit,appletAnalysisRequest,appletAnalysisItems,appletAnalysisInput,appletAnalysisRefresh,appletCandidateContent,canonicalSourceQuotes} from './applets/index.ts';
import {browserElementPolicy,browserDriverSnapshot} from './browser/index.ts';
import {browserWorkflowReport,prepareOperation,transitionOperation,operationReport,notionOperationOutcome} from './tasks/index.ts';
import {runtimeTaskLease,runtimeRunPrune,runtimeFailure,analysisPlan,nextSourceWake,sourceReadProviders} from './tasks/index.ts';
import {runtimeTaskReport} from './tasks/index.ts';
import {attentionCoverage,withheldContextIds,reconcileDeliveries,acknowledgeDeliveries,validateDeliverySubscriptions,failDeliveries,retryQuarantinedDeliveries} from './tasks/index.ts';
import {setRuntimeTaskEnabled,configureRuntimeSource,claimRuntimeTask,finishRuntimeTask,runtimeClaimCanWrite} from './tasks/index.ts';
import {validateAppletRuntimes,appletReadPlan,finishAppletPage} from './applets/index.ts';
import {agentWorkPriority,nextAgentWork,admitBackgroundWork,userIdle,preemptAgentWork,foregroundAgentWork} from './tasks/index.ts';
import {agentRequestDeadline,agentDeadlineRemaining} from './tasks/index.ts';
import {conversationGuidance,onScreenText,placeContext,recentBrowsing} from './companion/index.ts';
import {modelStatusFresh} from './companion/index.ts';
import {diagnosticReport,diagnosticError,exceptionReport,nativeCrashReport} from './diagnostics/index.ts';
import {interruptsBackground,readSourceChecksNow} from './tasks/index.ts';
import {foxTiming} from './diagnostics/index.ts';
import {attentionFailure} from './attention/index.ts';
import {attentionExecution,attentionFollowupReads,attentionReads} from './attention/index.ts';
import {applyMemoryEdits} from './companion/index.ts';
import {processedAttentionContent,attentionOwnerAllowed} from './attention/index.ts';
import {sourceReadAction} from './applets/index.ts';
import {recordAttentionProgress,discardedAttentionRemovals,matchingAttentionID,suppressedAttention,observeAttention,projectAttention,planAttention,startAttentionBudget,finishAttentionBudget,attentionDependencies,attentionCurrent,validateAttentionRegistrations,weatherObservationText} from './attention/index.ts';
import {browserHistoryDestination,recordBrowserVisit,searchBrowserHistory} from './browser/index.ts';
import {updateOnboarding,worldMenuState} from './onboarding/index.ts';
import {receiveAppletActivity,describeAppletActivity,finishAppletActivity,appletActivitySnapshot} from './applets/index.ts';
import {readPresentationRequest,sourceSnapshotPlan,sourceSnapshotRows,sourceAnalysisRequest,mergeSourceAnalysis,validateSourceAnalysis,validateContextAnalysis,validateContextLayout,contextChunks} from './context/index.ts';
import {validateAgentCapabilities,validateAgentEvent} from '../contracts/agent.ts';
import {journalEntry,executionEvent,taskExecutionEvents,worldActionEvent,worldEvent,recentWorldHistory} from './items/index.ts';
import {defaultSourceChecks,dueSourceCheck,startSourceCheck,reconcileSourceCheck,finishSourceCheck,configureSourceCheck} from './tasks/index.ts';
import {contextLayout} from './context/index.ts';
import {validateConversationHistory} from './companion/index.ts';
import {visibleWorldItems,queryWorldItems,calendarItemTimes} from './items/index.ts';
import {needsTaskContinuityReview,matchingWorldItemOwnerSource,resolveWorldItemID} from './items/index.ts';
import {migrateWorldItems} from './items/index.ts';
import {validateWorldItem} from './items/index.ts';
import {localDeletionRequest,localDeletionSources,localDeletionRecord,localDeletionTrail,worldItemMutation,updateWorldItem,reviewWorldItem,prepareWorldItem,needsAttentionReview} from './items/index.ts';
import {validateCompanionArchive,validCompanionID,validCompanionTimestamp,shouldRotateCompanion} from './companion/index.ts';
import {companionPrompt} from './companion/index.ts';
import {companionPersonaPrompt} from './companion/index.ts';
import {recallCompanion} from './companion/index.ts';
/** Narrow JSON entry for native JS engines. No system capabilities are exposed. */
export function invoke(operation:string,input:string):string {
 try {
  if(operation==='browserElementPolicy')return JSON.stringify({ok:true,value:browserElementPolicy(JSON.parse(input))});
  if(operation==='browserDriverSnapshot')return JSON.stringify({ok:true,value:browserDriverSnapshot(JSON.parse(input))});
  const value=JSON.parse(input);
  if(operation==='conversationEntries')return JSON.stringify({ok:true,value:conversationEntries(value)});
  if(operation==='worldHistoryQuery')return JSON.stringify({ok:true,value:worldHistoryQuery(value)});
  if(operation==='worldEventAppend')return JSON.stringify({ok:true,value:worldEventAppend(value)});
  if(operation==='worldHistoryPage')return JSON.stringify({ok:true,value:worldHistoryPage(value)});
  if(operation==='activityObserve')return JSON.stringify({ok:true,value:activityObserve(value)});
  if(operation==='activityEvent')return JSON.stringify({ok:true,value:activityEvent(value)});
  if(operation==='curatedSourceRead')return JSON.stringify({ok:true,value:curatedSourceRead(value)});
  if(operation==='todoistWriteReview')return JSON.stringify({ok:true,value:todoistWriteReview(value)});
  if(operation==='todoistWriteResult')return JSON.stringify({ok:true,value:todoistWriteResult(value)});
  if(operation==='homeWritePlan')return JSON.stringify({ok:true,value:homeWritePlan(value)});
  if(operation==='browserOutcomeRequest')return JSON.stringify({ok:true,value:readBrowserOutcomeRequest(value)});
  if(operation==='foxHostRequest')return JSON.stringify({ok:true,value:readFoxHostRequest(value)});
  if(operation==='browserSurfaceRequest')return JSON.stringify({ok:true,value:readBrowserSurfaceRequest(value)});
  if(operation==='runtimeReadProviders')return JSON.stringify({ok:true,value:sourceReadProviders(value.providers,value.active)});
  if(operation==='runtimeNextWake')return JSON.stringify({ok:true,value:nextSourceWake(value.checks,value.now)});
  if(operation==='runtimeFailure')return JSON.stringify({ok:true,value:runtimeFailure(value)});
  if(operation==='appletChangedSources')return JSON.stringify({ok:true,value:appletChangedSources(value.previous,value.incoming)});
  if(operation==='appletInvalidateFacts')return JSON.stringify({ok:true,value:appletInvalidateFacts(value.facts,value.provider,value.ids)});
  if(operation==='appletObservations')return JSON.stringify({ok:true,value:appletObservations(value.previous,value.incoming,value.now)});
  if(operation==='appletAnalysisPending')return JSON.stringify({ok:true,value:appletAnalysisPending(value.records,value.saved,value.revisions)});
  if(operation==='appletAnalysisRetrying')return JSON.stringify({ok:true,value:appletAnalysisRetrying(value.records,value.saved,value.revisions)});
  if(operation==='appletAnalysisParked')return JSON.stringify({ok:true,value:appletAnalysisParked(value.records,value.saved,value.revisions)});
  if(operation==='appletAnalysisFailed')return JSON.stringify({ok:true,value:appletAnalysisFailed(value)});
  if(operation==='appletAnalysisCommit')return JSON.stringify({ok:true,value:appletAnalysisCommit(value)});
  if(operation==='appletCandidateContent')return JSON.stringify({ok:true,value:appletCandidateContent(value.item)});
  if(operation==='canonicalSourceQuotes')return JSON.stringify({ok:true,value:canonicalSourceQuotes(value.items,value.evidence)});
  if(operation==='appletAnalysisInput')return JSON.stringify({ok:true,value:appletAnalysisInput(value.provider,value.records,value.items,value.now)});
  if(operation==='appletAnalysisRefresh')return JSON.stringify({ok:true,value:appletAnalysisRefresh(value.records,value.saved,value.revisions)});
  if(operation==='attentionBatchInput')return JSON.stringify({ok:true,value:attentionBatchInput(value)});
  if(operation==='appletAnalysisItems')return JSON.stringify({ok:true,value:appletAnalysisItems(value.records,value.items)});
  if(operation==='appletAnalysisRequest')return JSON.stringify({ok:true,value:appletAnalysisRequest(value.timeoutSeconds,value.instructions)});
  if(operation==='runtimeAnalysisPlan')return JSON.stringify({ok:true,value:analysisPlan(value)});
  if(operation==='runtimeTaskReport')return JSON.stringify({ok:true,value:runtimeTaskReport(value)});
  if(operation==='attentionCoverage')return JSON.stringify({ok:true,value:attentionCoverage(value)});
  if(operation==='withheldContextIds')return JSON.stringify({ok:true,value:withheldContextIds(value)});
  if(operation==='runtimeDeliveriesFail')return JSON.stringify({ok:true,value:failDeliveries(value.rows,value.seeds,value.consumerId,value.code,value.isolated)});
  if(operation==='runtimeDeliveriesRetry')return JSON.stringify({ok:true,value:retryQuarantinedDeliveries(value.rows,value.consumerId)});
  if(operation==='runtimeNotionOutcome')return JSON.stringify({ok:true,value:notionOperationOutcome(value.status)});
  if(operation==='analysisBatch')return JSON.stringify({ok:true,value:analysisBatch(value.records,value.limit,value.retrying)});
  if(operation==='orderAnalysisRecords')return JSON.stringify({ok:true,value:orderAnalysisRecords(value.records,value.attempted)});
  if(operation==='sourceEvidenceContext')return JSON.stringify({ok:true,value:sourceEvidenceContext(value.records,value.provider)});
  if(operation==='sourceEvidenceIssues')return JSON.stringify({ok:true,value:sourceEvidenceIssues(value.items,value.evidence,value.authorizedProviders)});
  if(operation==='analysisSourceContents')return JSON.stringify({ok:true,value:value.rows.map(analysisSourceContent)});
  if(operation==='analysisSourceContent')return JSON.stringify({ok:true,value:analysisSourceContent(value)});
  if(operation==='mergeAnalysisCandidates')return JSON.stringify({ok:true,value:mergeAnalysisCandidates(value.previous,value.incoming)});
  if(operation==='browserWorkflowReport')return JSON.stringify({ok:true,value:browserWorkflowReport(value.receipts,value.items,value.owner)});
  if(operation==='runtimeOperationReport')return JSON.stringify({ok:true,value:operationReport(value.rows,value.owner)});
  if(operation==='runtimeOperationPrepare')return JSON.stringify({ok:true,value:prepareOperation(value)});
  if(operation==='runtimeOperationTransition')return JSON.stringify({ok:true,value:transitionOperation(value.operation,value.event,value.now)});
  if(operation==='runtimeSubscriptions')return JSON.stringify({ok:true,value:validateDeliverySubscriptions(value.rows)});
  if(operation==='runtimeDeliveries')return JSON.stringify({ok:true,value:reconcileDeliveries(value.rows,value.facts,value.seen,value.now,value.subscriptions)});
  if(operation==='runtimeDeliveriesAck')return JSON.stringify({ok:true,value:acknowledgeDeliveries(value.rows,value.seeds,value.now,value.consumerId)});
  if(operation==='runtimeSourceConfigure')return JSON.stringify({ok:true,value:configureRuntimeSource(value.task,value.check)});
  if(operation==='runtimeTaskEnabled')return JSON.stringify({ok:true,value:setRuntimeTaskEnabled(value.task,value.enabled)});
  if(operation==='runtimeTaskLease')return JSON.stringify({ok:true,value:runtimeTaskLease(value)});
  if(operation==='runtimeRunPrune')return JSON.stringify({ok:true,value:runtimeRunPrune(value)});
  if(operation==='runtimeTaskClaim')return JSON.stringify({ok:true,value:claimRuntimeTask(value)});
  if(operation==='runtimeTaskFinish')return JSON.stringify({ok:true,value:finishRuntimeTask(value)});
  if(operation==='runtimeClaimCanWrite')return JSON.stringify({ok:true,value:runtimeClaimCanWrite(value)});
  if(operation==='foregroundAgentWork')return JSON.stringify({ok:true,value:foregroundAgentWork(value)});
  if(operation==='preemptAgentWork')return JSON.stringify({ok:true,value:preemptAgentWork(value)});
  if(operation==='agentWorkPriority')return JSON.stringify({ok:true,value:agentWorkPriority(value)});
  if(operation==='nextAgentWork')return JSON.stringify({ok:true,value:nextAgentWork(value)});
  if(operation==='admitBackgroundWork')return JSON.stringify({ok:true,value:admitBackgroundWork(value)});
  if(operation==='userIdle')return JSON.stringify({ok:true,value:userIdle(value)});
  if(operation==='agentDeadlineRemaining')return JSON.stringify({ok:true,value:agentDeadlineRemaining(value.body,value.started,value.lastInput,value.now)});
  if(operation==='agentRequestDeadline')return JSON.stringify({ok:true,value:agentRequestDeadline(value)});
  if(operation==='conversationGuidance')return JSON.stringify({ok:true,value:conversationGuidance(value)});
  if(operation==='conversationPlace')return JSON.stringify({ok:true,value:placeContext(value)});
  if(operation==='onScreenText')return JSON.stringify({ok:true,value:onScreenText(Array.isArray(value.records)?value.records:[])});
  if(operation==='recentBrowsing')return JSON.stringify({ok:true,value:recentBrowsing(value.visits,value.now,typeof value.open==='string'?value.open:'')});
  if(operation==='modelStatusFresh')return JSON.stringify({ok:true,value:modelStatusFresh(value)});
  if(operation==='attentionOwnerAllowed')return JSON.stringify({ok:true,value:attentionOwnerAllowed(value.provider,value.sources,value.scheduled,value.facts,value.monitorProvider)});
  if(operation==='attentionContent')return JSON.stringify({ok:true,value:processedAttentionContent(value.item)});
  if(operation==='attentionMatchingID')return JSON.stringify({ok:true,value:matchingAttentionID(value.item,value.items)});
  if(operation==='attentionSuppressed')return JSON.stringify({ok:true,value:suppressedAttention(value.item,value.items)});
  if(operation==='attentionRegistrations')return JSON.stringify({ok:true,value:validateAttentionRegistrations(value.rows)});
  if(operation==='attentionWeatherText')return JSON.stringify({ok:true,value:weatherObservationText(value.words,value.temperature,value.previous)});
  if(operation==='attentionObserve')return JSON.stringify({ok:true,value:observeAttention(value.facts,value.registration,value.observations,value.now,value.deliveries)});
  if(operation==='attentionProject')return JSON.stringify({ok:true,value:projectAttention(value.items,value.facts,value.now,value.providers)});
  if(operation==='attentionFailure')return JSON.stringify({ok:true,value:attentionFailure(value.message,value.now)});
  if(operation==='appletRuntimes')return JSON.stringify({ok:true,value:validateAppletRuntimes(value.rows)});
  if(operation==='appletReadPlan')return JSON.stringify({ok:true,value:appletReadPlan(value.spec,value.cursor,value.now)});
  if(operation==='appletPageFinish')return JSON.stringify({ok:true,value:finishAppletPage(value.spec,value.cursor,value.plan,value.page,value.now)});
  if(operation==='attentionExecution')return JSON.stringify({ok:true,value:attentionExecution(value.kind,value.provider)});
  if(operation==='attentionFollowupReads')return JSON.stringify({ok:true,value:attentionFollowupReads(value.provider,value.records)});
  if(operation==='attentionReads')return JSON.stringify({ok:true,value:attentionReads(value.provider)});
  if(operation==='attentionDiscardedRemovals')return JSON.stringify({ok:true,value:discardedAttentionRemovals(value.facts,value.items,value.providers)});
  if(operation==='attentionCompletion')return JSON.stringify({ok:true,value:attentionCompletion(value)});
  if(operation==='attentionPlanCurrent')return JSON.stringify({ok:true,value:attentionPlanCurrent(value.plan,value.facts,value.now,value.providers)});
  if(operation==='attentionPlan')return JSON.stringify({ok:true,value:planAttention(value.facts,value.budget,value.now,value.providers,value.items,value.deliveries,Array.isArray(value.backlog)?value.backlog:[])});
  if(operation==='attentionStart')return JSON.stringify({ok:true,value:startAttentionBudget(value.budget,value.now)});
  if(operation==='attentionProgress')return JSON.stringify({ok:true,value:recordAttentionProgress(value.budget,value.plan,value.processed,value.facts)});
  if(operation==='attentionFinish')return JSON.stringify({ok:true,value:finishAttentionBudget(value.budget,value.plan,value.now,value.success,value.facts,value.cancelled===true,value.yielded===true)});
  if(operation==='attentionDependencies')return JSON.stringify({ok:true,value:attentionDependencies(value.item,value.facts)});
  if(operation==='attentionCurrent')return JSON.stringify({ok:true,value:attentionCurrent(value.dependencies,value.facts,value.now,value.providers)});
  if(operation==='browserHistoryDestination')return JSON.stringify({ok:true,value:browserHistoryDestination(value.url)});
  if(operation==='browserHistoryRecord')return JSON.stringify({ok:true,value:recordBrowserVisit(value.visits,value.item,value.sameDay)});
  if(operation==='browserHistorySearch')return JSON.stringify({ok:true,value:searchBrowserHistory(value.visits,value.query,value.offset,value.after,value.before)});
  if(operation==='worldMenuState')return JSON.stringify({ok:true,value:worldMenuState(value)});
  if(operation==='onboardingUpdate')return JSON.stringify({ok:true,value:updateOnboarding(value.setup,value.body)});
  if(operation==='appletActivityReceive')return JSON.stringify({ok:true,value:receiveAppletActivity(value.activity,value.event,value.turn)});
  if(operation==='appletActivityDescribe')return JSON.stringify({ok:true,value:describeAppletActivity(value.activity,value.body,value.turn)});
  if(operation==='appletActivityFinish')return JSON.stringify({ok:true,value:finishAppletActivity(value.activity,value.turn,value.cancelled)});
  if(operation==='sourceReadAction')return JSON.stringify({ok:true,value:sourceReadAction(value)});
  if(operation==='appletActivitySnapshot')return JSON.stringify({ok:true,value:appletActivitySnapshot(value.provider,value.connected,value.syncStatus,value.items,value.check,value.activity,undefined,value.attentionPending===true)});
  if(operation==='presentationRequest')return JSON.stringify({ok:true,value:readPresentationRequest(value)});
  if(operation==='itemHostRequest')return JSON.stringify({ok:true,value:readItemHostRequest(value)});
  if(operation==='sourceSnapshotPlan')return JSON.stringify({ok:true,value:sourceSnapshotPlan(value.sources,value.knowledge)});
  if(operation==='sourceSnapshotRows')return JSON.stringify({ok:true,value:sourceSnapshotRows(value.sources,value.knowledge,value.regions)});
  if(operation==='sourceAnalysisRequest')return JSON.stringify({ok:true,value:sourceAnalysisRequest(value)});
  if(operation==='sourceAnalysisMerge')return JSON.stringify({ok:true,value:mergeSourceAnalysis(value.source,value.chunks)});
  if(operation==='sourceAnalysisValidate')return JSON.stringify({ok:true,value:validateSourceAnalysis(value.items,value.sources,value.originals,value.themes)});
  if(operation==='contextAnalysisValidate')return JSON.stringify({ok:true,value:validateContextAnalysis(value.items,value.sources,value.originalIDs,value.themes)});
  if(operation==='contextLayoutValidate')return JSON.stringify({ok:true,value:validateContextLayout(value.layout,value.themes)});
  if(operation==='contextChunks')return JSON.stringify({ok:true,value:contextChunks(value.text,value.limit)});
  if(operation==='browserReceiptBegin')return JSON.stringify({ok:true,value:beginBrowserReceipt(value)});
  if(operation==='browserReceiptObserve')return JSON.stringify({ok:true,value:observeBrowserReceipt(value.receipt,value.origin,value.now)});
  if(operation==='browserReceiptResolve')return JSON.stringify({ok:true,value:resolveBrowserReceipt(value)});
  if(operation==='harnessHandshake')return JSON.stringify({ok:true,value:harnessHandshake(value)});
  if(operation==='harnessReceive')return JSON.stringify({ok:true,value:harnessReceive(value)});
  if(operation==='harnessAuthHandoff')return JSON.stringify({ok:true,value:harnessAuthHandoff(value)});
  if(operation==='browserDriverStart')return JSON.stringify({ok:true,value:browserDriverStart(value)});
  if(operation==='browserDriverNext')return JSON.stringify({ok:true,value:browserDriverNext(value)});
  if(operation==='agentCapabilities')return JSON.stringify({ok:true,value:validateAgentCapabilities(value.capabilities)});
  if(operation==='agentEvent')return JSON.stringify({ok:true,value:validateAgentEvent(value.event)});
  if(operation==='recentWorldHistory')return JSON.stringify({ok:true,value:recentWorldHistory(value.rows,value.limit)});
  if(operation==='journalEntry')return JSON.stringify({ok:true,value:journalEntry(value)});
  if(operation==='executionEvent')return JSON.stringify({ok:true,value:executionEvent(value)});
  if(operation==='taskExecutionEvents')return JSON.stringify({ok:true,value:taskExecutionEvents(value)});
  if(operation==='worldActionEvent')return JSON.stringify({ok:true,value:worldActionEvent(value)});
  if(operation==='worldEvent')return JSON.stringify({ok:true,value:worldEvent(value.action,value.body)});
  if(operation==='sourceChecksDefault')return JSON.stringify({ok:true,value:defaultSourceChecks(value.existing,value.providers,value.now,value.registrations||[])});
  if(operation==='sourceCheckDue')return JSON.stringify({ok:true,value:dueSourceCheck(value.checks,value.providers,value.now,value.only,value.firstMail)});
  if(operation==='sourceCheckStart')return JSON.stringify({ok:true,value:startSourceCheck(value.check,value.now)});
  if(operation==='interruptsBackground')return JSON.stringify({ok:true,value:interruptsBackground(value)});
  if(operation==='foxTimings')return JSON.stringify({ok:true,value:(Array.isArray(value.rows)?value.rows:[]).slice(-100).map(foxTiming).filter(Boolean)});
  if(operation==='diagnosticError')return JSON.stringify({ok:true,value:diagnosticError(value)});
  if(operation==='exceptionReport')return JSON.stringify({ok:true,value:exceptionReport(value)});
  if(operation==='nativeCrashReport')return JSON.stringify({ok:true,value:nativeCrashReport(value)});
  if(operation==='diagnosticReport')return JSON.stringify({ok:true,value:diagnosticReport(value)});
  if(operation==='foxTiming')return JSON.stringify({ok:true,value:foxTiming(value)});
  if(operation==='sourceChecksReadNow')return JSON.stringify({ok:true,value:readSourceChecksNow(value.checks,value.now)});
  if(operation==='sourceCheckConfigure')return JSON.stringify({ok:true,value:configureSourceCheck(value.check,value.request,value.providers,value.now)});
  if(operation==='sourceCheckFinish')return JSON.stringify({ok:true,value:finishSourceCheck(value.check,value.latest,value.status,value.now,value.message)});
  if(operation==='sourceCheckReconcile')return JSON.stringify({ok:true,value:reconcileSourceCheck(value.check,value.latest)});
  if(operation==='contextLayout')return JSON.stringify({ok:true,value:contextLayout(value)});
  if(operation==='conversationHistoryValidate'){validateConversationHistory(value.rows,value.writing);return JSON.stringify({ok:true,value:true});}
  if(operation==='worldItemsVisible')return JSON.stringify({ok:true,value:visibleWorldItems(value.items,value.enabledSourceIDs)});
  if(operation==='worldItemsQuery')return JSON.stringify({ok:true,value:queryWorldItems(value.items,value.checks,value.provider)});
  if(operation==='worldItemCalendarTimes')return JSON.stringify({ok:true,value:calendarItemTimes(value.item,value.evidence)});
  if(operation==='worldItemOwnerSourceMatch')return JSON.stringify({ok:true,value:matchingWorldItemOwnerSource(value.a,value.b)});
  if(operation==='taskContinuityReview')return JSON.stringify({ok:true,value:needsTaskContinuityReview(value.item,value.previous,value.identity,value.previousIdentity)});
  if(operation==='worldItemResolveID')return JSON.stringify({ok:true,value:resolveWorldItemID(value.item,value.previous,value.matchingID,value.identity)});
  if(operation==='worldItemMatchingOwnerSource')return JSON.stringify({ok:true,value:matchingWorldItemOwnerSource(value.a,value.b)});
  if(operation==='worldItemsMigrate')return JSON.stringify({ok:true,value:migrateWorldItems(value)});
  if(operation==='worldItemValidate'){validateWorldItem(value.item,value.dates);return JSON.stringify({ok:true,value:true});}
  if(operation==='localDeletionRequest')return JSON.stringify({ok:true,value:localDeletionRequest(value)});
  if(operation==='localDeletionSources')return JSON.stringify({ok:true,value:localDeletionSources(value)});
  if(operation==='localDeletionRecord')return JSON.stringify({ok:true,value:localDeletionRecord(value)});
  if(operation==='localDeletionTrail')return JSON.stringify({ok:true,value:localDeletionTrail(value)});
  if(operation==='worldItemMutation')return JSON.stringify({ok:true,value:worldItemMutation(value.item,value.status,value.now,value.snoozedUntil,value.readOnlyUpdate,value.by)});
  if(operation==='worldItemUpdate')return JSON.stringify({ok:true,value:updateWorldItem(value.item,value.status,value.now,value.snoozedUntil)});
  if(operation==='worldItemReview')return JSON.stringify({ok:true,value:reviewWorldItem(value.item,value.assessment,value.reason,value.sources,value.now)});
  if(operation==='worldItemPrepare')return JSON.stringify({ok:true,value:prepareWorldItem(value.item,value.previous,value.id,value.identity,value.run,value.now,value.previousIdentity)});
  if(operation==='worldItemNeedsReview')return JSON.stringify({ok:true,value:needsAttentionReview(value.item)});
  if(operation==='companionValidate'){validateCompanionArchive(value.archive);return JSON.stringify({ok:true,value:true});}
  if(operation==='companionValidID')return JSON.stringify({ok:true,value:validCompanionID(value.text)});
  if(operation==='companionValidTimestamp')return JSON.stringify({ok:true,value:validCompanionTimestamp(value.text)});
  if(operation==='companionShouldRotate')return JSON.stringify({ok:true,value:shouldRotateCompanion(value.count)});
  if(operation==='companionPrompt')return JSON.stringify({ok:true,value:companionPrompt(value.archive)});
  if(operation==='companionPersonaPrompt')return JSON.stringify({ok:true,value:companionPersonaPrompt(value.name,value.personality)});
  if(operation==='companionMemoryEdits')return JSON.stringify({ok:true,value:applyMemoryEdits(value.archive,value.edits)});
  if(operation==='companionRecall')return JSON.stringify({ok:true,value:recallCompanion(value.archive,value.args)});
  if(operation==='turnTrustObserve')return JSON.stringify({ok:true,value:turnTrustObserve(value.state,value.event)});
  if(operation==='turnTrustInherit')return JSON.stringify({ok:true,value:turnTrustInherit(value.state)});
  if(operation==='turnWriteAdmission')return JSON.stringify({ok:true,value:turnWriteAdmission(value.state,value.event)});
  if(operation==='turnWriteNotice')return JSON.stringify({ok:true,value:turnWriteNotice(value.tool,value.args,value.before)});
  if(operation==='worldItemSnapshot')return JSON.stringify({ok:true,value:worldItemSnapshot(value.item)});
  if(operation==='worldItemRestore')return JSON.stringify({ok:true,value:worldItemRestore(value.item,value.previous,value.now)});
  throw Error('Unknown shared-core operation.');
 } catch(error){return JSON.stringify({ok:false,error:error instanceof Error?error.message:'Shared core failed.'});}
}
