// One source-backed outcome, never a manufactured review task or a savings promise.
export const firstWinDiscovery = `Find important information in this user's Mail for the Attention Center categories: Coming Up (kind=event, a real dated meeting or event), Worth Doing (kind=task, an unfinished action), and Worth Knowing (kind=update, useful information that needs no action). Search the past 30 days, including read and unread mail. FIRST call gmail/read with query="newer_than:30d", limit=1, metadataOnly=false. Evaluate the first readable email for relevance; reading it does not require publishing it. If it contains a genuinely useful finding, save it immediately with exact evidence using items/save before further reads. Otherwise continue discovery without filling the interface. Publish each qualifying verified event, task or update individually as it is found; never collect useful findings until the end of the turn. Then use gmail/read discovery=true for at most 20 metadata candidates across recent mail, meetings, renewals and short obligations, and fetch at most three promising exact provider thread IDs. Keep any additional confirmation searches within newer_than:30d. Query existing world items and preserve settled items. This is a bounded sample of the last 30 days, not an exhaustive scan.
Prefer a genuinely earned benefit that preserves what the user has, then an upcoming unwanted charge (ask whether to keep it), then a short real obligation such as an attendance response. Receipt is not proof of usage, duplication or refund eligibility. An invitation that is free and explicitly needs no RSVP/reservation is information, not a task; do not turn it into a check or booking. Exclude marketing offers requiring spending, heavy claims and lengthy support negotiations from tasks; an informative email may instead be a Worth Knowing update only when it is relevant and worth the user’s attention. Routine promotions, generic newsletters and low-value receipts do not qualify merely because they contain facts. Never create a generic Review/Check task just to fill the interface.
For sources[].quote copy one short continuous passage exactly from the returned full record text. Do not translate, paraphrase, join separate passages or insert ellipses. If save rejects evidence, use its returned readSources text to repair that quote once; do not repeat discovery. If it still fails, report that organization is unfinished rather than claiming a saved finding. Using items/save, save zero or more findings, up to one current event, one genuinely useful task, and three useful updates, each with exact source evidence. There is no minimum count in any category. Readable mail can produce no findings; leave categories empty when nothing important qualifies. Do not invent meetings or tasks to fill categories, and do not duplicate existing or settled items; title and context must state the concrete opportunity and any uncertainty. No claimed savings without current price/policy evidence. Do not browse or change anything yet. If no task qualifies, select a qualifying saved Worth Knowing update if one exists. If no finding qualifies after the bounded scan, call items/save with an empty list to record completion and return an empty candidate block. Distinguish no readable mail from readable mail with nothing important to surface; never claim the entire inbox has no obligations. Return the selected saved task's (preferred), or otherwise update's, exact ID inside <worldlet-candidate>...</worldlet-candidate>, or an empty block if none. Do not return an old task unless its current source was read and qualified in this turn. The public answer must state value/uncertainty and limited coverage in at most two sentences.`;

export function firstWinCandidate(text:unknown){
 const value=String(text||'').match(/<worldlet-candidate>\s*([^<>\s]{1,160})\s*<\/worldlet-candidate>/)?.[1];
 return value||null;
}
