// Interface copy is separate from user content and companion personality.
import {purposeCopy} from './setup-purposes.ts';
const copy:Record<string,string[]>={
 ...purposeCopy,
 'Give your agent a world':['给你的 Agent 一个世界','あなたのエージェントに世界を','Dale un mundo a tu agente'],
 'Give {agent} a world':['给 {agent} 一个世界','{agent} に世界を','Dale un mundo a {agent}'],
 'your agent':['你的 Agent','あなたのエージェント','tu agente'],
 'Found on this computer':['在这台电脑上找到','このコンピュータで見つかりました','Encontrados en este equipo'],
 'Looking for agents on this computer…':['正在查找这台电脑上的 Agent…','このコンピュータのエージェントを探しています…','Buscando agentes en este equipo…'],
 'No agent on this computer yet':['这台电脑上还没有 Agent','このコンピュータにはまだエージェントがありません','Aún no hay agentes en este equipo'],
 'Worldlet sets it up for you':['Worldlet 帮你装好','Worldlet が用意します','Worldlet lo instala por ti'],
 'More options':['更多选项','その他の方法','Más opciones'],
 'Your agents':['你的 Agent','あなたのエージェント','Tus agentes'],
 '{agent} is moving in':['{agent} 正在搬进来','{agent} が引っ越し中','{agent} se está mudando'],
 '{agent} moved in':['{agent} 搬进来了','{agent} が引っ越してきました','{agent} ya se mudó'],
 'Moving {agent} in…':['正在把 {agent} 搬进来…','{agent} を引っ越し中…','Mudando a {agent}…'],
 'Entering your world…':['正在进入你的世界…','世界に入っています…','Entrando en tu mundo…'],
 'What comes along':['一起带来的','一緒に来るもの','Lo que viene con él'],
 'Avatar':['形象','アバター','Avatar'],
 'Fox, by default':['默认是小狐狸','最初はキツネ','Fox, por defecto'],
 'Profile':['档案','プロフィール','Perfil'],
 'Knows: ':['知道：','知っていること：','Sabe: '],
 'Conversations':['对话','会話','Conversaciones'],
 'Skills':['技能','スキル','Habilidades'],
 'skills it learned':['个学会的技能','件の覚えたスキル','habilidades aprendidas'],
 'Routines':['定时任务','ルーティン','Rutinas'],
 'run on their own':['个自动运行','件が自動で動きます','se ejecutan solas'],
 'Connections':['连接','接続','Conexiones'],
 'Apps':['应用','アプリ','Apps'],
 '{count} found on this computer':['这台电脑上找到 {count} 个','このコンピュータで {count} 個','{count} encontradas en este equipo'],
 '{count} to sign in again after setup':['{count} 个设置后需重新登录','{count} 件は設定後に再ログイン','{count} por volver a iniciar sesión'],
 'Sign in again after setup':['设置后重新登录','設定後に再ログイン','Vuelve a iniciar sesión después'],
 '{count} skills':['{count} 个技能','{count} 件のスキル','{count} habilidades'],
 '{count} routines':['{count} 个定时任务','{count} 件のルーティン','{count} rutinas'],
 'Set up by Worldlet':['由 Worldlet 安装','Worldlet が用意','Configurado por Worldlet'],
 'Your agent':['你的 Agent','あなたのエージェント','Tu agente'],
 'On {agent}':['在 {agent} 上','{agent} 上','En {agent}'],
 'On your other computer':['在你的另一台电脑上','別のコンピュータ上','En tu otro equipo'],
 'Your Google account':['你的 Google 账号','あなたの Google アカウント','Tu cuenta de Google'],
 'World tools':['世界工具','ワールドツール','Herramientas del mundo'],
 '{count} apps':['{count} 个应用','{count} 個のアプリ','{count} apps'],
 'Continue in your browser.':['请在浏览器中继续。','ブラウザで続けてください。','Continúa en tu navegador.'],
 'If prompted: ':['如有提示：','表示されたら：','Si se solicita: '],
 'Some browser bookmarks are not accessible on this Mac. You can choose websites below.':['部分浏览器收藏夹无法访问，可在下方选择网站。','一部のブックマークにアクセスできません。下からサイトを選べます。','Algunos marcadores no están disponibles. Elige sitios abajo.'],
 'Find an app':['查找应用','アプリを検索','Buscar una app'],
 'Create':['创作','制作','Crear'],
 'Home':['家','ホーム','Inicio'],
 'Life':['生活','暮らし','Vida'],
 'Explore':['探索','探索','Explorar'],
 'Social':['社交','ソーシャル','Social'],
 'Entertainment':['娱乐','エンタメ','Entretenimiento'],
 'Finance':['财务','財務','Finanzas'],
 'Your request was cancelled.':['请求已取消。','リクエストはキャンセルされました。','Tu solicitud se canceló.'],
 'Your websites':['你的网站','あなたのウェブサイト','Tus sitios web'],
 'Read browser bookmarks':['导入收藏夹','ブックマークを読み込む','Importar marcadores'],
 'Matching websites selected. You can uncheck any.':['已选中匹配的网站，可以取消勾选。','一致するサイトを選択しました。解除できます。','Sitios coincidentes seleccionados. Puedes desmarcarlos.'],
 'No matching websites found. You can choose below.':['没有匹配的网站，可在下方选择。','一致するサイトはありません。下から選べます。','Sin coincidencias. Elige abajo.'],
 'No matching installed apps found.':['未找到匹配的本机应用。','一致するアプリはありません。','No se encontraron apps instaladas compatibles.'],
 'Bookmark file is too large (maximum 5 MB).':['收藏夹文件不能超过 5 MB。','ファイルは最大 5 MB です。','El archivo no puede superar 5 MB.'],
 'Choose an HTML bookmark export from your browser.':['请选择浏览器导出的 HTML 收藏夹文件。','ブラウザから書き出した HTML を選んでください。','Elige un archivo HTML de marcadores exportado.'],
 'Welcome to your personal AI world':['欢迎来到你的专属 AI 世界','あなたの AI の世界へようこそ','Bienvenido a tu mundo de IA'],
 'Bring your apps into your World':['把常用应用带进你的世界','いつものアプリをあなたの世界へ','Trae tus apps a tu mundo'],
 'Choose again':['重新选择','選び直す','Elegir de nuevo'],
 'None':['没有','なし','Ninguno'],
 'Enter your world':['进入你的世界','あなたの世界へ','Entra en tu mundo'],
 'Back to your world':['回到你的世界','あなたの世界へ戻る','Vuelve a tu mundo'],
 'Fox now runs on your own agent. What Fox has learned comes along.':['Fox 现在运行在你自己的 Agent 上，它学到的东西会一起带过去。','Fox はこれからあなた自身のエージェントで動きます。Fox が覚えたことも一緒に移ります。','Fox ahora funciona con tu propio agente. Lo que Fox ha aprendido viene con él.'],
 'Sign-in wasn’t completed. Please try again.':['登录尚未完成，请重试。','ログイン未完了です。もう一度お試しください。','No se completó el inicio. Inténtalo de nuevo.'],
 'Connect Google to enter your world.':['请先连接 Google。','まず Google を接続してください。','Conecta Google para entrar.'],
 'On this Mac':['本机应用','この Mac のアプリ','En este Mac'],
 'Everyday':['日常','ほかのアプリ · 日常','Más apps · Día a día'],
 'Work':['工作','仕事','Trabajo'],
 'Knowledge':['更多应用 · 知识','ほかのアプリ · 知識','Más apps · Conocimiento'],
 'Browse & watch':['更多应用 · 浏览与影音','ほかのアプリ · ウェブと動画','Más apps · Web y vídeos'],
 'Games':['游戏','ゲーム','Juegos'],
 'Money':['更多应用 · 财务','ほかのアプリ · お金','Más apps · Finanzas'],
 'Health':['健康','ほかのアプリ · 健康','Más apps · Salud'],
 'Choose your language':['选择语言','言語を選ぶ','Elige tu idioma'],
 'Choose your apps':['选择应用','アプリを選ぶ','Elige tus apps'],
 'Connect your Google account':['连接 Google 账号','Google アカウントを接続','Conecta tu cuenta de Google'],
 'Your world is ready':['你的世界准备好了','あなたの世界ができました','Tu mundo está listo'],
 'Entering your World…':['正在进入你的世界…','あなたの世界へ…','Entrando en tu mundo…'],
 'Continue':['继续','続ける','Continuar'],
 'Finishing setup…':['正在完成设置…','設定を完了しています…','Terminando la configuración…'],
 'Google authorized. Preparing Fox in the background…':['Google 已授权，正在后台准备 Fox…','Google 認証済み。Fox を準備しています…','Google autorizado. Preparando Fox…'],
 'Checking Mail and Calendar access…':['正在检查邮件与日历访问权限…','メールとカレンダーのアクセスを確認中…','Comprobando acceso al correo y calendario…'],
 'No agent found on this computer. Worldlet installs Hermes Agent for you the official way, then you sign in to ChatGPT inside it.':['这台电脑上没有找到 Agent。Worldlet 会用官方方式帮你装好 Hermes Agent，然后你在 Hermes 里登录 ChatGPT。','このコンピュータにエージェントが見つかりません。Worldlet が公式の方法で Hermes Agent をインストールし、その中で ChatGPT にサインインします。','No hay ningún agente en este ordenador. Worldlet instala Hermes Agent por ti de la forma oficial y luego inicias sesión en ChatGPT dentro de él.'],
 'Installing Hermes Agent…':['正在安装 Hermes Agent…','Hermes Agent をインストールしています…','Instalando Hermes Agent…'],
 'Install Hermes Agent':['安装 Hermes Agent','Hermes Agent をインストール','Instalar Hermes Agent'],
 'Step {step} of {steps}: {title}':['第 {step} 步，共 {steps} 步：{title}','ステップ {step}/{steps}：{title}','Paso {step} de {steps}: {title}'],
 'Hermes Agent is installed. Sign in to ChatGPT in it. To use another model, run hermes model in Terminal, then check again.':['Hermes Agent 已装好。在它里面登录 ChatGPT。想用别的模型，在终端运行 hermes model，再重新检测。','Hermes Agent をインストールしました。その中で ChatGPT にサインインしてください。別のモデルを使うには、ターミナルで hermes model を実行してからもう一度確認します。','Hermes Agent está instalado. Inicia sesión en ChatGPT dentro de él. Para usar otro modelo, ejecuta hermes model en Terminal y vuelve a comprobar.'],
 'Sign in with ChatGPT':['用 ChatGPT 登录','ChatGPT でサインイン','Iniciar sesión con ChatGPT'],
 'Waiting for ChatGPT…':['等待 ChatGPT…','ChatGPT を待っています…','Esperando a ChatGPT…'],
 'Enter this code: ':['输入这个代码：','このコードを入力：','Introduce este código: '],
 'Check again':['重新检测','もう一度確認','Volver a comprobar'],
 'Your agent on another computer':['你在另一台电脑上的 Agent','別のコンピュータのエージェント','Tu agente en otro ordenador'],
 'My Agent is on another computer':['我的 Agent 在另一台电脑上','エージェントは別のコンピュータにあります','Mi agente está en otro ordenador'],
 'Use an agent on this computer':['使用这台电脑上的 Agent','このコンピュータのエージェントを使う','Usar un agente de este ordenador'],
 'On that computer, open Worldlet, then Fox’s panel › Mobile › Pair another computer, and paste its code here.':['在那台电脑上打开 Worldlet，进入 Fox 面板 › 手机 › 配对另一台电脑，然后把代码粘贴到这里。','そのコンピュータで Worldlet を開き、Fox のパネル › モバイル › 別のコンピュータとペアリング を選んで、コードをここに貼り付けてください。','En ese ordenador, abre Worldlet, luego el panel de Fox › Móvil › Emparejar otro ordenador, y pega aquí su código.'],
 'Code from your other computer':['另一台电脑的代码','別のコンピュータのコード','Código de tu otro ordenador'],
 'Connecting to your other computer…':['正在连接另一台电脑…','別のコンピュータに接続中…','Conectando con tu otro ordenador…'],
 'Model ID':['模型 ID','モデル ID','ID del modelo'],
 'Connect':['连接','接続','Conectar'],
 'Continue with Google':['使用 Google 继续','Google で続ける','Continuar con Google'],
 'Continue with {agent}':['使用 {agent} 继续','{agent} で続ける','Continuar con {agent}'],
 'With {agent}, Fox can talk with you but can’t act in your world yet.':['使用 {agent} 时，Fox 可以和你聊天，但暂时还不能在你的世界里操作。','{agent} では Fox は会話できますが、まだ世界の中で操作はできません。','Con {agent}, Fox puede conversar contigo, pero aún no puede actuar en tu mundo.'],
 'Bring {agent}’s name and memory to Fox?':['把 {agent} 的名字和记忆带给 Fox 吗？','{agent} の名前と記憶を Fox に引き継ぎますか？','¿Traer el nombre y la memoria de {agent} a Fox?'],
 'Bring your {agent} memory to Fox?':['把你在 {agent} 里的记忆带给 Fox 吗？','{agent} の記憶を Fox に引き継ぎますか？','¿Traer tu memoria de {agent} a Fox?'],
 'Bring your {agent} memory and model to Fox?':['把你在 {agent} 里的记忆和模型带给 Fox 吗？','{agent} の記憶とモデルを Fox に引き継ぎますか？','¿Traer tu memoria y modelo de {agent} a Fox?'],
 'Fox copies them, and its model if it uses an API key; {agent} itself stays as it is.':['Fox 复制一份，用 API key 的模型也一起带过来；{agent} 本身不会改动。','Fox はコピーし、API キーのモデルも引き継ぎます。{agent} 自体は変わりません。','Fox hace una copia, también del modelo si usa una clave de API; {agent} queda igual.'],
 '{agent} signs in with its own account, which Fox can’t use. After setup, choose a model in Settings, under Model.':['{agent} 用它自己的账号登录，Fox 用不了。设置完成后，在「设置 › 模型」里选一个模型。','{agent} は自分のアカウントでサインインしているため、Fox は使えません。セットアップ後、「設定 › モデル」でモデルを選んでください。','{agent} inicia sesión con su propia cuenta, que Fox no puede usar. Después de la configuración, elige un modelo en Ajustes, en Modelo.'],
 'Choose one in Settings':['在设置里选','設定で選ぶ','Elígelo en Ajustes'],
 'Its own sign-in':['它自己的登录','自身のサインイン','Su propio inicio de sesión'],
 'Fox now runs on the model you brought from {agent}.':['Fox 现在用你从 {agent} 带来的模型。','Fox は {agent} から引き継いだモデルで動きます。','Fox ahora usa el modelo que trajiste de {agent}.'],
 'Fox copies them; {agent} itself stays as it is.':['Fox 只复制一份，{agent} 本身不会改动。','Fox はコピーするだけで、{agent} 自体は変わりません。','Fox hace una copia; {agent} queda igual.'],
 'Bring {agent}’s name, memory and conversations to Fox?':['把 {agent} 的名字、记忆和对话带给 Fox 吗？','{agent} の名前、記憶、会話を Fox に引き継ぎますか？','¿Traer el nombre, la memoria y las conversaciones de {agent} a Fox?'],
 'Bring your {agent} memory and conversations to Fox?':['把你在 {agent} 里的记忆和对话带给 Fox 吗？','{agent} の記憶と会話を Fox に引き継ぎますか？','¿Traer tu memoria y conversaciones de {agent} a Fox?'],
 'conversations':['个对话','件の会話','conversaciones'],
 'notes':['篇笔记','件のメモ','notas'],
 'skills':['个技能','個のスキル','habilidades'],
 'scheduled jobs':['个定时任务','件の定期タスク','tareas programadas'],
 'Fox brought your conversations from {agent}.':['Fox 已经带来了你在 {agent} 里的对话。','Fox は {agent} の会話を引き継ぎました。','Fox trajo tus conversaciones de {agent}.'],
 'Bring them':['带过来','引き継ぐ','Traerlos'],
 'Start fresh':['重新开始','新しく始める','Empezar de cero'],
 'Fox couldn’t bring {agent}’s memory. You can tell Fox about yourself instead.':['Fox 没能带来 {agent} 的记忆，你可以直接告诉 Fox 你的情况。','Fox は {agent} の記憶を引き継げませんでした。Fox に直接教えてください。','Fox no pudo traer la memoria de {agent}. Puedes contarle a Fox sobre ti.'],
 'Connecting to {agent}…':['正在连接 {agent}…','{agent} に接続しています…','Conectando con {agent}…'],
 'Continue with ChatGPT':['使用 ChatGPT 继续','ChatGPT で続ける','Continuar con ChatGPT'],
 'Coming soon':['即将推出','近日公開','Próximamente'],
 'Not installed':['未安装','未インストール','No instalado'],
 'Chat only':['仅聊天','会話のみ','Solo chat'],
 'Ways to continue':['继续方式','続ける方法','Formas de continuar'],
 'Fox can use an Agent already on this computer:':['Fox 可以直接使用这台电脑上的 Agent：','Fox はこのコンピュータの Agent を使えます：','Fox puede usar un Agent de este equipo:'],
 'Enter my World':['进入我的世界','自分の世界へ','Entrar en mi mundo'],
 'Skip for now':['暂时跳过','今はスキップ','Omitir por ahora'],
 'Connecting to Google…':['正在连接 Google…','Google に接続しています…','Conectando con Google…'],
 'Waiting for Google…':['等待 Google 授权…','Google の認証待ち…','Esperando a Google…'],
 'Cancel sign-in':['取消登录','ログインをキャンセル','Cancelar inicio'],
 'Open again':['重新打开','もう一度開く','Abrir de nuevo'],
 'Copy link':['复制链接','リンクをコピー','Copiar enlace'],
 'Link copied':['链接已复制','コピーしました','Enlace copiado'],
 'Finish signing in in your browser. We’ll bring you back here.':['请在浏览器中完成登录。','ブラウザでログインしてください。','Termina de iniciar sesión en el navegador.'],
 'Sign-in wasn’t completed. Try again, or skip for now.':['登录尚未完成，可以重试或跳过。','ログイン未完了です。再試行するかスキップできます。','No se completó el inicio. Reintenta u omite.'],
 'Finding apps on this Mac…':['正在查找本机应用…','この Mac のアプリを確認中…','Buscando apps en este Mac…'],
 'Read-only access. Fox uses your AI model to organize Mail and Calendar.':['只读访问。Fox 使用你的 AI 模型整理邮件和日历。','読み取り専用。Fox が AI モデルでメールと予定を整理します。','Acceso de lectura. Fox usa tu modelo de IA para organizar correo y calendario.'],
 'Previous apps':['上一组应用','前のアプリ','Apps anteriores'], 'More apps':['更多应用','ほかのアプリ','Más apps'],
 'Mail':['邮件','メール','Correo'],'Calendar':['日历','カレンダー','Calendario'],'Notes':['备忘录','メモ','Notas'],'Reminders':['提醒事项','リマインダー','Recordatorios'],'Browser':['浏览器','ブラウザ','Navegador'],'Weather':['天气','天気','Tiempo'],'Meetings':['会议','会議','Reuniones'],
 'With an account':['用账号登录','アカウントで','Con una cuenta'],
 'On this computer':['这台电脑上的','このコンピュータで','En este equipo'],
 'Popular apps':['热门推荐','人気のアプリ','Apps populares'],
 '{agent} isn’t installed on this computer.':['这台电脑上没有安装 {agent}。','このコンピュータに {agent} はインストールされていません。','{agent} no está instalado en este equipo.'],
 'Connecting…':['正在连接…','接続中…','Conectando…'],
 'Give your agent a World':['给你的 Agent 一个世界','あなたのエージェントに世界を','Dale un mundo a tu agente'],
 'Bring the agent you have':['带上你已有的 Agent','いま使っているエージェントを連れてこよう','Trae el agente que ya tienes'],
 'Bring your local agent':['带上本机的 Agent','このコンピュータのエージェント','Trae tu agente local'],
 'Step {step} of 3':['第 {step} 步，共 3 步','ステップ {step}/3','Paso {step} de 3'],
 'Name':['名字','名前','Nombre'],
 'Personality':['性格','性格','Personalidad'],
 'About you':['对你的了解','あなたについて','Sobre ti'],
 'Model':['模型','モデル','Modelo'],
 'Fox’s own':['用 Fox 自己的','Fox のもの','La de Fox'],
 'Bring your cloud agent':['带上云端的 Agent','クラウドのエージェント','Trae tu agente en la nube'],
 'Your ChatGPT plan':['你的 ChatGPT 套餐','ChatGPT プラン','Tu plan de ChatGPT'],
 '{count} conversations':['{count} 段对话','{count} 件の会話','{count} conversaciones'],
 '{count} notes':['{count} 条笔记','{count} 件のメモ','{count} notas'],
 '{count} messages':['{count} 条消息','{count} 件','{count} mensajes'],
 'Its memory comes along':['记忆会一起带来','記憶も一緒に','Su memoria viene contigo'],
 'Not on this computer':['这台电脑上没有','このコンピュータにはありません','No está en este equipo'],
 'routines':['例行任务','ルーティン','rutinas'],
 '{agent}’s conversations':['{agent} 的对话','{agent} の会話','Conversaciones de {agent}'],
 'Reading {agent}’s conversations…':['正在读取 {agent} 的对话…','{agent} の会話を読み込み中…','Leyendo las conversaciones de {agent}…'],
 'reading…':['读取中…','読み込み中…','leyendo…'],
 'Fox now remembers what {agent} knew about you.':['Fox 现在记得 {agent} 对你的了解。','Fox は {agent} が知っていたあなたのことを覚えています。','Fox ahora recuerda lo que {agent} sabía de ti.'],
 '{agent} had no conversations to bring.':['{agent} 没有可以带来的对话。','{agent} に持ってくる会話はありません。','{agent} no tenía conversaciones para traer.'],
 'Connections {agent} had':['{agent} 连过的服务','{agent} の接続','Conexiones de {agent}'],
 'Checking its connections…':['正在检查它的连接…','接続を確認中…','Revisando sus conexiones…'],
 'already connected':['已连接','接続済み','ya conectada'],
 'reconnect':['需重连','再接続','reconectar'],
 'stays with {agent}':['留在 {agent}','{agent} に残ります','se queda en {agent}'],
 'Recommended':['推荐','おすすめ','Recomendado'],
 'In your world':['已在你的世界','あなたの世界に','En tu mundo'],
 'Show all {count} apps':['显示全部 {count} 个应用','{count} 個のアプリをすべて表示','Ver las {count} apps'],
 'Add more apps':['添加更多应用','アプリを追加','Añadir más apps'],
 'Click an app to take it out':['点击应用可移出','クリックで外せます','Haz clic en una app para quitarla'],
 'Click an app below to add it':['点击下方应用即可添加','下のアプリをクリックして追加','Haz clic en una app de abajo para añadirla'],
 'Add {app}':['添加{app}','{app}を追加','Añadir {app}'],
 'Remove {app}':['移出{app}','{app}を外す','Quitar {app}'],
 'Matching websites selected. You can remove any.':['已选中匹配的网站，可以移出。','一致するサイトを選びました。外せます。','Sitios coincidentes seleccionados. Puedes quitarlos.'],
 'Back':['返回','戻る','Volver'],
 'Choose microphone':['选择麦克风','マイクを選ぶ','Elegir micrófono'],
 'Default microphone':['默认麦克风','既定のマイク','Micrófono predeterminado'],
 'Microphone':['麦克风','マイク','Micrófono'],
 'I’ll keep working here in the background. Right-click me (or the Dock icon) to go **Back to World** or **Quit Completely**.':['我会在后台继续工作。右键点我（或程序坞图标），可以选择 **Back to World**（回到世界）或 **Quit Completely**（完全退出）。','バックグラウンドで作業を続けます。私（または Dock のアイコン）を右クリックすると **Back to World**（ワールドに戻る）か **Quit Completely**（完全に終了）を選べます。','Seguiré trabajando aquí en segundo plano. Haz clic derecho sobre mí (o en el icono del Dock) para **Back to World** (volver al mundo) o **Quit Completely** (salir por completo).'],
 'I’ll keep working here in the background. Right-click me (or the tray icon) to go **Back to World** or **Quit Completely**.':['我会在后台继续工作。右键点我（或任务栏通知区域的图标），可以选择 **Back to World**（回到世界）或 **Quit Completely**（完全退出）。','バックグラウンドで作業を続けます。私（または通知領域のアイコン）を右クリックすると **Back to World**（ワールドに戻る）か **Quit Completely**（完全に終了）を選べます。','Seguiré trabajando aquí en segundo plano. Haz clic derecho sobre mí (o en el icono de la bandeja) para **Back to World** (volver al mundo) o **Quit Completely** (salir por completo).'],
 'I’ll keep working here in the background. Right-click me to go **Back to World** or **Quit Completely**.':['我会在后台继续工作。右键点我，可以选择 **Back to World**（回到世界）或 **Quit Completely**（完全退出）。','バックグラウンドで作業を続けます。私を右クリックすると **Back to World**（ワールドに戻る）か **Quit Completely**（完全に終了）を選べます。','Seguiré trabajando aquí en segundo plano. Haz clic derecho sobre mí para **Back to World** (volver al mundo) o **Quit Completely** (salir por completo).'],
 'The chosen microphone is unavailable. Using the default microphone.':['所选麦克风不可用，已改用默认麦克风','選んだマイクが使えないため、既定のマイクを使います。','El micrófono elegido no está disponible. Se usa el predeterminado.'],
 // The three setup pages (owner request 2026-10-06).
 'Reading {agent}’s memory…':['正在读取 {agent} 的记忆…','{agent} の記憶を読み込み中…','Leyendo la memoria de {agent}…'],
 'Packing up {agent}’s conversations…':['正在打包 {agent} 的对话…','{agent} の会話を荷造り中…','Empacando las conversaciones de {agent}…'],
 'Folding in {agent}’s notes…':['正在收拾 {agent} 的笔记…','{agent} のノートをまとめ中…','Doblando las notas de {agent}…'],
 'Teaching Fox {agent}’s skills…':['正在教 Fox 学会 {agent} 的技能…','Fox に {agent} のスキルを教え中…','Enseñando a Fox las habilidades de {agent}…'],
 'Bring your {agent}':['把你的 {agent} 带过来','あなたの {agent} を連れてくる','Trae a tu {agent}'],
 'Bringing everything over':['正在把一切搬过来','すべてを運んでいます','Trayendo todo'],
 'Everything came over':['都搬过来了','すべて運び終えました','Todo llegó'],
 'Click one to leave it out.':['点一下可以不带。','クリックすると外せます。','Haz clic en una para dejarla fuera.'],
 'Apps on your computer':['你电脑上的应用','このコンピュータのアプリ','Apps de tu computadora'],
 'Apps that are popular':['常用的热门应用','人気のアプリ','Apps populares'],
 'Its own':['它自己的','そのまま','La suya'],
 'What it knew':['它知道的','知っていたこと','Lo que sabía'],
 'Nothing yet':['还没有','まだありません','Nada aún'],
 '{agent} moved in.':['{agent} 搬进来了。','{agent} が引っ越してきました。','{agent} se mudó.']
};
export function setupText(text:string,language:string){const i=['zh','ja','es'].indexOf(language);return i<0?text:copy[text]?.[i]||text;}
export function setInterfaceLanguage(language:string){
 if(document.documentElement.lang===language&&localStorage.getItem('worldlet-interface-language')===language)return;
 document.documentElement.lang=language;
 localStorage.setItem('worldlet-interface-language',language);
 window.dispatchEvent(new CustomEvent('worldlet:language',{detail:language}));
}
