// What each app is for (core/applets purpose), in setup's other languages: zh, ja, es as in setup-language.ts.
export const purposeCopy:Record<string,string[]>={
 'Fox reads and sorts your mail and drafts replies':['Fox 帮你阅读、整理邮件并起草回复','Fox がメールを読んで整理し、返信の下書きを作ります','Fox lee y ordena tu correo y redacta respuestas'],
 'Fox keeps an eye on what’s coming up on your calendar':['Fox 帮你留意日历上的近期安排','Fox がカレンダーのこれからの予定に目を配ります','Fox está atento a lo que viene en tu calendario'],
 'Fox reads your notes on this Mac to help with your day':['Fox 读取这台 Mac 上的备忘录，帮你安排一天','Fox がこの Mac のメモを読んで一日を手伝います','Fox lee tus notas de este Mac para ayudarte con tu día'],
 'Fox reads your reminders and brings up the ones due':['Fox 读取提醒事项，告诉你哪些快到期了','Fox がリマインダーを読み、期限のものを知らせます','Fox lee tus recordatorios y te avisa de los pendientes'],
 'Today’s weather and the week ahead where you live':['你所在地的今日天气和一周预报','お住まいの地域の今日の天気と週間予報','El tiempo de hoy y de la semana donde vives'],
 'Join your calls from one place; Fox shows what’s next':['在一处加入所有会议；Fox 告诉你下一场是什么','通話にまとめて参加。次の予定は Fox が表示します','Únete a tus llamadas desde un solo sitio; Fox te muestra la siguiente'],
 'Fox follows your pull requests, reviews and releases':['Fox 跟进你的 Pull Request、代码评审和发布','Fox がプルリクエスト、レビュー、リリースを追います','Fox sigue tus pull requests, revisiones y versiones'],
 'Read your Codex sessions and keep coding with Fox':['查看你的 Codex 会话，和 Fox 继续写代码','Codex のセッションを読み、Fox とコーディングを続けます','Lee tus sesiones de Codex y sigue programando con Fox'],
 'Browse your Claude Code sessions and past conversations':['浏览你的 Claude Code 会话和过往对话','Claude Code のセッションと過去の会話を見られます','Explora tus sesiones de Claude Code y conversaciones anteriores'],
 'Fox reads your Notion pages and finds what matters':['Fox 阅读你的 Notion 页面，找出重点','Fox が Notion のページを読み、大事なことを見つけます','Fox lee tus páginas de Notion y encuentra lo importante'],
 'Fox reads your Obsidian vault; it never changes it':['Fox 读取你的 Obsidian 库，但从不修改','Fox は Obsidian の保管庫を読むだけで、変更しません','Fox lee tu bóveda de Obsidian sin cambiarla nunca'],
 'Read your iMessage conversations and send messages from your world':['在你的世界里看 iMessage 对话、发信息','iMessage の会話を読み、あなたの世界からメッセージを送れます','Lee tus conversaciones de iMessage y envía mensajes desde tu mundo'],
 'Listen to your Voice Memos recordings in your world':['在你的世界里收听语音备忘录录音','ボイスメモの録音をあなたの世界で聴けます','Escucha tus grabaciones de Notas de voz en tu mundo'],
 'Open your Plaid account on its website':['在 Plaid 网站上打开你的账户','Plaid のサイトでアカウントを開きます','Abre tu cuenta de Plaid en su web'],
 'Fox reads your payments, revenue and billing history':['Fox 读取你的付款、收入和账单记录','Fox が支払い、売上、請求履歴を読みます','Fox lee tus pagos, ingresos e historial de facturación'],
 'Fox reads your merchant invoices; the rest stays on PayPal':['Fox 读取你的商家发票，其余内容留在 PayPal','Fox は販売者の請求書を読み、ほかは PayPal に残ります','Fox lee tus facturas de comerciante; lo demás se queda en PayPal'],
 'Fox reads your tasks and helps you get them done':['Fox 读取你的任务，帮你逐一完成','Fox がタスクを読み、片付けるのを手伝います','Fox lee tus tareas y te ayuda a terminarlas'],
 'Fox reads your Linear issues':['Fox 读取你的 Linear issue','Fox が Linear の課題を読みます','Fox lee tus incidencias de Linear'],
 'Fox checks on your Supabase projects':['Fox 帮你查看 Supabase 项目','Fox が Supabase のプロジェクトを確認します','Fox revisa tus proyectos de Supabase'],
 'Fox checks your local containers and images':['Fox 查看本机的容器和镜像','Fox がローカルのコンテナとイメージを確認します','Fox revisa tus contenedores e imágenes locales'],
 'Fox finds your recent files and reads your Docs':['Fox 找到你最近的文件并阅读你的文档','Fox が最近のファイルを見つけ、ドキュメントを読みます','Fox encuentra tus archivos recientes y lee tus Docs'],
 'Fox reads your Google Docs':['Fox 阅读你的 Google 文档','Fox が Google ドキュメントを読みます','Fox lee tus documentos de Google Docs'],
 'Fox reads your Google Sheets':['Fox 阅读你的 Google 表格','Fox が Google スプレッドシートを読みます','Fox lee tus hojas de Google Sheets'],
 'Fox reads your Google Slides':['Fox 阅读你的 Google 幻灯片','Fox が Google スライドを読みます','Fox lee tus presentaciones de Google Slides'],
 'Check your sleep and readiness on Oura’s website':['在 Oura 网站查看睡眠和准备度','Oura のサイトで睡眠とコンディションを確認','Consulta tu sueño y preparación en la web de Oura'],
 'Check your runs and rides on Strava’s website':['在 Strava 网站查看跑步和骑行记录','Strava のサイトでランやライドを確認','Consulta tus carreras y salidas en bici en la web de Strava'],
 'Check your steps, sleep and heart rate on Fitbit’s website':['在 Fitbit 网站查看步数、睡眠和心率','Fitbit のサイトで歩数、睡眠、心拍数を確認','Consulta pasos, sueño y pulso en la web de Fitbit'],
 'Find places and routes; Fox can look them up for you':['查找地点和路线；Fox 可以帮你查','場所やルートを探せます。Fox が調べることもできます','Busca lugares y rutas; Fox puede buscarlos por ti'],
 'Find stays on Airbnb; Fox can search and compare them for you':['在 Airbnb 找住处；Fox 可以帮你搜索和比较','Airbnb で宿探し。Fox が検索して比べます','Busca alojamientos en Airbnb; Fox puede buscarlos y compararlos'],
 'See your trip plans on TripIt’s website':['在 TripIt 网站查看你的行程','TripIt のサイトで旅行の予定を確認','Consulta tus planes de viaje en la web de TripIt'],
 'Read X; Fox keeps the useful posts for you':['浏览 X；Fox 帮你留下有用的帖子','X を読めます。役立つ投稿は Fox が残します','Lee X; Fox guarda los posts útiles por ti'],
 'Watch YouTube; Fox can find videos for you':['看 YouTube；Fox 可以帮你找视频','YouTube を見られます。Fox が動画を探します','Mira YouTube; Fox puede buscarte vídeos'],
 'Watch TikTok in your world':['在你的世界里刷 TikTok','あなたの世界で TikTok を見られます','Mira TikTok en tu mundo'],
 'Chat with your communities on Discord’s website':['在 Discord 网站和社区聊天','Discord のサイトでコミュニティと話せます','Chatea con tus comunidades en la web de Discord'],
 'Visit any website; Fox can look things up for you':['访问任何网站；Fox 可以帮你查资料','どんなサイトも開けます。Fox が調べものをします','Visita cualquier web; Fox puede buscar cosas por ti'],
 'Ask Fox for a page for right now; it works on your phone too':['让 Fox 为眼下做一个页面；手机上也能用','今この時のページを Fox に頼めます。スマホでも使えます','Pide a Fox una página para este momento; también funciona en tu móvil'],
 'Keep the conversations you keep coming back to in one place':['把你一直在继续的对话放在一处','何度も戻ってくる会話を一か所にまとめられます','Reúne en un lugar las conversaciones a las que siempre vuelves'],
 'Order food; Fox finds it and prepares your cart':['点外卖；Fox 帮你找餐并备好购物车','料理を注文。Fox が探してカートを用意します','Pide comida; Fox la encuentra y prepara tu carrito'],
 'Slide the numbered tiles; equal ones merge. Reach 2048.':['滑动数字方块，相同的会合并。凑出 2048。','数字のタイルをスライドし、同じ数を合体。2048 を目指そう。','Desliza las fichas; las iguales se unen. Llega a 2048.'],
 'Steer the snake through the garden and eat the apples without biting your tail.':['操控小蛇在花园里吃苹果，别咬到自己的尾巴。','ヘビを操って庭のリンゴを食べよう。しっぽはかまないで。','Guía la serpiente por el jardín y come manzanas sin morderte la cola.'],
 'Clear the field without digging up a mine. The numbers tell you how many are near.':['清理雷区，别挖到地雷。数字表示周围有几颗雷。','地雷を掘らずにフィールドを片付けよう。数字は周りの地雷の数。','Despeja el campo sin pisar una mina. Los números dicen cuántas hay cerca.'],
 'Fill the grid so every row, column and box holds 1 to 9. A new puzzle every game.':['填满格子，让每行、每列、每宫都有 1 到 9。每局都是新题。','各行・列・ブロックに 1〜9 を入れよう。毎回新しいパズル。','Llena la cuadrícula: 1 a 9 en cada fila, columna y caja. Un puzle nuevo cada vez.'],
 'A different small game from worldlet.ai/games each time it opens.':['每次打开都是 worldlet.ai/games 里的另一款小游戏。','開くたびに worldlet.ai/games の別の小さなゲーム。','Un juego pequeño distinto de worldlet.ai/games cada vez que se abre.'],
 'Guess the five-letter word in six tries. A new puzzle every day.':['六次之内猜出五个字母的单词。每天一道新题。','6 回以内に 5 文字の単語を当てよう。毎日新しいパズル。','Adivina la palabra de cinco letras en seis intentos. Un puzle nuevo cada día.'],
 'Battle trainers with random or your own Pokémon teams; Fox can review your games.':['用随机或自己组的宝可梦队伍和其他训练家对战；Fox 可以帮你复盘打过的对局。','ランダムや自作のポケモンチームでトレーナーと対戦。Fox が対戦を振り返れます。','Combate con equipos Pokémon, aleatorios o tuyos. Fox puede repasar tus partidas.'],
 'Sort sixteen words into four hidden groups. A new puzzle every day.':['把十六个词分进四个隐藏的组。每天一道新题。','16 の単語を 4 つの隠れたグループに分けよう。毎日新しいパズル。','Ordena dieciséis palabras en cuatro grupos ocultos. Un puzle nuevo cada día.'],
 'Grow the longest snake in a live arena full of other players.':['在满是其他玩家的实时竞技场里，把蛇养到最长。','ほかのプレイヤーでいっぱいのアリーナで一番長いヘビを目指そう。','Haz crecer la serpiente más larga en una arena en vivo llena de jugadores.'],
 'Eat smaller cells and grow in a live arena full of other players.':['在满是其他玩家的实时竞技场里吃掉更小的细胞，不断长大。','ほかのプレイヤーでいっぱいのアリーナで小さなセルを食べて大きくなろう。','Come células más pequeñas y crece en una arena en vivo llena de jugadores.'],
 'A fast first-person arena shooter that runs right in the browser.':['直接在浏览器里玩的快节奏第一人称射击游戏。','ブラウザですぐ遊べる、テンポの速い一人称シューター。','Un shooter rápido en primera persona que funciona en el navegador.'],
 'Draw a word while friends guess it, then guess theirs.':['画出一个词让朋友猜，再猜他们画的。','単語を絵に描いて友達に当ててもらい、次は友達の絵を当てよう。','Dibuja una palabra mientras tus amigos adivinan, y luego adivina las suyas.'],
 'Combine elements into new ones, starting from water, fire, wind and earth.':['从水、火、风、土开始，合成新的元素。','水・火・風・土から始めて、元素を組み合わせて新しいものを作ろう。','Combina elementos para crear otros, empezando por agua, fuego, viento y tierra.'],
 'Mix elements to discover hundreds of new ones.':['混合元素，发现数百种新元素。','元素を混ぜて、何百もの新しい元素を見つけよう。','Mezcla elementos para descubrir cientos de nuevos.'],
 'Bake cookies, buy grandmas and factories, bake even more cookies.':['烤饼干，雇奶奶、建工厂，烤更多饼干。','クッキーを焼き、おばあちゃんや工場を買って、もっと焼こう。','Hornea galletas, compra abuelas y fábricas, y hornea aún más.'],
 'Free chess: play people or the computer, solve puzzles. No ads.':['免费国际象棋：和真人或电脑对弈，做谜题。无广告。','無料のチェス：人やコンピュータと対局、パズルも。広告なし。','Ajedrez gratis: juega con personas o la máquina y resuelve problemas. Sin anuncios.'],
 'Drive a little truck over wild physics tracks without flipping.':['开着小卡车驶过疯狂的物理赛道，别翻车。','小さなトラックで物理コースを走ろう。ひっくり返らないで。','Conduce un camioncito por pistas locas sin volcar.'],
 'Run along the tracks, dodge trains and collect coins.':['沿着铁轨奔跑，躲开火车，收集金币。','線路を走り、電車をよけてコインを集めよう。','Corre por las vías, esquiva trenes y recoge monedas.'],
 'Play, make and remix small AI-made games from the Sekai community.':['游玩、制作和改编 Sekai 社区里用 AI 做的小游戏。','Sekai コミュニティの AI 製ミニゲームを遊んで、作って、リミックス。','Juega, crea y remezcla juegos hechos con IA de la comunidad Sekai.'],
 'Tic-tac-toe against an AI that does not play fair. A Sekai favourite.':['和一个不守规矩的 AI 下井字棋。Sekai 人气作品。','ずるい AI と三目並べ。Sekai の人気作。','Tres en raya contra una IA que hace trampas. Un favorito de Sekai.'],
 'Race a hand-drawn car over sketchbook tracks with jump pads. A Sekai favourite.':['驾驶手绘赛车，飞跃素描本上的赛道。Sekai 人气作品。','手描きの車でスケッチブックのコースを走ろう。Sekai の人気作。','Corre con un coche dibujado por pistas de cuaderno con rampas. Un favorito de Sekai.'],
 'Mix paints to match the target shade. A Sekai favourite.':['调配颜料，配出目标颜色。Sekai 人气作品。','絵の具を混ぜて目標の色を作ろう。Sekai の人気作。','Mezcla pinturas hasta igualar el tono. Un favorito de Sekai.'],
 'Draw a roller coaster track and ride it in 3D. A Sekai favourite.':['画出过山车轨道，再用 3D 视角坐一趟。Sekai 人气作品。','ジェットコースターのコースを描いて 3D で乗ろう。Sekai の人気作。','Dibuja una montaña rusa y móntate en 3D. Un favorito de Sekai.'],
 'The card game UNO in 3D against the computer. A Sekai favourite.':['和电脑玩 3D 版 UNO 纸牌。Sekai 人气作品。','コンピュータ相手に 3D の UNO。Sekai の人気作。','El juego de cartas UNO en 3D contra la máquina. Un favorito de Sekai.'],
 'Fifty troll platformer levels where nothing is what it seems. A Sekai favourite.':['五十个处处是陷阱的恶搞闯关关卡。Sekai 人气作品。','見た目どおりにいかない 50 のトロールステージ。Sekai の人気作。','Cincuenta niveles trampa donde nada es lo que parece. Un favorito de Sekai.'],
 'Chat with ChatGPT on its website, next to Fox':['在 ChatGPT 网站上聊天，Fox 就在旁边','Fox のそばで、サイトの ChatGPT と話せます','Chatea con ChatGPT en su web, junto a Fox'],
 'Chat with Claude on its website, next to Fox':['在 Claude 网站上聊天，Fox 就在旁边','Fox のそばで、サイトの Claude と話せます','Chatea con Claude en su web, junto a Fox'],
 'Chat with Gemini on its website, next to Fox':['在 Gemini 网站上聊天，Fox 就在旁边','Fox のそばで、サイトの Gemini と話せます','Chatea con Gemini en su web, junto a Fox'],
 'Ask Perplexity; Fox can run a search there for you':['向 Perplexity 提问；Fox 可以帮你在那里搜索','Perplexity に質問。Fox が代わりに検索します','Pregunta a Perplexity; Fox puede buscar ahí por ti'],
 'Chat with DeepSeek on its website, next to Fox':['在 DeepSeek 网站上聊天，Fox 就在旁边','Fox のそばで、サイトの DeepSeek と話せます','Chatea con DeepSeek en su web, junto a Fox'],
 'Message your friends on WhatsApp Web':['用 WhatsApp 网页版和朋友聊天','WhatsApp Web で友達にメッセージ','Escribe a tus amigos en WhatsApp Web'],
 'Message your chats on Telegram Web':['用 Telegram 网页版收发消息','Telegram Web でチャット','Escribe en tus chats de Telegram Web'],
 'Talk with your team on Slack’s website':['在 Slack 网站和团队交流','Slack のサイトでチームと話せます','Habla con tu equipo en la web de Slack'],
 'Chat and meet on Microsoft Teams’ website':['在 Microsoft Teams 网站聊天和开会','Microsoft Teams のサイトでチャットや会議','Chatea y reúnete en la web de Microsoft Teams'],
 'Join and host calls on Zoom’s website':['在 Zoom 网站参加和主持会议','Zoom のサイトで通話に参加・主催','Únete a llamadas y organízalas en la web de Zoom'],
 'Open your files on Dropbox’s website':['在 Dropbox 网站打开你的文件','Dropbox のサイトでファイルを開けます','Abre tus archivos en la web de Dropbox'],
 'Open your files on OneDrive’s website':['在 OneDrive 网站打开你的文件','OneDrive のサイトでファイルを開けます','Abre tus archivos en la web de OneDrive'],
 'Write documents in Word on the web':['用网页版 Word 写文档','Web 版 Word で文書を作成','Escribe documentos en Word para la web'],
 'Work on spreadsheets in Excel on the web':['用网页版 Excel 处理表格','Web 版 Excel で表計算','Trabaja con hojas de cálculo en Excel para la web'],
 'Make presentations in PowerPoint on the web':['用网页版 PowerPoint 做演示文稿','Web 版 PowerPoint でプレゼンを作成','Crea presentaciones en PowerPoint para la web'],
 'Design in Figma on its website':['在 Figma 网站上做设计','Figma のサイトでデザイン','Diseña en la web de Figma'],
 'Make designs in Canva on its website':['在 Canva 网站上做设计','Canva のサイトでデザインを作成','Crea diseños en la web de Canva'],
 'Play music on Spotify’s web player':['用 Spotify 网页播放器听音乐','Spotify のウェブプレーヤーで音楽を再生','Escucha música en el reproductor web de Spotify'],
 'Play music on Apple Music’s website':['在 Apple Music 网站听音乐','Apple Music のサイトで音楽を再生','Escucha música en la web de Apple Music'],
 'Read Reddit; Fox can find threads on a topic for you':['浏览 Reddit；Fox 可以帮你找某个话题的帖子','Reddit を読めます。話題のスレッドは Fox が探します','Lee Reddit; Fox puede buscarte hilos sobre un tema'],
 'Browse Instagram in your world':['在你的世界里刷 Instagram','あなたの世界で Instagram を見られます','Mira Instagram en tu mundo'],
 'Use LinkedIn; Fox can look up people and jobs for you':['使用 LinkedIn；Fox 可以帮你查找人脉和职位','LinkedIn を使えます。人や求人は Fox が調べます','Usa LinkedIn; Fox puede buscarte personas y empleos'],
 'Shop on Amazon; Fox can search and compare items for you':['在 Amazon 购物；Fox 可以帮你搜索和比价','Amazon で買い物。Fox が商品を検索して比べます','Compra en Amazon; Fox puede buscar y comparar productos por ti'],
 'Watch Netflix in your world':['在你的世界里看 Netflix','あなたの世界で Netflix を見られます','Mira Netflix en tu mundo'],
 'Read and send mail on Outlook’s website':['在 Outlook 网站收发邮件','Outlook のサイトでメールを読み書き','Lee y envía correo en la web de Outlook'],
 'Listen to podcasts on Apple Podcasts’ website':['在 Apple Podcasts 网站听播客','Apple Podcasts のサイトでポッドキャストを聴けます','Escucha pódcasts en la web de Apple Podcasts'],
 'Look through your photos on Google Photos’ website':['在 Google 相册网站浏览你的照片','Google フォトのサイトで写真を見られます','Mira tus fotos en la web de Google Fotos'],
 'Find ideas on Pinterest; Fox can search boards for you':['在 Pinterest 找灵感；Fox 可以帮你搜索图板','Pinterest でアイデア探し。ボードは Fox が検索します','Busca ideas en Pinterest; Fox puede buscar tableros por ti'],
 'Browse Facebook in your world':['在你的世界里刷 Facebook','あなたの世界で Facebook を見られます','Mira Facebook en tu mundo'],
 'Read Threads in your world':['在你的世界里看 Threads','あなたの世界で Threads を読めます','Lee Threads en tu mundo'],
 'Edit videos in CapCut on the web':['用网页版 CapCut 剪辑视频','Web 版 CapCut で動画を編集','Edita vídeos en CapCut para la web'],
 'Book rides on Uber’s website; Fox can check prices for you':['在 Uber 网站叫车；Fox 可以帮你查价格','Uber のサイトで配車。料金は Fox が確認します','Pide viajes en la web de Uber; Fox puede consultar precios por ti'],
 'Order food on Uber Eats; Fox can find a place for you':['在 Uber Eats 点外卖；Fox 可以帮你找餐厅','Uber Eats で料理を注文。お店は Fox が探します','Pide comida en Uber Eats; Fox puede buscarte un sitio'],
 'Find hotels on Booking.com; Fox can search and compare them for you':['在 Booking.com 找酒店；Fox 可以帮你搜索和比较','Booking.com でホテル探し。Fox が検索して比べます','Busca hoteles en Booking.com; Fox puede buscarlos y compararlos'],
 'Work with your team on Feishu’s website':['在飞书网页版和团队协作','Feishu のサイトでチームと仕事','Trabaja con tu equipo en la web de Feishu'],
 'Watch videos on bilibili; Fox can find them for you':['在哔哩哔哩看视频；Fox 可以帮你找','bilibili で動画を見られます。Fox が探します','Mira vídeos en bilibili; Fox puede buscarlos por ti'],
 'Find tips on Xiaohongshu; Fox can search notes for you':['在小红书找攻略；Fox 可以帮你搜笔记','Xiaohongshu でヒント探し。ノートは Fox が検索します','Busca consejos en Xiaohongshu; Fox puede buscar notas por ti'],
 'Open your files on Baidu Netdisk’s website':['在百度网盘网页版打开你的文件','Baidu Netdisk のサイトでファイルを開けます','Abre tus archivos en la web de Baidu Netdisk'],
 'Track issues in Linear on its website':['在 Linear 网站跟踪问题','Linear のサイトで課題を管理','Sigue incidencias en la web de Linear'],
 'Watch live streams on Twitch':['在 Twitch 看直播','Twitch でライブ配信を見られます','Mira directos en Twitch'],
 'Chat with Microsoft Copilot on its website, next to Fox':['在 Microsoft Copilot 网站上聊天，Fox 就在旁边','Fox のそばで、サイトの Microsoft Copilot と話せます','Chatea con Microsoft Copilot en su web, junto a Fox'],
 'Read and edit PDFs in Adobe Acrobat on the web':['用网页版 Adobe Acrobat 阅读和编辑 PDF','Web 版 Adobe Acrobat で PDF を閲覧・編集','Lee y edita PDF en Adobe Acrobat para la web'],
 'Read Wikipedia; Fox can look things up there for you':['阅读维基百科；Fox 可以帮你在上面查资料','Wikipedia を読めます。Fox が調べものをします','Lee Wikipedia; Fox puede buscar cosas ahí por ti'],
 'Chat with Doubao on its website, next to Fox':['在豆包网站上聊天，Fox 就在旁边','Fox のそばで、サイトの Doubao と話せます','Chatea con Doubao en su web, junto a Fox'],
 'Shop on Taobao; Fox can search and compare items for you':['在淘宝购物；Fox 可以帮你搜索和比价','Taobao で買い物。Fox が商品を検索して比べます','Compra en Taobao; Fox puede buscar y comparar productos por ti'],
 'Pay and check your bills on Alipay’s website':['在支付宝网站付款和查看账单','Alipay のサイトで支払いや請求を確認','Paga y revisa tus facturas en la web de Alipay'],
 'Watch short videos on Douyin; Fox can find them for you':['在抖音刷短视频；Fox 可以帮你找','Douyin でショート動画を見られます。Fox が探します','Mira vídeos cortos en Douyin; Fox puede buscarlos por ti'],
 'Check your product analytics on PostHog’s website':['在 PostHog 网站查看产品分析','PostHog のサイトでプロダクト分析を確認','Consulta tu analítica de producto en la web de PostHog'],
 'Manage your sites on Cloudflare’s dashboard':['在 Cloudflare 控制台管理你的网站','Cloudflare のダッシュボードでサイトを管理','Gestiona tus sitios en el panel de Cloudflare'],
 'Check your deployments on Vercel’s website':['在 Vercel 网站查看部署','Vercel のサイトでデプロイを確認','Consulta tus despliegues en la web de Vercel'],
 'Check your sites and deploys on Netlify’s website':['在 Netlify 网站查看站点和部署','Netlify のサイトでサイトとデプロイを確認','Consulta tus sitios y despliegues en la web de Netlify'],
 'Open your Firebase projects in its console':['在 Firebase 控制台打开你的项目','Firebase のコンソールでプロジェクトを開けます','Abre tus proyectos de Firebase en su consola'],
 'Check your app’s errors on Sentry’s website':['在 Sentry 网站查看应用错误','Sentry のサイトでアプリのエラーを確認','Consulta los errores de tu app en la web de Sentry'],
 'Check your services on Railway’s website':['在 Railway 网站查看你的服务','Railway のサイトでサービスを確認','Consulta tus servicios en la web de Railway'],
 'Check your services on Render’s website':['在 Render 网站查看你的服务','Render のサイトでサービスを確認','Consulta tus servicios en la web de Render'],
 'Follow your code and merge requests on GitLab’s website':['在 GitLab 网站跟进代码和合并请求','GitLab のサイトでコードとマージリクエストを追えます','Sigue tu código y merge requests en la web de GitLab'],
 'Track issues in Jira on its website':['在 Jira 网站跟踪问题','Jira のサイトで課題を管理','Sigue incidencias en la web de Jira'],
};
