import logo from './logo-source.ts';
import {node,textButton as button} from '../../components/index.ts';
export function videoID(input){
 const value=String(input||'').trim();if(/^[\w-]{11}$/.test(value))return value;
 try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port)return null;const p=u.pathname.split('/').filter(Boolean);let id;if(u.hostname==='youtu.be'&&p.length===1)id=p[0];if(['youtube.com','www.youtube.com','m.youtube.com','music.youtube.com'].includes(u.hostname)){if(u.pathname==='/watch'&&u.searchParams.getAll('v').length===1)id=u.searchParams.get('v');if(p.length===2&&['shorts','embed','live'].includes(p[0]))id=p[1];}return /^[\w-]{11}$/.test(id||'')?id:null;}catch{return null;}
}
const el:(tag:string,cls?:string,text?:unknown)=>any=node;
const clock=n=>{n=Math.max(0,Math.floor(n||0));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')};
// The Applet holds no YouTube account; harness/hermes/GOOGLE-OAUTH-REVIEW.md says why. Public links
// play in the official player and the queue stays on this Mac.
export function createYouTubeApplet({native,content,onMedia=(_media: any)=>{},notify=(_text: string)=>{}}){
 const root=el('section','youtube-applet'),top=el('div','yt-top'),brand=el('div','yt-brand'),img=el('img');img.src=logo;img.alt='';brand.append(img,el('strong','','YouTube'));
 const form=el('form','yt-search'),input=el('input'),submit=el('button','','Watch');input.type='search';input.placeholder='Paste a YouTube video link';input.setAttribute('aria-label','Paste a YouTube video link');submit.type='submit';form.append(input,submit);top.append(brand);root.append(top,form);
 const status=el('p','yt-message');status.setAttribute('role','status');status.setAttribute('aria-live','polite');root.append(status);
 const watch=el('div','yt-watch'),slot=el('div','yt-player-slot'),now=el('div','yt-now'),title=el('h2'),byline=el('p'),controls=el('div','yt-controls');watch.hidden=true;slot.setAttribute('aria-label','YouTube video player');slot.append(el('p','','Loading the official YouTube player…'));now.append(title,byline,controls);watch.append(slot,now);root.append(watch);
 const listHeader=el('div','yt-list-heading'),heading=el('h2','','Your viewing corner'),count=el('span');listHeader.append(heading,count);root.append(listHeader);
 const results=el('div','yt-results');root.append(results);
 let state: any={sample:false,queue:[]},media: any={state:-1},selected=null,queue=[],generation=0,visible=false,playerShown=false,lastRect='',saveAt=0,pendingPlay=false,layoutEpoch=0,ready;
 const api=body=>{if(!native?.youtube)throw Error('Open the YouTube Applet in the Worldlet Mac app.');return native.youtube(body)};
 const player=body=>{if(!native?.youtubePlayer)throw Error('The official player is available in the Worldlet Mac app.');return native.youtubePlayer(body)};
 function message(text,error=false){status.textContent=text;status.dataset.error=String(error)}
 async function run(fn){try{return await fn()}catch(e){message(e.message||String(e),true);return null}}
 function drawEmpty(){results.replaceChildren();const empty=el('div','yt-empty'),mark=el('img');mark.src=logo;mark.alt='YouTube';empty.append(mark,el('h3','','A queue for this little world'),el('p','','Paste a YouTube link above to start watching. Videos you add are saved on this Mac, separate from YouTube Watch later.'));results.append(empty);count.textContent='';}
 function draw(){results.replaceChildren();count.textContent=queue.length?queue.length+' '+(queue.length===1?'item':'items'):'';if(!queue.length){drawEmpty();return;}
  for(const item of queue){const card=el('article','yt-card'),open=button('',()=>run(()=>openVideo(item)),'yt-card-open'),thumbnail=el('img');thumbnail.src=item.thumbnail||'';thumbnail.alt='';thumbnail.loading='lazy';thumbnail.referrerPolicy='no-referrer';thumbnail.onerror=()=>{thumbnail.removeAttribute('src');thumbnail.classList.add('unavailable')};const image=el('div','yt-thumbnail');if(item.thumbnail)image.append(thumbnail);image.append(el('span','yt-kind','▶'));open.append(image,el('strong','',item.title),el('small','',item.channel||''));card.append(open);
   card.append(button('Remove',()=>run(()=>remove(item.id)),'yt-queue-action'));results.append(card);
  }
 }
 async function load({agent}: {agent?: boolean}={}){const requestID=++generation;heading.textContent='Your local queue';
  const result=await api({operation:'queue',agent});if(requestID!==generation)return;
  queue=result.queue||[];draw();message('Saved on this Mac · Separate from YouTube Watch later');return result;
 }
 function rect(){const r=slot.getBoundingClientRect(),p=content.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,visible:!document.hidden&&r.top>=p.top+3&&r.bottom<=p.bottom-3}}
 async function layout(){if(!visible||!selected)return;const epoch=layoutEpoch;const r=rect(),key=JSON.stringify(r);if(key===lastRect&&playerShown)return;lastRect=key;if(!playerShown){await player({operation:'show',id:selected.id,seconds:media.seconds||0,rect:r});if(epoch===layoutEpoch&&visible)playerShown=true;}else await player({operation:'layout',rect:r});}
 async function remember(){if(!selected)return;await api({operation:'remember',...selected,seconds:media.seconds||0})}
 async function openVideo(item,seconds=0,agent=false){const id=videoID(item.id);if(!id)throw Error('Paste a valid YouTube video link.');if(agent)await api({operation:'status',agent:true});layoutEpoch++;pendingPlay=false;await player({operation:'hide'});playerShown=false;lastRect='';selected={id,title:item.title||'YouTube video',channel:item.channel||''};media={id,state:-1,seconds,duration:0};watch.hidden=false;title.textContent=selected.title;byline.textContent=selected.channel;drawControls();content.scrollTop=0;onMedia(media);await remember();await layout();message('Press Play in the official YouTube player.');return {ok:true,id,title:selected.title,playback:'cued; press Play or request playback'};}
 function drawControls(){controls.replaceChildren(button(media.state===1?'Pause':'Play',()=>run(()=>control(media.state===1?'pause':'play'))),button('Next',()=>run(()=>next())),button('＋ Queue',()=>run(()=>add(selected))),button('Open on YouTube ↗',()=>run(()=>api({operation:'external',id:selected.id})),'yt-link'));const b=controls.children[1];b.disabled=!queue.length;if(media.error!==undefined)controls.append(button('Retry',()=>run(()=>openVideo(selected,media.seconds||0))));controls.append(el('span','yt-time',clock(media.seconds)+' / '+clock(media.duration)));}
 async function add(item,agent=false){const result=await api({operation:'add_to_queue',id:item.id,title:item.title,channel:item.channel,agent});queue=result.queue;draw();if(selected)drawControls();message('Added to your local queue.');return result}
 async function remove(id,agent=false){const result=await api({operation:'remove_from_queue',id,agent});queue=result.queue;draw();if(selected)drawControls();return result}
 async function next(agent=false){const autoplay=media.state===1||media.state===0;if(!queue.length)throw Error('Your queue is empty. Add a video first.');const index=queue.findIndex(v=>v.id===selected?.id),item=queue[index+1];if(!item)throw Error('You reached the end of your queue.');const result=await openVideo(item,0,agent);pendingPlay=autoplay;return result}
 async function control(operation: string,seconds?: number,agent=false){const result=await player({operation,seconds,agent});return result}
 form.onsubmit=e=>{e.preventDefault();run(async()=>{const query=input.value.trim();if(!query)return;const id=videoID(query);if(!id)throw Error('Paste a YouTube video link. This Applet plays links you bring; it does not read your YouTube account.');return openVideo({id,title:'YouTube video'})})};
 window.addEventListener('worldlet:youtube-player',(e: any)=>{const value=e.detail;if(value.closed){media={...media,state:-1};onMedia(media);return}if(!selected||value.id!==selected.id)return;const oldState=media.state;media={...media,...value};if(value.title){selected.title=value.title;title.textContent=value.title;}byline.textContent=selected.channel||'YouTube';if(oldState!==media.state||value.error!==undefined)drawControls();else if(controls.querySelector('.yt-time'))controls.querySelector('.yt-time').textContent=clock(media.seconds)+' / '+clock(media.duration);onMedia(media);if(value.ready&&pendingPlay&&visible){pendingPlay=false;run(()=>control('play'));}
  if(value.error!==undefined)message(({2:'This video link is invalid.',5:'YouTube could not play this video.',100:'This video is unavailable or private.',101:'The owner does not allow embedded playback.',150:'The owner does not allow embedded playback.',153:'YouTube could not verify this player.'}[value.error]||'The YouTube player could not load. Check your connection and retry.')+' Use Open on YouTube to watch in your browser.',true);
  else if(value.ready||value.state===1)message('');
  if(Date.now()-saveAt>5000){saveAt=Date.now();run(remember)}
  if(value.state===0&&oldState!==0&&queue.findIndex(v=>v.id===selected.id)<queue.length-1)run(()=>next());
 });
 function sync(){const nextVisible=root.isConnected&&!content.hidden&&content.contains(root);if(nextVisible===visible)return;visible=nextVisible;if(!visible){layoutEpoch++;pendingPlay=false;generation++;run(remember);playerShown=false;lastRect='';run(()=>player({operation:'hide'}));}else{run(layout);}}
 new MutationObserver(()=>{sync();if(visible)run(layout)}).observe(content,{attributes:true,childList:true,subtree:true,attributeFilter:['hidden','data-template']});new ResizeObserver(()=>{if(visible)run(layout)}).observe(slot);window.addEventListener('resize',()=>run(layout));content.addEventListener('scroll',()=>run(layout),{passive:true});document.addEventListener('visibilitychange',()=>run(layout));
 ready=run(async()=>{state=await api({operation:'status'});queue=state.queue||[];if(state.current){selected=state.current;media={state:-1,seconds:state.seconds||0};watch.hidden=false;title.textContent=selected.title;byline.textContent=selected.channel;drawControls();}await load();if(!queue.length){heading.textContent='Your viewing corner';message('Paste a YouTube link to start watching.')}sync();if(visible)await layout();});
 return {element:root,ready,show(){sync();onMedia(media)},async agent(args){await ready;await api({operation:'status',agent:true});const op=args.operation;if(op==='queue')return load({agent:true});if(op==='open')return openVideo({id:args.id||args.url,title:args.title||'YouTube video'},args.seconds||0,true);if(['play','pause','seek'].includes(op))return control(op,args.seconds,true);if(op==='next')return next(true);if(op==='add_to_queue')return add({id:videoID(args.id||args.url),title:args.title||'YouTube video',channel:''},true);if(op==='remove_from_queue')return remove(args.id,true);if(op==='status')return {untrusted:true,selected,playback:await player({operation:'status',agent:true}),queue};throw Error('Unknown YouTube operation.')}};
}
