export const foxControls = [{
 name:'control_background_music',
 description:'Control Worldlet audio. PODCAST: use operation podcast with show naming the exact programme, for example The Daily, or history. Worldlet resolves one programme through the public Apple directory and plays its newest dated, published non-trailer episode; there is no account and no key. Use episode latest for latest/newest (also the default), and episode resume only to continue an unfinished episode. If the directory reports multiple matches, ask the user to choose using the returned title and publisher; after their choice use its apple:ID as show. Never silently substitute a similarly named programme. For a topic request, ask which exact programme or offer choices rather than guessing. Radio genres are not podcasts. MUSIC: use operation radio with a short English genre tag (rock, soft rock, jazz, classical, electronic, lo-fi/lofi, blues, ambient, chillout, or another requested style) to search free Radio Browser stations and play a live stream. Use next for a different station of the same genre. Generic play/resume continues the selected source; on first use it starts chillout radio. Music faster/slower means finding a matching style, not an exact BPM guarantee. Radio may include ads/talk and cannot select a particular song/artist, rewind or resume an old position. AMBIENCE: channel ambience and play track ocean, rain, forest (curated CC0 field recordings) or village (offline synthesized bed). OFFLINE MUSIC: only when requested, play track calm, focus or brisk (legacy built-in loops). Both channels support pause, stop, resume, quieter/louder and volume 0–1. Multiple requested changes can use separate calls. Keep the other channel playing unless asked to change it. Available without private sources; do not transmit personal context to the radio directory. Only confirm playing from a playing receipt; loading/buffering/errors are not success. No arbitrary URLs, paid account, generation API, specific song playback or automatic downloads.',
 parameters:{type:'object',properties:{operation:{type:'string',enum:['podcast','radio','next','play','resume','pause','stop','volume','quieter','louder','status']},genre:{type:'string',minLength:2,maxLength:60,description:'Short English Radio Browser genre tag; only valid with operation radio.'},show:{type:'string',minLength:2,maxLength:80,description:'Exact programme name, optionally with publisher; or apple:ID from a directory choice the user selected.'},episode:{type:'string',enum:['latest','resume'],description:'Podcast only: latest ignores saved progress; resume continues the saved episode.'},volume:{type:'number',minimum:0,maximum:1},channel:{type:'string',enum:['music','ambience']},track:{type:'string',enum:['calm','focus','brisk','village','ocean','rain','forest']}},required:['operation'],additionalProperties:false}

},{
 name:'control_local_music',
 description:'Control the music app the person is playing on this computer (Apple Music, Spotify, 汽水音乐, QQ 音乐, a browser tab: whichever the system says is playing), not Worldlet\'s own sound. status says what is playing and in which app; play, pause, toggle, next and previous go to that player. Apple Music only (Mac): playlists lists their playlists with IDs, play_playlist plays one by ID, search finds songs in their library by words, play_track plays one by the ID search returned. Never guess an ID; search or list first. Use control_background_music only for Worldlet\'s radio, podcasts and ambience. Confirm only from the result.',
 parameters:{type:'object',properties:{operation:{type:'string',enum:['status','play','pause','toggle','next','previous','playlists','play_playlist','search','play_track']},id:{type:'string',pattern:'^[0-9A-F]{16}$',description:'A playlist or song ID from playlists or search.'},query:{type:'string',minLength:1,maxLength:120,description:'Words to find in the Apple Music library (search only).'}},required:['operation'],additionalProperties:false}
},{
 name:'open_worldlet_controls',
 description:'Help the user manage Worldlet through Fox. Open a small inline guide for connections/imports, organizing private sources, privacy permission, model connection, voice, local backup/restore (data), how Fox speaks, switching between sample and personal worlds, opening Worldlet at login (login), or opening text input. This only opens guidance; it never grants consent or claims authorization or sync success. Use when the user asks to connect an account, change a model or setting, import sources, or organize their world. Never ask them to find a Settings panel.',
 parameters:{type:'object',properties:{screen:{type:'string',enum:['preferences','sources','organize','model','privacy','voice','style','world','data','login']},provider:{type:'string',enum:['google','gmail','google-calendar','google-drive','notion','github','doordash']}},required:['screen'],additionalProperties:false}
},{
 name:'set_worldlet_preference',
 description:'When explicitly requested, set attention_focus (auto/work/personal: auto uses weekdays 09:00–18:00 local time; urgent items always lead), companion_name (1–24 characters), companion_motion (idle/happy/waving/sleeping), spoken_replies (boolean), spoken_voice (installed voice ID from the Voice guide, empty for automatic language), text size, or save how Fox speaks (companion_style: the user\'s own words for tone, length or what to call them; an empty value forgets it), or what the 6 AM morning brief holds (morning_brief: the whole list, one part a line in the user\'s own words, for example "Today\'s schedule\nReply drafts for the mail that needs me\nAI news on X"; send the full new list, keeping the parts they did not ask to drop; an empty value restores the default), when the user explicitly asks. Read the success receipt before confirming. This cannot enable private model processing or change credentials.',
 parameters:{type:'object',properties:{setting:{type:'string',enum:['text_size','companion_style','companion_name','companion_motion','spoken_replies','spoken_voice','attention_focus','morning_brief']},value:{oneOf:[{type:'number',enum:[1,1.25,1.5,2]},{type:'boolean'},{type:'string',maxLength:240}]}},required:['setting','value'],additionalProperties:false}
}];
