import {MADE_GAME_LIMITS} from '../games/index.ts';
// The Game Factory (core/games/README.md). make_game hands the work to the Factory as an Applet task;
// save_game and read_made_game belong to that task only.
const id={type:'string',pattern:'^game-[a-z0-9]{10}$'};
export const gameTools=[
 {type:'function',name:'make_game',description:'Have the Game Factory make a small game the person asked for in their own words this turn ("I want a game like Flappy Bird but with a fox"), or change one it made before (replaces: the game ID from list_made_games). It runs in the background on the person\'s own Agent and returns at once; the game appears at the front of the Games area when it is ready and Fox says so. Write the idea in their words, with every detail they gave. One game is made at a time.',
  parameters:{type:'object',properties:{idea:{type:'string',minLength:1,maxLength:1200},replaces:id},required:['idea'],additionalProperties:false}},
 {type:'function',name:'list_made_games',description:'List the games the Game Factory made in this World, newest first, with their IDs, titles and one-line descriptions. Reads nothing else.',parameters:{type:'object',properties:{},required:[],additionalProperties:false}},
 {type:'function',name:'save_game',description:`Game Factory task only. Save the game you wrote as ONE complete, self-contained HTML document: doctype, head, body, inline <style> and inline <script>. It runs offline in a sandbox, so use no external files, fonts, images, links or network requests of any kind (fetch, XMLHttpRequest, WebSocket, iframes, forms, workers, cookies and navigation are blocked); draw with canvas, DOM and CSS, SVG or emoji, and make sounds with the Web Audio API if any. The page must fill its window and resize with it (about 900×600 in the app, down to 360 px wide), show its board or start screen at once, say the controls in one short line on screen, work with keyboard and mouse (and touch where it fits), have a way to restart, and stay under ${MADE_GAME_LIMITS.bytes/1000} KB (keep it compact, about 8 to 25 KB, so it fits in one reply). Call window.worldlet.best(score) with a score worth keeping (higher is better); local storage works but is forgotten when the game closes. Write the visible text in the person's language. title: a short name (up to ${MADE_GAME_LIMITS.title} characters); blurb: one line saying what you do in it; color: an #rrggbb accent. Worldlet checks the page and plays it for a few seconds offline; if it returns problems, fix every one and save again. replaces: only when changing a game you were asked to change.`,
  parameters:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:MADE_GAME_LIMITS.title},blurb:{type:'string',maxLength:MADE_GAME_LIMITS.blurb},color:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},html:{type:'string',minLength:1,maxLength:MADE_GAME_LIMITS.bytes},replaces:id},required:['title','blurb','color','html'],additionalProperties:false}},
 {type:'function',name:'read_made_game',description:'Game Factory task only. Read the current page of a game the person asked to change, by its ID.',parameters:{type:'object',properties:{id},required:['id'],additionalProperties:false}},
];
