import {WORLD_APPS} from '../applets/index.ts';
import {tool,string} from './schema.ts';
// GPT-Live uses its own /v1/live/sessions protocol, not Realtime calls.
export const worldTools = [
  {type:'function',name:'manage_weather_location',description:'Manage the real weather location only when requested. Search by city name, show the returned city/region/country choices, and select only a matching choice ID from the latest search. Ask which city when ambiguous; never invent a choice. Clear removes the saved place and forecast. Status reports the saved place and weather availability. This does not request device location or change visual weather overrides.',parameters:{type:'object',properties:{operation:{type:'string',enum:['search','select','clear','status']},query:{type:'string',minLength:1,maxLength:100},choice:{type:'string',maxLength:100}},required:['operation'],additionalProperties:false}},
  tool('set_scene_lighting','Preview day or night lighting when requested, with a smooth transition. Visual preview only: do not claim the local time has changed. Use actual to restore real daylight.',{lighting:{type:'string',enum:['day','night','actual']}}),
  tool('set_scene_weather','Change the village visual weather only when requested. This does not change the real forecast or location. Use actual to restore the forecast-driven sky.',{weather:{type:'string',enum:['actual','clear','cloud','rain','snow']}}),
  tool('scroll_browser', 'Scroll the currently visible Worldlet Applet website up or down. Use when asked to scroll the browser, including YouTube. This only moves the page and returns scroll position, never page contents; no private-context consent is needed. If no browser is open, first open the requested Applet.', {direction:{type:'string',enum:['up','down']}}),
  tool('open_applet', 'Open an Applet when the user asks to open, show, go to, or take them there. All catalog Applets can be opened directly, including those not displayed on the ground or not previously used. Never ask the user to add an Applet first. Opening does not install external desktop software, connect accounts or grant permissions. Available even before private-context consent; opens the device or its website without reading account contents. Call directly using this public catalog: '+WORLD_APPS.map(app=>`${app.title}: ${app.id}`).join('; '), {id:{type:'string',enum:WORLD_APPS.map(app=>app.id)}}),
  tool('start_applet_task', 'Hand a task that takes several steps in one Applet (for example searching a website, comparing options, filling a form or preparing an order) to that Applet, so it works in the background while the conversation continues. Use only for work the user asked for this turn; write the whole task in their words. Returns at once with a task ID; the Applet shows it is working, and its result comes back to the user when it is done. Quick things (opening an Applet, scrolling, one look at a page, reading a connected source) stay in the current turn.', {applet:{type:'string',enum:WORLD_APPS.map(app=>app.id)},task:{type:'string',minLength:1,maxLength:2000}}),
  {type:'function',name:'inspect_world',description:'Read a compact directory of actual world locations and current actions. No notes are included; use find_content for notes. Optional query filters by title or ID; offset pages each directory (40 entries).',parameters:{type:'object',properties:{query:{type:'string',maxLength:160},offset:{type:'integer',minimum:0}},required:[],additionalProperties:false}},
  tool('find_content', 'Search the notes saved in this world and return a few matches with short summaries.', { query: string('What the user is looking for, for example a trip, a bill or a project') }),
  tool('visit_place', 'Move the camera to a place that exists in the world, such as a region or an Applet.', { id: string('A place ID returned by inspect_world'), level: { type: 'string', enum: ['place', 'room', 'shelf'] } }),
  tool('open_content', 'Open a note that exists and move the camera to it. Returns an excerpt of its text.', { id: string('A note ID from a search result') }),
  tool('read_content', 'Read a bounded amount of one note\'s text without moving the camera.', { id: string('A note ID') }),
  tool('move_view', 'Return to the world overview, go back one level, or move to the next item.', { direction: { type: 'string', enum: ['overview', 'back', 'next'] } }),
];
