import {WIDGET_LIMITS,READY_APPLETS} from '../artifacts/index.ts';
// Moment Applets (core/artifacts/README.md). make_applet hands the work to an Applet task that makes it;
// save_applet and read_applet belong to that task only.
const id={type:'string',pattern:'^wgt-[a-z0-9]{10}$'};
const data={type:'string',minLength:2,maxLength:WIDGET_LIMITS.dataBytes,description:'What the page shows, as JSON text (an object or array): the events, items, numbers or lines that may change. The page reads it as window.worldlet.data.'};
const endsAt={type:'string',maxLength:40,description:'When the moment is over, an ISO 8601 date-time with the UTC offset (for a day at a museum, its closing time or the end of that day). At most two weeks away.'};
export const widgetTools=[
 {type:'function',name:'make_applet',description:'Make a new Applet the person asked for in their own words this turn, for a moment in their life: one small interactive page used on the computer and on their phone, such as a guide for today\'s museum visit with a map, timed stops and artworks to tick off, a packing list for a trip, a plan for tonight\'s dinner. Or change one made before (replaces: its ID from list_made_applets). It runs in the background and returns at once; when ready the new Applet appears in their World (Home), at the top of Now and on the phone, and Fox says so. It puts itself away when its moment is over. Write the request in their words with every detail they gave (place, date, people, what they care about), and when it ends.',
  parameters:{type:'object',properties:{idea:{type:'string',minLength:1,maxLength:1200},endsAt,replaces:id,website:{type:'string',maxLength:2000,description:'Make this website an Applet instead of writing a page: its https address. Added at once under the site\'s name and icon; it opens the site in the Browser with the person\'s sign-ins. Only when they asked to make a website (or the page open now) an Applet.'},ready:{type:'string',enum:READY_APPLETS.map(applet=>applet.key),description:'Add a ready-made Applet at once instead of writing one: '+READY_APPLETS.map(applet=>`${applet.key} (“${applet.title}”, ${applet.about})`).join('; ')+'. Prefer it whenever it fits what they asked.'}},required:['idea'],additionalProperties:false}},
 {type:'function',name:'list_made_applets',description:'List the Applets Fox made for a moment in this World, newest first: the ones for now and the ones whose moment is over, with their IDs, titles, one-line descriptions and ends. Reads nothing else.',parameters:{type:'object',properties:{},required:[],additionalProperties:false}},
 {type:'function',name:'save_applet',description:`Applet-making task only. Save the Applet you wrote as ONE complete, self-contained HTML document: doctype, head, body, inline <style> and inline <script>. It runs offline in a sandbox on the computer and on the person's phone, so use no external files, fonts, images, links or network requests of any kind (fetch, XMLHttpRequest, WebSocket, iframes, forms, workers, cookies and navigation are blocked); draw maps and pictures with inline SVG, CSS or emoji. Design for a phone first: 360 to 430 px wide, comfortable touch targets, one scrolling column, a calm paper-like look with one accent color; it must also look right in a wider window (keep content within about 640 px). Show what matters now at the top (for a timed plan: the current or next step, worked out from the real clock). Put the content that may change later (events, items, prices, lines, numbers) in data, not in the markup, and draw it from window.worldlet.data (null when there is none) when the page loads: Fox can then update the data later without rewriting the page. Keep EVERYTHING the person checks, marks, picks or types in localStorage (getItem/setItem with string values, JSON for structure) and restore it on load: Worldlet keeps localStorage for this Applet and syncs it between the computer and the phone, so a box ticked on the phone shows ticked on the computer. Include undo for anything marked done. Write the visible text in the person's language, with real, specific content (names, times, places) rather than placeholders. Stay under ${WIDGET_LIMITS.bytes/1000} KB (about 10 to 40 KB is plenty). title: a short name (up to ${WIDGET_LIMITS.title} characters); blurb: one line saying what it is for; color: an #rrggbb accent; endsAt: when the moment is over (ISO 8601 with offset). Worldlet checks the page and runs it for a few seconds at phone size; if it returns problems, fix every one and save again. replaces: only when changing an Applet you were asked to change.`,
  parameters:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:WIDGET_LIMITS.title},blurb:{type:'string',maxLength:WIDGET_LIMITS.blurb},color:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},endsAt,html:{type:'string',minLength:1,maxLength:WIDGET_LIMITS.bytes},data,replaces:id},required:['title','blurb','color','endsAt','html'],additionalProperties:false}},
 {type:'function',name:'read_applet',description:'Applet-making task only. Read the current page and data of a made Applet the person asked to change, by its ID.',parameters:{type:'object',properties:{id},required:['id'],additionalProperties:false}},
 {type:'function',name:'update_applet_data',description:'Update what one of the person\'s page Applets shows without rewriting its page: send its whole new data as JSON text (read the current data first with read_applet_data, and keep its shape). Use it when the person asks to refresh or change an Applet\'s contents, or in a routine they set up to keep it current (for example each morning from their calendar). The page loads again with it on the computer and the phone; what they ticked stays.',parameters:{type:'object',properties:{id,data},required:['id','data'],additionalProperties:false}},
 {type:'function',name:'read_applet_data',description:'Read the data one of the person\'s page Applets shows (null when its page keeps everything in its markup), by its ID from list_made_applets.',parameters:{type:'object',properties:{id},required:['id'],additionalProperties:false}},
];
