// Generated by `npm run theme:import`: every bundled theme package. Do not edit by hand.
import theme_blueprint from './blueprint/index.ts';
import theme_village from './village/index.ts';
import theme_village_map from './village-map/index.ts';
export const THEME_PACKAGES=[theme_blueprint,theme_village,theme_village_map];
