// Generated by `npm run theme:import`: every bundled theme package, the default first. Do not edit by hand.
import theme_village from './village/index.ts';
import theme_blueprint from './blueprint/index.ts';
export const THEME_PACKAGES=[theme_village,theme_blueprint];
