import manifest from './theme.json' with {type:'json'};
import presentation from './presentation.json' with {type:'json'};
import data_0 from './assets/art.json' with {type:'json'};
import data_1 from './lamps.json' with {type:'json'};
/** Generated by theme:import: the package as the host registry reads it. */
export default {manifest,presentation,data:{'assets/art.json':data_0,'lamps.json':data_1}};
