import theme from './entry.ts';
import manifest from './theme.json' with {type:'json'};
import presentation from './presentation.json' with {type:'json'};
/** Generated by theme:import: the package as the host registry reads it. */
export default {theme,manifest,presentation};
