import manifest from './theme.json' with {type:'json'};
import presentation from './presentation.json' with {type:'json'};
import data_0 from './artifact-style/manifest.json' with {type:'json'};
import data_1 from './assets/art.json' with {type:'json'};
import data_2 from './lamps.json' with {type:'json'};
import data_3 from './pack.json' with {type:'json'};
import data_4 from './style.json' with {type:'json'};
import data_5 from './tokens.json' with {type:'json'};
import data_6 from './world.json' with {type:'json'};
/** Generated by theme:import: the package as the host registry reads it. */
export default {manifest,presentation,data:{'artifact-style/manifest.json':data_0,'assets/art.json':data_1,'lamps.json':data_2,'pack.json':data_3,'style.json':data_4,'tokens.json':data_5,'world.json':data_6}};
