import {node,textButton as button} from '../../components/index.ts';
const el:(tag:string,cls?:string,text?:unknown)=>any=node;
export function stripeMoney(amount,currency='usd') {
  try { const code=String(currency).toUpperCase(),fmt=new Intl.NumberFormat('en-US',{style:'currency',currency:code});const digits=['ISK','UGX'].includes(code)?2:fmt.resolvedOptions().maximumFractionDigits;return fmt.format(Number(amount)/10**digits); }
  catch { return `${amount} ${String(currency).toUpperCase()} (minor units)`; }
}
const date=value=>{if(!value)return '—';const d=new Date(typeof value==='number'?value*1000:value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
export function createStripeApplet({native,content,notify=(_text: string)=>{}}) {
  const root=el('section','stripe-applet');root.setAttribute('aria-label','Stripe revenue and customers');
  const header=el('div','stripe-toolbar'),eyebrow=el('span','stripe-eyebrow','REVENUE & RELATIONSHIPS'),actions=el('div','stripe-actions');
  const account=button('Connect Stripe',()=>run(configure),'stripe-connect'),refresh=button('Refresh',()=>run(reload)),dashboard=button('Stripe Dashboard ↗',()=>run(()=>api({operation:'external'})));
  actions.append(refresh,account,dashboard);header.append(eyebrow,actions);
  const status=el('p','stripe-message');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
  const nav=el('nav','stripe-tabs');nav.setAttribute('aria-label','Stripe views');
  const overviewTab=button('Overview',()=>run(()=>select('overview'))),customersTab=button('Customers',()=>run(()=>select('customers')));nav.append(overviewTab,customersTab);
  const body=el('div','stripe-body'),footer=el('p','stripe-footnote');root.append(header,nav,status,body,footer);
  let state: any={connected:false},overview=null,customers=[],nextPage='',customerDetail=null,selectedCustomerID='',view='overview',query='',visible=false,generation=0,busy=false,shown=false;
  const api=args=>{if(!native?.stripe)throw Error('Open Stripe in the Worldlet Mac app to connect your account.');return native.stripe(args)};
  const message=(text,error=false)=>{status.textContent=text;status.dataset.error=String(error)};
  async function run(fn){try{return await fn()}catch(error){message(error.message||String(error),true);return null}}
  function chrome(){account.textContent=state.connected?'Connection':'Connect Stripe';refresh.disabled=busy||!state.connected;account.disabled=busy;overviewTab.setAttribute('aria-current',String(view==='overview'));customersTab.setAttribute('aria-current',String(view!=='overview'));root.setAttribute('aria-busy',String(busy));}
  function empty(title,text){const box=el('div','stripe-empty');box.append(el('span','stripe-empty-mark','↗'),el('h2','',title),el('p','',text));return box;}
  function draw(){chrome();body.replaceChildren();footer.textContent='Read-only · Amounts stay in their original currency';
    if(!state.connected){const box=empty('A clear view of your business.','See today’s collected payments, recurring revenue and the customers behind them.');box.append(el('p','stripe-setup-note',state.sample?'Account connections are available in your personal world.':'Sign in on Stripe’s website. The official Stripe CLI handles authorization — no API key to copy. Worldlet only reads your account. Signing in may also update your terminal’s Stripe CLI session.'));if(!state.sample){const connectButton=button('Connect Stripe',()=>run(configure),'stripe-primary');connectButton.disabled=busy;const testButton=button('Connect test mode',()=>run(()=>connect('test')));testButton.disabled=busy;box.append(connectButton,testButton);}body.append(box);return;}
    if(view==='overview')drawOverview();else if(view==='customer')drawCustomer();else drawCustomers();
  }
  function amounts(values){if(!values?.length)return '—';return values.map(v=>stripeMoney(v.amount,v.currency)).join(' · ')}
  function metric(label,value,note){const card=el('article','stripe-metric');card.append(el('span','stripe-label',label),el('strong','stripe-value',value),el('small','',note));return card;}
  function drawOverview(){if(!overview){body.append(empty(busy?'Reading your Stripe account…':'Your overview is ready to load.','Refresh to read the latest account activity.'));return;}
    const intro=el('div','stripe-intro');intro.append(el('h2','','Your business, at a glance.'),el('span','stripe-mode',state.mode==='test'?'TEST DATA':'READ ONLY'));body.append(intro);
    const metrics=el('div','stripe-metrics');metrics.append(metric('Today collected',overview.todayComplete===false?'Incomplete':overview.today?.length?amounts(overview.today):'No payments',`Successful captured payments · ${overview.timezone||'Local timezone'}`),metric('Estimated MRR',overview.mrrComplete===false?'Incomplete':overview.mrr?.length?amounts(overview.mrr):'No recurring revenue','Monthly equivalent of supported recurring prices'),metric('Active subscriptions',String(overview.activeSubscriptions??'Incomplete'),'Within the loaded subscription set'));body.append(metrics);
    const attention=el('section','stripe-section');attention.append(el('div','stripe-section-heading','Needs a closer look'));if(!overview.attention?.length)attention.append(el('p','stripe-quiet','No payment issues found in the loaded records.'));else for(const item of overview.attention){const row=el('div','stripe-attention');row.append(el('span','stripe-signal','!'),el('div','stripe-row-main',item.title||item.id),el('span','stripe-badge',item.status||'Needs attention'));if(item.customer)row.append(button('Customer →',()=>run(()=>loadCustomer(typeof item.customer==='string'?item.customer:item.customer.id))));attention.append(row);}body.append(attention);
    const note=el('details','stripe-method'),summary=el('summary','','How these numbers are calculated');note.append(summary,el('p','','Today collected is captured payment volume, not profit or payouts. Estimated MRR is a monthly equivalent, not recognized revenue. No currency conversion is applied.'));for(const limitation of overview.limitations||[])note.append(el('p','',String(limitation)));body.append(note);
    footer.textContent=`Read-only · Updated ${date(overview.asOf)} · ${overview.timezone||'Local timezone'}`;
  }
  function drawCustomers(){const heading=el('div','stripe-section-heading');heading.append(el('h2','','Your customers'),el('span','stripe-count',`${customers.length} loaded`));const search=el('input','stripe-search');search.type='search';search.placeholder='Search loaded customers';search.setAttribute('aria-label','Search loaded customers by name, email or ID');search.value=query;const list=el('div','stripe-customer-list');
    function results(){list.replaceChildren();const needle=query.trim().toLowerCase(),filtered=customers.filter(c=>[c.name,c.email,c.id].some(v=>String(v||'').toLowerCase().includes(needle)));if(!filtered.length)list.append(el('p','stripe-quiet',busy?'Loading customers…':needle?'No match in the loaded customers. Load more to search further.':'No customers in the loaded records.'));for(const c of filtered){const row=button('',()=>run(()=>loadCustomer(c.id)),'stripe-customer');const avatar=el('span','stripe-avatar',String(c.name||c.email||'?').slice(0,1).toUpperCase()),identity=el('span','stripe-row-main');identity.append(el('strong','',c.name||c.email||'Unnamed customer'),el('small','',c.email||c.id));row.append(avatar,identity,el('span','stripe-arrow','→'));list.append(row)}}
    search.oninput=()=>{query=search.value;results()};body.append(heading,search,el('p','stripe-search-hint','Search applies to loaded customers only.'),list);results();if(nextPage){const more=button('Load more customers',()=>run(()=>loadCustomers(true)),'stripe-more');more.disabled=busy;body.append(more);}
  }
  function drawCustomer(){body.append(button('← All customers',()=>{view='customers';draw()},'stripe-back'));if(!customerDetail){body.append(empty(busy?'Loading customer…':'Customer unavailable',busy?'Reading billing activity from Stripe.':'Use Refresh to try this customer again.'));return;}const c=customerDetail.customer||{},identity=el('div','stripe-customer-identity');identity.append(el('span','stripe-avatar',String(c.name||c.email||'?').slice(0,1).toUpperCase()),el('h2','',c.name||c.email||'Unnamed customer'));body.append(identity,el('p','stripe-customer-email',c.email||'No email on file'),el('p','stripe-customer-id',c.id||''),button('View in Stripe ↗',()=>run(()=>api({operation:'external',id:c.id})),'stripe-link'));
    for(const [key,label] of [['subscriptions','Subscriptions'],['payments','Recent payments'],['invoices','Recent invoices']]){const section=el('section','stripe-section');section.append(el('h3','',label));const rows=customerDetail[key]||[];if(!rows.length)section.append(el('p','stripe-quiet','No records found in this read.'));for(const item of rows){const row=el('div','stripe-record'),main=el('div','stripe-row-main');main.append(el('strong','',item.name||item.description||item.number||item.id),el('small','',date(item.created)));row.append(main);const amount=item.amount??item.amountPaid??item.amount_paid??item.total;if(amount!==undefined)row.append(el('strong','stripe-record-amount',stripeMoney(amount,item.currency)));row.append(el('span','stripe-badge',String(item.status||'').replaceAll('_',' ')));section.append(row);}body.append(section);}
    footer.textContent=customerDetail.limited?'Read-only · Some records were not loaded · Open Stripe for complete history':'Read-only · Recent billing records · Open Stripe for complete history';
  }
  async function request(operation,args={},apply){const token=++generation;busy=true;message('Reading Stripe…');draw();try{const result=await api({operation,...args});if(token!==generation)return result;apply(result);message('');return result;}catch(error){if(token===generation){message(error.message||String(error),true);throw error;}}finally{if(token===generation){busy=false;draw();}}}
  async function loadOverview(agent=false){return request('overview',{agent},result=>{overview=result;window.dispatchEvent(new CustomEvent('worldlet:stripe-summary',{detail:result}));})}
  async function loadCustomers(append=false,agent=false,page=nextPage){return request('customers',{...(append?{page}:{}),agent},result=>{customers=append?[...customers,...(result.items||[])]:result.items||[];nextPage=result.nextPage||'';})}
  async function loadCustomer(id,agent=false){if(!id)throw Error('Choose a customer first.');view='customer';selectedCustomerID=id;customerDetail=null;return request('customer',{id,agent},result=>{customerDetail=result;})}
  async function select(next){view=next;draw();if(!state.connected)return;if(next==='overview'&&!overview)return loadOverview();if(next==='customers'&&!customers.length)return loadCustomers();}
  async function reload(){if(!state.connected)return;if(view==='customer')return loadCustomer(selectedCustomerID);if(view==='customers')return loadCustomers();return loadOverview();}
  async function configure(){if(state.sample||busy)return;if(state.connected){body.replaceChildren();const box=empty('Stripe is connected.',`Read-only access · ${state.mode==='test'?'Test':'Live'} mode · ${state.account||''}`);box.append(button('Reconnect in browser',()=>run(()=>connect()),'stripe-primary'),button('Connect test mode',()=>run(()=>connect('test'))),button('Disconnect Stripe',()=>run(async()=>{generation++;state=await api({operation:'disconnect'});overview=null;customers=[];nextPage='';customerDetail=null;view='overview';draw();message('Stripe disconnected from Worldlet. Manage CLI authorization in Stripe to revoke access.');})),button('Back to overview',()=>{view='overview';draw()}));body.append(box);return;}return connect();}
  async function connect(mode='live'){const token=++generation;busy=true;state={...state,connected:false};overview=null;customers=[];nextPage='';customerDetail=null;view='overview';draw();message('Opening Stripe sign-in in your browser…');try{let next=await api({operation:'configure',mode});if(token!==generation)return;if(next.authorizing){body.replaceChildren();const box=empty('Finish signing in on Stripe.','After you approve in your browser, this view updates automatically.');if(next.verificationCode)box.append(el('p','stripe-setup-note',`If Stripe asks for a verification code: ${next.verificationCode}`));box.append(button('Cancel sign-in',()=>run(async()=>{generation++;await api({operation:'cancel'});busy=false;draw();message('Sign-in canceled.');})));body.append(box);message('Waiting for Stripe authorization…');next=await api({operation:'complete'});if(token!==generation)return;}state=next;overview=null;customers=[];nextPage='';customerDetail=null;view='overview';if(state.connected){message('Stripe connected.');notify('Stripe connected.');await loadOverview();}else message('Connection canceled.');}catch(error){if(token===generation)throw error;}finally{if(token===generation){busy=false;draw();}}}
  function hide(){if(!visible)return;visible=false;shown=false;generation++;busy=false;message('');chrome();Promise.resolve().then(()=>api({operation:'cancel'})).catch(()=>{});}
  function sync(){const next=root.isConnected&&!content.hidden&&content.contains(root);if(!next){hide();return;}visible=true;}
  new MutationObserver(sync).observe(content,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden','data-template']});
  const ready=run(async()=>{const token=generation,next=await api({operation:'status'});if(token!==generation)return;state=next;draw();});
  draw();
  return {element:root,ready,show(){sync();if(!visible||shown)return;shown=true;run(async()=>{await ready;const token=generation,next=await api({operation:'status'});if(!visible||token!==generation)return;if(!next.connected){overview=null;customers=[];customerDetail=null;}state=next;draw();if(state.connected&&!busy)await loadOverview();});},hide,async agent(args){await ready;const next=await api({operation:'status',agent:true});state=next;if(args.operation==='status')return next;if(args.operation==='overview'){view='overview';return loadOverview(true)}if(args.operation==='customers'){view='customers';return loadCustomers(Boolean(args.page),true,args.page)}if(args.operation==='customer')return loadCustomer(args.id||args.customer_id,true);throw Error('Unsupported read-only Stripe operation.');},async context(){if(!visible||!state.connected)return null;try{await api({operation:'status',agent:true});}catch{return null;}return{platform:'stripe',untrusted:true,view,overview:view==='overview'?overview:undefined,customer:customerDetail?.customer?.id||null,loadedCustomers:view==='customers'?customers.length:undefined};}};
}
