import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {BUILD_THEME_CONTRACT_VERSION,parseBuildThemeManifest,parseThemePresentation,themeAssetPath} from '../ui/themes/build-theme-contract.ts';
/** A theme is static (resources/themes/CONTRACT.md): pictures, sounds, fonts, licence texts and JSON. Code and stylesheets are refused. */
const STATIC_FILE=/\.(?:json|png|webp|jpg|jpeg|svg|woff2?|ttf|otf|mp3|m4a|wav|ogg|webm|txt|md)$/i;

export async function themeFiles(root:string,prefix=''):Promise<string[]> {
 const result:string[]=[];
 for(const e of await fs.readdir(path.join(root,prefix),{withFileTypes:true})){
  if(e.isSymbolicLink())throw Error('Theme symlink is not supported');
  const p=prefix+e.name;
  if(e.isDirectory())result.push(...await themeFiles(root,p+'/'));else if(e.isFile())result.push(p);else throw Error('Unsupported theme file');
 }
 return result.sort();
}
export async function validateBuildTheme(source:string){
 source=await fs.realpath(source);
 const files=await themeFiles(source),manifest=parseBuildThemeManifest(JSON.parse(await fs.readFile(path.join(source,'theme.json'),'utf8')));
 if(!files.includes('presentation.json'))throw Error('Missing presentation.json');
 const presentation=parseThemePresentation(JSON.parse(await fs.readFile(path.join(source,'presentation.json'),'utf8')));
 for(const font of presentation.fonts)for(const asset of [font.file,font.license])if(!files.includes(themeAssetPath(asset)))throw Error('Missing theme asset: '+asset);
 const hashes:Record<string,string>={};
 for(const file of files){
  // The generated index.ts is the host's import of the package, not the theme's code.
  if(file==='index.ts')continue;
  if(!STATIC_FILE.test(file))throw Error('A theme is static: pictures, sounds, fonts and JSON only, not '+file);
  const bytes=await fs.readFile(path.join(source,file));
  if(bytes.length<1024&&bytes.toString().startsWith('version https://git-lfs.github.com/spec/v1'))throw Error('Run git lfs pull before importing: '+file);
  hashes[file]=createHash('sha256').update(bytes).digest('hex');
  if(file.endsWith('.json')){
   const inspect=(value:unknown)=>{if(typeof value==='string'&&value.startsWith('assets/')){if(!files.includes(themeAssetPath(value)))throw Error('Missing declared asset: '+value);}else if(value&&typeof value==='object')Object.values(value).forEach(inspect);};
   inspect(JSON.parse(bytes.toString()));
  }
 }
 return {manifest,files,hashes};
}
const PACKAGES='ui/theme-packages';
/** The package as the host registry reads it: its manifest, its presentation and every other JSON file it ships by
 * package path (locks aside), which the host's own World code reads through themeData. */
function packageIndex(files:string[]){
 const data=files.filter(f=>f.endsWith('.json')&&!['theme.json','presentation.json','source-lock.json'].includes(f)&&!f.endsWith('.lock.json'));
 return "import manifest from './theme.json' with {type:'json'};\nimport presentation from './presentation.json' with {type:'json'};\n"+
  data.map((f,i)=>`import data_${i} from './${f}' with {type:'json'};\n`).join('')+
  "/** Generated by theme:import: the package as the host registry reads it. */\nexport default {manifest,presentation,data:{"+data.map((f,i)=>`'${f}':data_${i}`).join(',')+"}};\n";
}
/** Bundled package IDs in a stable order. The default theme (Village) is built in, not a package. */
export async function bundledThemes(root:string):Promise<string[]> {
 const ids=(await fs.readdir(path.join(root,PACKAGES),{withFileTypes:true})).filter(e=>e.isDirectory()&&/^[a-z][a-z0-9-]*$/.test(e.name)).map(e=>e.name).sort();
 return ids;
}
/** The registry the app bundles (ui/theme-packages/index.ts): every package directory, nothing else to edit. */
export async function writeThemeRegistry(root:string){
 const ids=await bundledThemes(root),name=(id:string)=>'theme_'+id.replace(/-/g,'_');
 await fs.writeFile(path.join(root,PACKAGES,'index.ts'),'// Generated by `npm run theme:import`: every bundled theme package. Do not edit by hand.\n'+ids.map(id=>`import ${name(id)} from './${id}/index.ts';\n`).join('')+`export const THEME_PACKAGES=[${ids.map(name).join(',')}];\n`);
 return ids;
}
/** Copy an explicitly chosen source package into ui/theme-packages/<id>. It holds no code, so nothing in it runs.
 * Other bundled themes are untouched; importing the same ID again replaces only that package. */
export async function importBuildTheme(source:string,root:string){
 const checked=await validateBuildTheme(source),parent=path.join(root,PACKAGES),dest=path.join(parent,checked.manifest.id);
 await fs.mkdir(parent,{recursive:true});
 const stage=path.join(parent,'.theme-stage-'+randomUUID()),backup=path.join(parent,'.theme-backup-'+randomUUID());
 let moved=false;
 try{
  await fs.mkdir(stage,{recursive:true});
  for(const file of checked.files.filter(f=>f!=='index.ts'&&f!=='source-lock.json')){const target=path.join(stage,file);await fs.mkdir(path.dirname(target),{recursive:true});await fs.copyFile(path.join(source,file),target);}
  // Revalidate the staged bytes, catching source edits made during copying.
  const staged=await validateBuildTheme(stage);
  const hashes=(h:Record<string,string>)=>JSON.stringify(Object.entries(h).filter(([f])=>f!=='index.ts'&&f!=='source-lock.json'));
  if(hashes(staged.hashes)!==hashes(checked.hashes))throw Error('Theme changed during import; retry');
  await fs.writeFile(path.join(stage,'index.ts'),packageIndex(staged.files));
  await fs.writeFile(path.join(stage,'source-lock.json'),JSON.stringify({contractVersion:BUILD_THEME_CONTRACT_VERSION,id:checked.manifest.id,updatedAt:checked.manifest.updatedAt,sha256:staged.hashes},null,2)+'\n');
  try{await fs.rename(dest,backup);moved=true;}catch(error){if(error.code!=='ENOENT')throw error;}
  try{await fs.rename(stage,dest);}catch(error){if(moved)await fs.rename(backup,dest);throw error;}
  if(moved)await fs.rm(backup,{recursive:true});
 }finally{await fs.rm(stage,{recursive:true,force:true});}
 await writeThemeRegistry(root);
 return checked.manifest;
}
/** Publish every bundled package: its assets under theme-assets/<id>/ and the list in themes.json. */
export async function buildThemeSource(root:string,output:string){
 const ids=await bundledThemes(root),published=[];
 // The output directory belongs solely to the bundled packages; stale assets cannot survive a replacement.
 await fs.rm(path.join(output,'theme-assets'),{recursive:true,force:true});
 for(const id of ids){
  const source=path.join(root,PACKAGES,id),checked=await validateBuildTheme(source);
  if(checked.manifest.id!==id)throw Error(`Theme package ${id} declares id ${checked.manifest.id}`);
  for(const file of checked.files.filter(f=>f.startsWith('assets/'))){const dest=path.join(output,'theme-assets',id,file.slice(7));await fs.mkdir(path.dirname(dest),{recursive:true});await fs.copyFile(path.join(source,file),dest);}
  published.push({id,title:checked.manifest.title,updatedAt:checked.manifest.updatedAt});
 }
 await fs.writeFile(path.join(output,'themes.json'),JSON.stringify(published,null,2)+'\n');
 return published;
}
if(process.argv[1]&&await fs.realpath(process.argv[1])===fileURLToPath(import.meta.url)){
 const [command,source]=process.argv.slice(2);
 if(!source||!['check','import'].includes(command))throw Error('Usage: node scripts/build-theme-source.ts check|import /path/to/<id>/package');
 const root=fileURLToPath(new URL('../',import.meta.url));
 console.log(command==='import'?await importBuildTheme(path.resolve(source),root):(await validateBuildTheme(path.resolve(source))).manifest);
}
