import assert from 'node:assert/strict';
import {createContentStore} from '../ui/shell/content-store.ts';
const originals=Array.from({length:2000},(_,i)=>({id:'p'+i,title:'Page '+i,markdown:'Original '+i,text:'Original '+i,children:[],paths:['p'+i+'.md'],revision:'r1'}));
const input=structuredClone(originals),pages=new Map<string,any>(input.map(p=>[p.id,p])),sections=[{id:'room',virtual:true,children:input.map(p=>p.id)}];
let saved:string|null=null;const storage={getItem:()=>saved,setItem:(_key,value)=>{saved=value;}};
const store=createContentStore({pages,sections,key:'test',storage});
const before=new Map(pages);const next=structuredClone(originals);next[3].title='Changed';
store.replaceBase(next,[{id:'room',virtual:true,children:next.map(p=>p.id)}]);
assert.equal([...pages].filter(([id,p])=>!p.virtual&&before.get(id)!==p).length,1,'only the changed source gets a new object');
assert.equal(pages.get('p3').title,'Changed');
pages.get('p4').title='Optimistic';store.replaceBase(next,sections);
assert.equal(pages.get('p4').title,'Page 4','authoritative snapshot resets optimistic mutations');
assert.deepEqual(input,originals,'no mutation leaks to caller');
const edited=store.mutate('patch_content',{id:'p5',revision:'r1',field:'body',old_text:'Original 5',new_text:'Local edit'},{operationId:'edit'});assert.ok(edited.ok);
store.replaceBase(next,sections);assert.equal(pages.get('p5').markdown,'Local edit');
const deleted=store.mutate('delete_content',{id:'p6',revision:'r1'},{operationId:'delete'});assert.ok(deleted.ok);
store.replaceBase(next,sections);assert.ok(!pages.has('p6'));assert.ok(!sections[0].children.includes('p6'));
assert.ok(store.mutate('undo_content',{}, {operationId:'undo'}).ok);assert.ok(pages.has('p6'));
store.replaceBase(next.filter(p=>p.id!=='p7'),sections);assert.ok(!pages.has('p7'));
console.log('PASS 2,000 pages: one changed object; input isolation, authoritative reset, edits, delete, undo, source removal');
