import assert from 'node:assert/strict';
import {CROPS,newGarden,plant,harvest,stage,ripeAt,ripeCount,nextRipe,buyPlot,plotPrice,restoreGarden,whenText} from '../ui/games/garden.ts';
const H=3_600_000,now=new Date('2026-10-03T21:00:00').getTime();
assert.deepEqual(CROPS.map(c=>c.minutes),[30,240,480,720,1320,1440],'crops ripen from half an hour to a day');
for(const c of CROPS)assert.ok(c.sell>c.seed*1.8,`${c.key} pays back its seed`);
const g=newGarden();assert.equal(g.plots.length,6);assert.equal(g.coins,10);
assert.ok(plant(g,0,'radish',now));assert.equal(g.coins,8);
assert.ok(!plant(g,0,'radish',now),'an occupied plot takes no seed');
assert.ok(!plant(g,1,'strawberry',now),'seeds cost coins');
assert.equal(stage(g.plots[0],now),0);assert.equal(stage(g.plots[0],now+11*60_000),1);assert.equal(stage(g.plots[0],now+21*60_000),2);
assert.equal(harvest(g,0,now+29*60_000),0,'nothing is harvested before it is ripe');
assert.equal(nextRipe(g,now),now+30*60_000);
assert.equal(stage(g.plots[0],now+30*24*H),3,'ripe crops wait and never wither');
assert.equal(ripeCount(g,now+H),1);
assert.equal(harvest(g,0,now+H),4);assert.equal(g.coins,12);assert.equal(g.plots[0],null);assert.equal(g.harvested,1);
g.coins=100;assert.equal(plotPrice(g),30);assert.ok(buyPlot(g));assert.equal(g.plots.length,7);assert.equal(plotPrice(g),45);
g.coins=10_000;while(buyPlot(g));assert.equal(g.plots.length,12);assert.equal(plotPrice(g),0);
assert.ok(plant(g,3,'pumpkin',now));assert.equal(ripeAt(g.plots[3]!),now+22*H);
assert.deepEqual(restoreGarden(JSON.parse(JSON.stringify(g))),g,'a saved garden comes back whole');
const odd=restoreGarden({coins:-4,plots:[{crop:'kale',planted:1},null,null,null,null,{crop:'carrot',planted:now}],harvested:'x'});
assert.equal(odd.coins,10);assert.equal(odd.plots[0],null);assert.equal(odd.plots[5]?.crop,'carrot');assert.equal(odd.harvested,0);
assert.deepEqual(restoreGarden(null),newGarden());
assert.equal(whenText(now+25*60_000,now),'in 25 min');
assert.match(whenText(now+12*H,now),/^tomorrow 9:00 AM$/);
assert.match(whenText(now+2*H,now),/^11:00 PM$/);
console.log('PASS Garden crops ripen on the clock, wait when ripe, and restore from storage.');
