import assert from 'node:assert/strict';
import {harnessHandshake,harnessReceive} from '../core/agent/index.ts';
import {validateAgentDescriptor} from '../contracts/agent.ts';
import type {HarnessTurn} from '../contracts/harness.ts';
const caps={streaming:true,tools:true,cancel:true,steer:false,memory:false,sessions:false};
const hello={type:'hello',protocolVersion:1,id:'alternative',capabilities:caps};
assert.deepEqual(harnessHandshake({hello,expectedId:'alternative',action:'chat'}),hello);
for(const patch of [{protocolVersion:2},{id:'other'},{capabilities:{...caps,tools:'yes'}},{capabilities:{...caps,steer:true}}])assert.throws(()=>harnessHandshake({hello:{...hello,...patch},expectedId:'alternative',action:'chat'}));
for(const action of ['configure','modelConfigure','modelCatalog','modelRepair','modelLogin','routine_tick'])assert.throws(()=>harnessHandshake({hello,expectedId:'alternative',action}));
assert.ok(harnessHandshake({hello:{...hello,capabilities:{...caps,routines:true}},expectedId:'alternative',action:'routine_tick'}));
let state:HarnessTurn={requestId:'turn',action:'chat',capabilities:caps,toolIDs:[],finished:false};
const tool={type:'tool',requestId:'turn',id:'read-1',name:'inspect_world',args:{},privateTransport:'discard'};
const accepted=harnessReceive({state,frame:tool});assert.equal(accepted.kind,'event');state=accepted.state;
assert.throws(()=>harnessReceive({state,frame:tool}));
assert.throws(()=>harnessReceive({state,frame:{...tool,id:'read-2',requestId:'old-turn'}}));
assert.throws(()=>harnessReceive({state:{...state,capabilities:{...caps,tools:false}},frame:{...tool,id:'read-2'}}));
assert.throws(()=>harnessReceive({state:{...state,capabilities:{...caps,streaming:false}},frame:{type:'delta',requestId:'turn',text:'hi'}}));
for(const value of [null,[],{message:''},{message:' '},{message:'中'.repeat(43000)}])assert.throws(()=>harnessReceive({state,frame:{type:'result',requestId:'turn',value}}));
const trace={type:'trace',requestId:'turn',kind:'model.result',payload:{usage:{input_tokens:3}}};
assert.throws(()=>harnessReceive({state,frame:trace}));
assert.equal(harnessReceive({state:{...state,capabilities:{...caps,tracing:true}},frame:trace}).kind,'event');
assert.throws(()=>harnessReceive({state:{...state,capabilities:{...caps,tracing:true}},frame:{...trace,kind:'run.succeeded'}}));
const done=harnessReceive({state,frame:{type:'result',requestId:'turn',value:{message:'Finished'}}});
assert.equal(done.state.finished,true);assert.throws(()=>harnessReceive({state:done.state,frame:tool}));
const status=harnessReceive({state:{...state,action:'status'},frame:{type:'result',requestId:'turn',value:{capabilities:{tools:false}}}});
assert.equal(status.kind,'result');if(status.kind==='result')assert.deepEqual(status.value.capabilities,caps);
// Resident Hermes: late frames of retired turns are dropped, never accepted, and private host events stay opt-in.
const hermes={...state,finished:false,capabilities:{...caps,steer:true}};
assert.equal(harnessReceive({state:hermes,frame:{type:'steer_result',requestId:'old-turn',controlId:'c',accepted:false},hermes:true,retired:['old-turn']}).kind,'stale');
assert.throws(()=>harnessReceive({state:hermes,frame:{...tool,id:'read-3',requestId:'other-turn'},hermes:true,retired:['old-turn']}),/unknown turn/);
assert.throws(()=>harnessReceive({state:hermes,frame:{type:'shell',requestId:'turn'},hermes:true}),/Unsupported/);
assert.equal(harnessReceive({state:hermes,frame:{type:'applet',requestId:'turn'},hermes:true}).kind,'host');
assert.throws(()=>harnessReceive({state:hermes,frame:{type:'applet',requestId:'turn'}}));
const steer={type:'steer_result',requestId:'turn',controlId:'c',accepted:true};
assert.deepEqual(harnessReceive({state:hermes,frame:steer,hermes:true}),{state:hermes,kind:'steer',controlId:'c',accepted:true});
assert.throws(()=>harnessReceive({state,frame:steer}));assert.throws(()=>harnessReceive({state,frame:{type:'steered',requestId:'turn'}}));
const descriptor={protocolVersion:1,id:'alternative',name:'Alternative',capabilities:caps};
assert.deepEqual(validateAgentDescriptor({...descriptor,secret:'discard'}),descriptor);
for(const patch of [{id:12},{name:[]},{id:'has spaces'},{capabilities:{}}])assert.throws(()=>validateAgentDescriptor({...descriptor,...patch}));
console.log('PASS shared Harness contract: handshake, optional execution, correlation, duplicate tools, terminal replies, UTF-8 limit, descriptor projection, resident Hermes routing');
// Harness services v2 (contracts/HARNESS.md#harness-services-v2): every local Harness has a valid declaration.
const {validateHarnessServices}=await import('../contracts/harness-services.ts');
const {HARNESS_SERVICES,harnessService,harnessLocation}=await import('../core/agent/harness-services.ts');
for(const id of ['hermes','openclaw','claude-code','codex','pi','remote'])assert.equal(HARNESS_SERVICES[id]?.harness,id);
// Location comes from the declaration and the status, never from a Harness name: only a Harness that declares it is remote.
assert.deepEqual(harnessLocation('remote',{location:{kind:'remote',computer:'Mac mini'}}),{kind:'remote',computer:'Mac mini'});
assert.deepEqual(harnessLocation('pi',{location:{kind:'remote',computer:'Mac mini'}}),{kind:'local'});
assert.deepEqual(harnessLocation('remote',{}),{kind:'local'});
assert.equal(harnessService('openclaw','conversation'),'native');assert.equal(harnessService('hermes','approvals'),'native','Hermes Agent\'s permission prompts are answered in the World');assert.equal(harnessService('openclaw','approvals'),'native','OpenClaw\'s exec approvals are answered in the World over its Gateway WebSocket');assert.equal(harnessService('nobody','conversation'),null);
for(const id of ['openclaw','hermes'])assert.equal(harnessService(id,'agents'),'files','its agents or profiles are read from its folder');
assert.throws(()=>validateHarnessServices({version:1,harness:'x',services:{}}));
assert.throws(()=>validateHarnessServices({version:2,harness:'x',services:{schedule:'magic'}}));
assert.deepEqual(validateHarnessServices({version:2,harness:'x',services:{schedule:'files',unknown:'native'}}).services,{schedule:'files'});
