import assert from 'node:assert/strict';
import {readItemHostRequest} from '../contracts/item-actions.ts';
import {callHost} from '../platform/bridge/host.ts';
const read={action:'worldItemRead',id:'one'},done={action:'worldItemStatus',id:'one',status:'done'};
for(const valid of [read,done,{...done,status:'open',snoozedUntil:'2030-01-01T00:00:00Z'}])assert.deepEqual(readItemHostRequest(valid),valid);
for(const invalid of [null,[],{...read,id:''},{...read,id:1},{...done,status:'sent'},{...done,snoozedUntil:1},{...done,snoozedUntil:null},{...read,status:'read'},{...done,provider:'gmail'}])assert.throws(()=>readItemHostRequest(invalid));
const sent=[];
(globalThis as any).window={worldletHost:{version:1,platform:'macos',request:async body=>{sent.push(body);return {ok:true};}}};
await callHost('worldItemStatus',{id:'one',status:'done'});
await assert.rejects(()=>callHost('worldItemStatus',{id:'one',status:'sent'} as any));
assert.deepEqual(sent,[done]);
console.log('PASS item wire contract: unknown fields, wrong types and source-service status rejected before dispatch');
const {worldItemMutation}=await import('../core/items/index.ts');
const item:any={id:'one',kind:'task',status:'open'},now='2026-09-28T00:00:00Z';
assert.equal(worldItemMutation(item,'read',now,undefined,true).changed,false);
const update={...item,kind:'update'};
const first=worldItemMutation(update,'read',now,undefined,true);
assert.equal(first.item.status,'read');assert.equal(first.changed,true);
assert.equal(worldItemMutation(first.item,'read',now).changed,false);
assert.equal(worldItemMutation({...first.item,status:'done'},'read',now,undefined,true).changed,false);
assert.throws(()=>worldItemMutation(item,'open',now,'2020-01-01T00:00:00Z'));
assert.throws(()=>worldItemMutation(item,'done',now,'2030-01-01T00:00:00Z'));
assert.equal(worldItemMutation(item,'open',now,'2030-01-01T00:00:00Z').item.snoozedUntil,'2030-01-01T00:00:00Z');
console.log('PASS shared item mutation: read-only updates, idempotency and future snooze rules');
