// Mac Info.plist entries shared by the Dev/worktree app (scripts/dev-electron.ts) and the packaged app
// (scripts/package-electron.ts). macOS shows these privacy usage descriptions in its permission prompts;
// a key missing from the bundle can make the request fail or never prompt (#1135), so both apps declare
// the same set. Pure data and hashing only: no IO, so `scripts/mac-app-info-check.ts` runs on any OS.
import {createHash} from 'node:crypto';

export const macUsageDescriptions={
 NSMicrophoneUsageDescription:'Use your microphone in meetings when you allow it, or hold Fox for voice input. Speech is recognized on this Mac.',
 NSCameraUsageDescription:'Use your camera in a meeting when you allow it.',
 NSBluetoothAlwaysUsageDescription:'Let a website use your phone or security key nearby to sign in with a passkey.',
 NSLocationUsageDescription:'After you choose Use current location, update your location while the app is open for sunlight, moon, stars and weather. Only approximate coordinates go to the weather service; your notes are not sent.',
 NSLocationWhenInUseUsageDescription:'Follow your location for sunlight, moon, stars and local weather while the app is open.',
 NSRemindersFullAccessUsageDescription:'Read up to 50 reminders into your local library. Worldlet does not edit reminders.',
 NSAppleEventsUsageDescription:'Read up to 50 Notes, reminders and calendar events into your local library when you connect them, and send the iMessages you write in Messages when you press Send. Model processing requires your permission.',
 NSContactsUsageDescription:'Show the names of the people in your Messages conversations. Contacts stay on this Mac.',
 NSCalendarsFullAccessUsageDescription:'Save the next 30 days from calendars you choose to this Mac. Model processing requires your permission.'
} as const satisfies Record<`NS${string}UsageDescription`,string>;

/** String entries the Dev app writes into its copy of Electron.app's Info.plist (with `plutil -replace`). */
export function devInfoPlistEntries(name:string,bundleId:string,descriptions:Record<string,string>=macUsageDescriptions):[string,string][] {
 return [['CFBundleName',name],['CFBundleDisplayName',name],['CFBundleIdentifier',bundleId],['CFBundleIconFile','WorldletDev.icns'],...Object.entries(descriptions)];
}

/** Every input of the cached Dev bundle; a change to any of them rebuilds and re-signs it. */
export type DevRuntimeInputs={electronInfoPlist:string,icon:string,iconScript:string,name:string,bundleId:string,descriptions?:Record<string,string>,signer?:string};
export function devRuntimeStamp({electronInfoPlist,icon,iconScript,name,bundleId,descriptions=macUsageDescriptions,signer='-'}:DevRuntimeInputs):string {
 return createHash('sha256').update(JSON.stringify({electron:electronInfoPlist,icon,bundleId,name,plaque:iconScript,plist:devInfoPlistEntries(name,bundleId,descriptions),launcher:devLauncherFiles,...(signer==='-'?{}:{signer})})).digest('hex');
}

/** Contents/Resources/app of the Dev bundle. Electron loads Resources/app ahead of its default_app, so opening
 * Worldlet Dev.app itself (Finder, Dock, Spotlight) starts Worldlet instead of Electron's welcome page (owner
 * report 2026-10-02). Launched by the watcher, the app directory arrives as the first argument with the full
 * environment; opened directly there is none, so the launcher reads the last launch's app directory and
 * WORLDLET_* environment from launch.json beside runtime/ (outside the bundle, so its signature stays valid). */
export const devLauncherFiles={
 'package.json':JSON.stringify({name:'worldlet-dev-launcher',productName:'Worldlet',main:'main.cjs',private:true}),
 'main.cjs':`// Generated by scripts/mac-app-info.ts: start the Worldlet Dev build the way Electron's default_app would.
const {app,dialog}=require('electron'),fs=require('node:fs'),path=require('node:path');
const argument=process.argv.slice(1).find(arg=>!arg.startsWith('-'));
let appDir=argument&&path.resolve(argument);
if(!appDir){
 try{const launch=JSON.parse(fs.readFileSync(path.resolve(process.resourcesPath,'../../../..','launch.json'),'utf8'));appDir=launch.appDir;for(const [key,value] of Object.entries(launch.env||{}))if(process.env[key]===undefined)process.env[key]=value;}catch{}
}
let pkg=null;try{pkg=JSON.parse(fs.readFileSync(path.join(appDir,'package.json'),'utf8'));}catch{}
if(!pkg)app.whenReady().then(()=>{dialog.showErrorBox('Worldlet Dev','No Dev build has been launched from this checkout yet. Run npm run dev first.');app.quit();});
else{
 if(!('defaultApp' in process))Object.defineProperty(process,'defaultApp',{configurable:false,enumerable:true,value:true});
 if(pkg.version)app.setVersion(pkg.version);
 if(pkg.productName||pkg.name)app.name=pkg.productName||pkg.name;
 app.setAppPath(appDir);
 require(path.join(appDir,pkg.main||'index.js'));
}
`
} as const;

/** What launch.json keeps for a direct open: the app directory and the WORLDLET_* variables and PATH (Finder
 * starts apps with a minimal PATH, and the app runs local tools). */
export function devLaunchConfig(appDir:string,env:Record<string,string|undefined>){
 return {appDir,env:Object.fromEntries(Object.entries(env).filter(([key,value])=>value!==undefined&&(key.startsWith('WORLDLET_')||key==='PATH')))};
}

/** `/usr/bin/open` arguments that launch the Dev app through LaunchServices. Spawned straight from the Node watcher,
 * macOS counts the watcher as the app's responsible process, so Screen Recording and Microphone requests appeared as
 * "node" (owner report 2026-10-02); launched by LaunchServices the app is its own responsible process and the
 * requests name Worldlet Dev. `open` does not pass its own environment on, so every variable goes with --env, except
 * the ones macOS sets for each launched process itself (__CF*, XPC_*). */
export function devOpenArguments(app:string,appDir:string,log:string,env:Record<string,string|undefined>):string[] {
 const vars=Object.entries(env).filter(([key,value])=>value!==undefined&&/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)&&!/^(?:__CF|XPC_)/.test(key)&&!/[\0\n]/.test(value!)).flatMap(([key,value])=>['--env',`${key}=${value}`]);
 return ['-n','-a',app,'--stdout',log,'--stderr',log,...vars,'--args',appDir];
}

/** The identity that signs the Dev bundle. macOS keeps Microphone and Screen Recording grants for an ad hoc signature
 * only while its exact code hash stays the same, so every rebuild of the bundle asked again (owner report
 * 2026-10-02); a certificate signature keeps the grants across rebuilds because macOS then matches the bundle
 * identifier and certificate. WORLDLET_DEV_SIGN_IDENTITY or WORLDLET_SIGN_IDENTITY wins, then the first valid
 * Developer ID Application or Apple Development identity in `security find-identity -v -p codesigning`; '-'
 * (ad hoc) when there is none. */
export function devSigningIdentity(findIdentity:string,env:Record<string,string|undefined>):string {
 const chosen=env.WORLDLET_DEV_SIGN_IDENTITY||env.WORLDLET_SIGN_IDENTITY;
 if(chosen)return chosen;
 const identities=[...findIdentity.matchAll(/^\s*\d+\)\s+([0-9A-F]{40})\s+"([^"]+)"/gm)].map(m=>({hash:m[1],name:m[2]}));
 for(const kind of ['Developer ID Application: ','Apple Development: ']){const found=identities.find(i=>i.name.startsWith(kind));if(found)return found.hash;}
 return '-';
}
