import assert from 'node:assert/strict';
import {collectNativeActions} from '../ui/shell/native-actions.ts';
const pages=new Map(['mail-a','mail-b','calendar-a','note-a'].map(id=>[id,{id,title:id}]));
const sections=[{id:'mail',module:'mailroom',children:['mail-a','mail-b']},{id:'calendar',theme:'calendar',children:['calendar-a']},{id:'notes',theme:'library',children:['note-a']}];
const base={pages,sections,arrivals:['mail-a','mail-b','calendar-a','deleted'],decisions:[{id:'decision',pageId:'mail-a',label:'SelectQuote'}]};
let model=collectNativeActions(base);
assert.equal(model.activities[0].state,'needsAction');
assert.deepEqual(model.activities.find(a=>a.id==='updates:mail').pageIds,['mail-b']);
model=collectNativeActions({...base,read:new Set(['mail-a','mail-b'])});
assert.equal(model.activities.some(a=>a.id==='decision'),true,'reading is not a decision');
assert.equal(model.activities.some(a=>a.id==='updates:mail'),false,'read updates clear on both surfaces');
model=collectNativeActions({...base,read:new Set(['mail-a','mail-b']),completed:new Set(['decision'])});
assert.deepEqual(model.activities.map(a=>a.id),['updates:calendar']);
model=collectNativeActions({...base,depth:'note',current:'mail-a',lastRead:'note-a'});
assert.deepEqual(model.actions.map(a=>a.id),['decision'],'reader only shows actions for its content');
model=collectNativeActions({...base,pages:new Map([['note-a',pages.get('note-a')]]),lastRead:'note-a'});
assert.equal(model.activities.length,0,'withdrawn objects remove all notifications');
assert.deepEqual(model.actions.map(a=>a.id),['resume:note-a']);
assert.deepEqual(collectNativeActions({pages,sections}).actions,[],'no invented tasks');
console.log('PASS native actions: grouping, read versus completed, withdrawal, context and empty state');
const ledgerPage={id:'note-a',title:'Update',worldItemId:'update-1',worldItemStatus:'open',activities:[{kind:'update',title:'Update'}]};
assert.equal(collectNativeActions({pages:new Map([['note-a',ledgerPage]]),sections,read:new Set(['note-a'])}).activities.length,1,'stale page-read cache cannot hide an open ledger update');
ledgerPage.worldItemStatus='read';
assert.equal(collectNativeActions({pages:new Map([['note-a',ledgerPage]]),sections}).activities.length,0,'read ledger updates stay cleared');
