import assert from 'node:assert/strict';
import {reconcileDeliveries as reconcile,acknowledgeDeliveries as ack} from '../core/tasks/deliveries.ts';
const fact={id:'gmail:1',provider:'gmail',revision:'a',expiresAt:999};
let rows=reconcile([], [fact],{},1);
assert.equal(rows[0].status,'pending');
assert.equal(reconcile(rows,[fact],{},2).length,1);
rows=reconcile(rows,[{...fact,revision:'b'}],{},3);
assert.equal(ack(rows,[{id:fact.id,revision:'a'}],4)[0].status,'pending');
const done=ack(rows,[{id:fact.id,revision:'b'}],4);
assert.equal(done[0].status,'acknowledged');
assert.deepEqual(reconcile(done,[{...fact,revision:'b'}],{},5),done);
assert.deepEqual(reconcile(rows,[fact],{},1000),[]);
assert.equal(reconcile([],[fact],{[fact.id]:'a'},1)[0].status,'acknowledged');
console.log('PASS delivery deduplication, supersession, migration, expiry and revision fencing');
const subscribers=[{consumerId:'attention:center',providers:['*'],enabled:true},{consumerId:'fixture:mail',providers:['gmail'],enabled:true}];
let independent=reconcile([],[fact,{...fact,id:'calendar:1',provider:'google-calendar'}],{[fact.id]:'a'},1,subscribers);
assert.equal(independent.length,3);
assert.equal(independent.find(r=>r.consumerId==='fixture:mail')?.status,'pending','legacy Center receipt must not acknowledge another consumer');
independent=ack(independent,[{id:fact.id,revision:'a'}],2,'fixture:mail');
assert.equal(independent.find(r=>r.consumerId==='fixture:mail')?.status,'acknowledged');
assert.equal(independent.find(r=>r.entityId==='calendar:1')?.status,'pending');
const fresh=reconcile([],[fact],{},1,subscribers);
const centerAck=ack(fresh,[{id:fact.id,revision:'a'}],2);
assert.equal(centerAck.find(r=>r.consumerId==='fixture:mail')?.status,'pending');
assert.equal(reconcile(centerAck,[fact],{},3,[subscribers[1]]).length,1,'removed subscription has no deliveries');
assert.equal(reconcile(centerAck,[fact],{},3,[{...subscribers[0],enabled:false}]).length,0);
assert.equal(reconcile([], [fact,fact],{},1,subscribers).length,2,'duplicate inputs must not duplicate deliveries');
assert.throws(()=>reconcile([], [fact],{},1,[subscribers[0],subscribers[0]]));
console.log('PASS subscriber isolation, provider matching, registration removal and Center-only migration');
const {failDeliveries:fail,retryQuarantinedDeliveries:retry}=await import('../core/tasks/deliveries.ts');
const seeds=[{id:fact.id,revision:'a'}];
let failed=fail(fresh,seeds,'attention:center','unverified_output',false);
assert.equal(failed[0].isolate,true);assert.equal(failed[0].attempts,0);
assert.deepEqual(fail(failed,seeds,'attention:center','model_allowance',true),failed);
assert.deepEqual(fail(failed,seeds,'attention:center','offline',true),failed);
for(let n=0;n<3;n++)failed=fail(failed,seeds,'attention:center','unverified_output',true);
assert.equal(failed[0].status,'quarantined');
assert.equal(failed[1].status,'pending','another consumer must not be quarantined');
assert.equal(ack(failed,seeds,9)[0].status,'quarantined');
assert.equal(reconcile(failed,[fact],{},10,subscribers)[0].status,'quarantined');
assert.equal(reconcile(failed,[{...fact,revision:'b'}],{},10,subscribers)[0].status,'pending','new evidence revision gets a fresh attempt');
assert.equal(retry(failed,'attention:center')[0].attempts,0);
assert.equal(retry(failed,'attention:center')[0].isolate,true);
const {planAttention}=await import('../core/attention/attention-center.ts');
const context=(id:string)=>({...fact,id,sourceId:id,title:'Fixture',text:'Fixture evidence',keys:['shared'],attributes:{},removed:false,changedAt:1,observedAt:1}) as any;
const contexts=[context(fact.id),context('gmail:healthy')];
const plan=planAttention(contexts,{},20,['gmail'],[],failed)!;
assert.deepEqual(plan.seeds.map(s=>s.id),['gmail:healthy']);
assert.equal(plan.facts.length,1,'quarantined evidence must not leak back as related context');
const isolated=fail(fresh,seeds,'attention:center','unverified_output',false);
const healthyPlan=planAttention(contexts,{},20,['gmail'],[],isolated)!;
assert.deepEqual(healthyPlan.seeds.map(s=>s.id),['gmail:healthy']);
assert.equal(healthyPlan.facts.length,1);
const singlePlan=planAttention([contexts[0]],{},20,['gmail'],[],isolated)!;
assert.equal(singlePlan.facts.length,1);
assert.equal(planAttention([contexts[0]],{},20,['gmail'],[],failed),null);
console.log('PASS bounded singleton quarantine, independent healthy work, manual retry and revision recovery');

const {attentionCoverage}=await import('../core/tasks/deliveries.ts');
const input={available:['a','b'],required:['a','b'],previous:[],processed:['a']};
assert.deepEqual(attentionCoverage(input),{processed:['a'],remaining:['b'],complete:false});
assert.equal(attentionCoverage({...input,previous:['a'],processed:['b']}).complete,true);
assert.equal(attentionCoverage({...input,processed:[]}).complete,false);
assert.throws(()=>attentionCoverage({...input,processed:['invented']}));

const settled=ack(reconcile([], [fact],{},1),[{id:fact.id,revision:fact.revision}],2);
assert.deepEqual(fail(settled,[{id:fact.id,revision:fact.revision}],'attention:center','unverified_output',true),settled,'Later batch failure must not resurrect acknowledged input');

const {recordAttentionProgress}=await import('../core/attention/attention-center.ts');
const progressFacts=[{id:'a',revision:2},{id:'b',revision:3},{id:'related',revision:1}] as any;
const progressPlan={facts:progressFacts,seeds:[{id:'a',revision:2},{id:'b',revision:3}],sweep:true};
const initial={contentVersion:1,seen:{old:1},nextAt:999,attempts:7,lastSweepAt:12,sweepOffset:4};
const partial=recordAttentionProgress(initial,progressPlan,['a','related'],progressFacts);
assert.deepEqual(partial.seen,{a:2},'Related context must not be silently treated as a seed');
assert.equal(partial.nextAt,999);assert.equal(partial.attempts,7);assert.equal(partial.lastSweepAt,12);assert.equal(partial.sweepOffset,4);
assert.deepEqual(recordAttentionProgress(JSON.parse(JSON.stringify(partial)),progressPlan,['b'],progressFacts).seen,{a:2,b:3});
assert.deepEqual(recordAttentionProgress(initial,progressPlan,['a'],[{id:'a',revision:9}] as any).seen,{});
assert.throws(()=>recordAttentionProgress(initial,progressPlan,['invented'],progressFacts));
console.log('PASS durable partial coverage preserves budgets and sweeps and rejects stale/unknown acknowledgements');

let stalled=fail(fresh,seeds,'attention:center','incomplete_coverage',false);
assert.equal(stalled[0].isolate,true);assert.equal(stalled[0].attempts,0);
assert.deepEqual(planAttention(contexts,{},20,['gmail'],[],stalled)!.seeds.map(s=>s.id),['gmail:healthy']);
for(let n=0;n<3;n++)stalled=fail(stalled,seeds,'attention:center','incomplete_coverage',true);
assert.equal(stalled[0].status,'quarantined');
assert.equal(stalled[1].status,'pending');
assert.equal(retry(stalled,'attention:center')[0].status,'pending');
assert.deepEqual(fail(fresh,[{id:fact.id,revision:'older'}],'attention:center','incomplete_coverage',true),fresh);
console.log('PASS incomplete coverage isolates stalled inputs without consuming them or blocking healthy deliveries');

{
 const {attentionCoverage:cover,withheldContextIds}=await import('../core/tasks/deliveries.ts');
 const context=[{id:'["gmail","a"]',provider:'gmail',sourceId:'a'},{id:'["gmail","b"]',provider:'gmail',sourceId:'b'},{id:'["google-calendar","c"]',provider:'google-calendar',sourceId:'c'}];
 const withheld=withheldContextIds({context,rejected:[{sources:[{provider:'gmail',id:'b'}]}]});
 assert.deepEqual(withheld,['["gmail","b"]']);
 const result=cover({available:context.map(c=>c.id),required:context.map(c=>c.id),previous:[],processed:context.map(c=>c.id),withheld});
 assert.deepEqual(result.remaining,['["gmail","b"]'],'only the rejected finding input stays pending');
 assert.deepEqual(withheldContextIds({context:[{id:'x',provider:'gmail'}],rejected:[{sources:[{provider:'gmail',id:'x'}]}]}),['x'],'S records use their own ID as source');
 console.log('PASS rejected findings withhold only their cited inputs; accepted siblings commit');
}
