import assert from 'node:assert/strict';
import {prepareOperation as prepare,transitionOperation as transition} from '../core/tasks/operations.ts';
const input={id:'fixture',ownerId:'gmail',command:'mail.send',scope:'account-hash',reference:'fixture',now:1};
const draft=prepare(input),sent=transition(draft,'submit',2),unknown=transition(sent,'uncertain',3);
assert.equal(unknown.status,'unknown');
assert.throws(()=>transition(draft,'verified',2),'A prepared command has no external attempt to verify');
assert.equal(transition(sent,'verified',3).status,'succeeded');
assert.throws(()=>transition(unknown,'submit',4));
assert.throws(()=>transition(sent,'submit',4));
assert.throws(()=>transition(unknown,'cancel',4));
const done=transition(unknown,'verified',5);
assert.equal(done.status,'succeeded');
assert.equal(transition(done,'verified',6).status,'succeeded','Duplicate trusted confirmation is idempotent');
assert.equal(transition(done,'uncertain',6).status,'succeeded','late exception cannot erase a verified receipt');
assert.throws(()=>prepare({...input,scope:'different-account',existing:done}));
assert.deepEqual(prepare({...input,existing:done}),done);
const cancelled=transition(draft,'cancel',2);
assert.throws(()=>transition(cancelled,'submit',3));
assert.throws(()=>transition(cancelled,'verified',3));
assert.equal(JSON.stringify(done).includes('body'),false);
console.log('PASS durable operation identity, unknown-outcome no-replay, verified receipts and cancellation');
const {operationReport}=await import('../core/tasks/operations.ts');
const report=operationReport([done,unknown],'gmail');
assert.equal(report[1].needsReconciliation,true);
assert.equal(JSON.stringify(report).includes('account-hash'),false);
const {notionOperationOutcome}=await import('../core/tasks/operations.ts');
assert.equal(notionOperationOutcome('verified'),'verified');
for(const status of ['submitted','pending','unconfirmed','failed','unexpected'])assert.equal(notionOperationOutcome(status),'uncertain');
assert.equal(notionOperationOutcome('review'),null);
const rejected=transition(unknown,'not_completed',7);
assert.equal(rejected.status,'not_completed');
assert.throws(()=>transition(rejected,'submit',8));
assert.throws(()=>transition(rejected,'verified',8));
assert.throws(()=>transition(draft,'not_completed',2));

const {browserWorkflowReport}=await import('../core/tasks/operations.ts');
const receipt={id:'receipt-1',operationId:'operation-1',taskID:'task-1',status:'unverified',task:{provider:'gmail'},label:'private label',origin:'https://private.example'};
const workflow=browserWorkflowReport([receipt],[{id:'task-1',provider:'gmail'}],'gmail')[0]!;
assert.equal(workflow.state,'needs_review');assert.equal(workflow.operationId,'operation-1');
assert.deepEqual(workflow.nextAction,{target:'browser',action:'outcome',args:{receiptId:'receipt-1'}});
assert.equal(workflow.canReplay,false);assert.ok(!JSON.stringify(workflow).includes('private'));
assert.equal(browserWorkflowReport([receipt],[{id:'task-1',provider:'gmail'}],'notion').length,0);
assert.equal(browserWorkflowReport([receipt],[])[0]!.nextAction,null);
assert.equal(browserWorkflowReport([{...receipt,status:'user_confirmed'}],[])[0]!.state,'completed');
assert.equal(browserWorkflowReport([{...receipt,status:'not_completed'}],[])[0]!.state,'not_completed');
