import assert from 'node:assert/strict';
import {updateWorldItem,reviewWorldItem,prepareWorldItem,needsAttentionReview,worldItemMutation} from '../core/items/world-item-state.ts';
import {readItemHostRequest} from '../contracts/item-actions.ts';
const now='2026-09-24T10:00:00Z';
for(const status of ['done','dismissed','read']) {
 const item={id:'a',status,statusOrigin:'user'};
 const review=reviewWorldItem(item,'actionable','Still mentioned',[],now);
 assert.equal(review.status,status);assert.equal(review.statusOrigin,'user');
 assert.equal(item.status,status);
 assert.equal(reviewWorldItem({...item,statusOrigin:'agent'},'actionable','Still mentioned',[],now).status,'open');
}
for(const [assessment,status] of [['actionable','open'],['resolved','done'],['uncertain','candidate']])
 assert.equal(reviewWorldItem({},assessment,'Evidence',[],now).status,status);
assert.throws(()=>reviewWorldItem({},'other','Evidence',[],now));
assert.throws(()=>reviewWorldItem({},'resolved','x'.repeat(601),[],now));
assert.equal(reviewWorldItem({},'resolved','👨‍👩‍👧‍👦'.repeat(600),[],now).status,'done');
assert.throws(()=>updateWorldItem({},'candidate',now));
assert.deepEqual(updateWorldItem({id:'a'},'done',now),{id:'a',status:'done',statusOrigin:'user',updatedAt:now});
// The person confirming Fox's work records who did it; their own later status clears it.
const byFox=updateWorldItem({id:'a'},'done',now,undefined,'fox');
assert.equal(byFox.completedBy,'fox');
assert.equal(updateWorldItem(byFox,'open',now).completedBy,undefined);
assert.equal(worldItemMutation(updateWorldItem({id:'a'},'done',now),'done',now,undefined,false,'fox').changed,true,'confirming Fox did it is a change');
assert.equal(worldItemMutation(byFox,'done',now,undefined,false,'fox').changed,false);
assert.deepEqual(readItemHostRequest({action:'worldItemStatus',id:'a',status:'done',by:'fox'}),{action:'worldItemStatus',id:'a',status:'done',by:'fox'});
assert.throws(()=>readItemHostRequest({action:'worldItemStatus',id:'a',status:'dismissed',by:'fox'}));
assert.throws(()=>readItemHostRequest({action:'worldItemStatus',id:'a',status:'done',by:'someone'}));
const prepared=prepareWorldItem({key:'untrusted',status:'open',legacySourceId:'fake'},{status:'done',statusOrigin:'user',createdAt:'before'},'a','stable','run',now);
assert.equal(prepared.status,'done');assert.equal(prepared.createdAt,'before');
assert.equal(prepared.key,undefined);assert.equal(prepared.legacySourceId,undefined);
assert.equal(prepareWorldItem({}, {status:'candidate'},'a','stable','run',now).status,'open');
assert.equal(needsAttentionReview({status:'open'}),true);
assert.equal(needsAttentionReview({status:'open',policyVersion:2}),false);
assert.equal(needsAttentionReview({status:'done'}),false);
console.log('PASS shared item transitions, user overrides, re-extraction and review migration');

const {validateWorldItem}=await import('../core/items/world-item-validation.ts');
const base={provider:'gmail',kind:'task',title:'Reply',context:'A real request',attentionReason:'Needs a reply',sources:[{provider:'gmail',id:'thread',quote:'Please reply'}]};
const dates={start:null,end:null};
validateWorldItem(base,dates);
for(const patch of [{title:''},{title:'\u0085\u200b'},{title:'x'.repeat(201)},{priority:null},{attentionReason:' '},{sources:[]},{sources:[null]},{sources:[{id:'thread',provider:'gmail',quote:''}]}])
 assert.throws(()=>validateWorldItem({...base,...patch},dates));
validateWorldItem({...base,title:'👨‍👩‍👧‍👦'.repeat(200)},dates);
assert.throws(()=>validateWorldItem({...base,kind:'event'},dates));
validateWorldItem({...base,kind:'event',start:'host-parsed'}, {start:1,end:null});
assert.throws(()=>validateWorldItem({...base,kind:'event',end:'before'}, {start:2,end:1}));
validateWorldItem({...base,kind:'event',end:'same'}, {start:2,end:2});
assert.throws(()=>validateWorldItem({...base,end:'invalid'}, {start:2,end:null}));
const account={...base,sources:[{provider:'gmail',id:'alert',quote:'Example Bank card ending 1234 was declined'}]};
validateWorldItem({...account,event:{topic:'Payment declined',subject:'Example Bank card ending 1234'}},dates);
for(const event of [null,{topic:'Payment declined'},{topic:'Payment declined',subject:'Example Bank card ending 9999'},{topic:'Payment declined',subject:'Example Bank 4111111111111234'}])
 assert.throws(()=>validateWorldItem({...account,event},dates),/Invalid world item: event\./);
console.log('PASS item field, Unicode, evidence, priority and date range validation, including grounded event identity');
const {migrateWorldItems}=await import('../core/items/world-item-migration.ts');
const legacy={sources:[{id:'s',origin:'gmail',enabled:true,revision:'r1'}],knowledge:[{sourceId:'s',sourceRevision:'r1',summary:'Context',activities:[{kind:'event',title:'Meet',quote:'Friday',start:'date',allDay:false}]}],originals:{s:{threadId:'abc'}}};
const snapshot=JSON.stringify(legacy);
const migrated=migrateWorldItems(legacy);
assert.equal(migrated[0].identitySeed,'gmail:legacy:s:0');
assert.equal(migrated[0].item.status,'candidate');
assert.equal((migrated[0].item.sources as Record<string,unknown>[])[0].remoteId,'thread:abc');
assert.equal(migrated[0].item.allDay,false);
assert.equal(JSON.stringify(legacy),snapshot);
assert.equal(migrateWorldItems({...legacy,sources:[{...legacy.sources[0],enabled:false}]}).length,0);
assert.equal(migrateWorldItems({...legacy,sources:[{...legacy.sources[0],revision:'r2'}]}).length,0);
assert.deepEqual(migrateWorldItems(legacy),migrated);
console.log('PASS portable legacy item migration, identity seeds, stale-source exclusion and immutability');
const {resolveWorldItemID,matchingWorldItemSource,matchingWorldItemOwnerSource}=await import('../core/items/world-item-identity.ts');
const existing={...base,id:'saved',sources:[{provider:'gmail',id:'local',remoteId:'thread:abc'}]};
const refresh={...base,id:'saved',sources:[{provider:'gmail',id:'thread:abc'}]};
assert.equal(resolveWorldItemID(refresh,existing,undefined,'new-hash'),'saved');
assert.equal(resolveWorldItemID(base,undefined,'old-id','hash'),'old-id');
assert.equal(resolveWorldItemID(base,undefined,undefined,'hash'),'hash');
for(const previous of [undefined,{...existing,id:'other'},{...existing,provider:'notion'},{...existing,kind:'event'},{...existing,sources:[{provider:'gmail',id:'unrelated'}]}])
 assert.throws(()=>resolveWorldItemID(refresh,previous,undefined,'hash'));
assert.equal(matchingWorldItemSource({sources:[{provider:'notes',id:'é'}]},{sources:[{provider:'notes',id:'e\u0301'}]}),true);
assert.equal(matchingWorldItemSource({sources:[]},{sources:[]}),false);
const contextRef={provider:'weather',id:'shared-forecast'};
const composite={...existing,sources:[...existing.sources,contextRef]};
const unrelated={...refresh,sources:[{provider:'gmail',id:'different-thread'},contextRef]};
assert.throws(()=>resolveWorldItemID(unrelated,composite,undefined,'hash'),'explicit ID cannot use context overlap to replace another obligation');
assert(!matchingWorldItemOwnerSource(composite,{sources:[contextRef]}),'a context-only review must be rejected');
assert(matchingWorldItemOwnerSource(composite,refresh),'owner aliases retain compatibility');
assert(!matchingWorldItemOwnerSource({sources:[contextRef]},{sources:[contextRef]}),'missing owner fails closed');
console.log('PASS shared identity selection, source ownership, remote aliases and canonical Unicode equality');
const {visibleWorldItems,queryWorldItems,calendarItemTimes}=await import('../core/items/world-item-projection.ts');
assert.equal(visibleWorldItems([{sources:[{id:'a',local:true}]},{sources:[{id:'b',local:true}]},{sources:[{id:'remote'}]},{sources:[]}],['a']).length,2);
const query=queryWorldItems([{...base,context:'👨‍👩‍👧‍👦'.repeat(501),reviewEvidence:['private history'],sources:[{quote:'x'.repeat(501),id:'source'}]}],[{error:'retry',id:'check'}],'gmail');
assert.equal(query.items[0].context,'👨‍👩‍👧‍👦'.repeat(500));
assert.equal(query.items[0].reviewEvidence,undefined);
assert.equal((query.items[0].sources as Record<string,unknown>[])[0].quote,'x'.repeat(500));
assert.deepEqual(query.checks,[{id:'check',lastError:'retry'}]);
assert.equal(queryWorldItems([base],[],'notion').items.length,0);
const event={kind:'event',provider:'google-calendar',start:'model',end:'stale',allDay:true,sources:[{provider:'google-calendar',id:'event'}]};
const corrected=calendarItemTimes(event,{'google-calendar:event':{start:'original'}});
assert.equal(corrected.start,'original');assert.equal(corrected.end,undefined);assert.equal(corrected.allDay,undefined);assert.equal(event.end,'stale');
assert.deepEqual(calendarItemTimes({...event,sources:[...event.sources,{provider:'google-calendar',id:'second'}]},{'google-calendar:event':{start:'original'}}).start,'model');
console.log('PASS item visibility, bounded query projection and authoritative calendar times');

const {attentionKind,projectWorldItems,refreshItemPage,settleItemPage}=await import('../core/items/world-items.ts');
assert.equal(attentionKind({kind:'event',provider:'gmail'}),'update');
assert.equal(attentionKind({kind:'event',provider:'gmail',eventDisposition:'optional'}),'update');
assert.equal(attentionKind({kind:'event',provider:'gmail',eventDisposition:'confirmed'}),'event');
assert.equal(attentionKind({kind:'event',provider:'gmail',eventDisposition:'important'}),'update');
assert.equal(attentionKind({kind:'event',provider:'google-calendar'}),'event');
const until='2099-01-01T12:00:00Z';
const snoozed=updateWorldItem({id:'s',kind:'event'},'open',now,until);
assert.equal(snoozed.snoozedUntil,until);
assert.throws(()=>updateWorldItem({},'open',now,'yesterday'));
assert.throws(()=>updateWorldItem({},'done',now,until));
assert.equal(updateWorldItem(snoozed,'dismissed',now).snoozedUntil,undefined);
assert.equal(prepareWorldItem({},snoozed,'s','identity','run',now).snoozedUntil,until);
const world={roots:['root'],pages:[]};
projectWorldItems(world,[{...base,id:'s',kind:'event',status:'open',attentionContentVersion:1,snoozedUntil:until}]);
const page=world.pages[0];assert.equal(page.worldItemKind,'update');assert.equal(page.activities.length,0);
refreshItemPage(page,Date.parse(until)+1);assert.equal(page.activities.length,1);assert.equal(page.events.length,0);
settleItemPage(page,'done');assert.equal(page.activities.length,0);
const unprocessed={roots:['root'],pages:[]};
projectWorldItems(unprocessed,[{...base,id:'raw',kind:'event',status:'open',snoozedUntil:until}]);
refreshItemPage(unprocessed.pages[0],Date.parse(until)+1);
assert.equal(unprocessed.pages[0].activities.length,0,'snooze expiry cannot publish unprocessed source copy');
console.log('PASS commitment classification, persistent snooze, expiry and explicit settlement');
const hashA='a'.repeat(64),hashB='b'.repeat(64),hashC='c'.repeat(64);
const settled={kind:'task',status:'done',statusOrigin:'user',identity:hashA,obligationIdentityVersion:1,obligationIdentityAliases:[hashA]};
const continued=prepareWorldItem({kind:'task',obligationIdentityAliases:[hashC]},settled,'saved',hashB,'run',now);
assert.deepEqual(continued.obligationIdentityAliases,[hashA,hashB],'only saved/host identities become aliases');
assert.equal(continued.status,'done');
assert.deepEqual(prepareWorldItem({kind:'task'},continued,'saved',hashA,'run',now).obligationIdentityAliases,[hashA,hashB],'repeated evidence does not grow aliases');
assert.deepEqual(prepareWorldItem({kind:'task'},{kind:'task',identity:hashC},'legacy',hashB,'run',now,hashA).obligationIdentityAliases,[hashA,hashB],'legacy thread-wide identity is replaced by host-computed exact evidence');
assert.equal(prepareWorldItem({kind:'event',obligationIdentityAliases:[hashC]},settled,'event',hashB,'run',now).obligationIdentityAliases,undefined);
console.log('PASS durable obligation aliases, settled-state preservation and rejection of caller-proposed aliases');

const {needsTaskContinuityReview}=await import('../core/items/world-item-identity.ts');
assert.equal(needsTaskContinuityReview({...base,id:'saved'},existing,'new','old'),true);
assert.equal(needsTaskContinuityReview({...base,id:'saved'},existing,'old','old'),false);
assert.equal(needsTaskContinuityReview({...base,id:'saved'},{...existing,obligationIdentityVersion:1,obligationIdentityAliases:['new']},'new','old'),false);
assert.equal(needsTaskContinuityReview({...base,id:'saved',obligationIdentityAliases:['new']},existing,'new','old'),true);
assert.equal(needsTaskContinuityReview({...base,kind:'event',id:'saved'},existing,'new','old'),false);
assert.equal(needsTaskContinuityReview(base,existing,'new','old'),false);
console.log('PASS changed task evidence requires review; only host-saved aliases authorize continuity');

// Synthetic grouped findings retain a finite deferral across serialization and synthesis.
const {attentionLaterUntil}=await import('../core/attention/attention-time.ts');
const {matchingAttentionID}=await import('../core/attention/attention-center.ts');
const deferredUntil=attentionLaterUntil(Date.parse(now),'UTC');
assert.equal(deferredUntil,'2026-09-25T10:00:00.000Z');
const group=updateWorldItem({...base,id:'group',attentionContentVersion:1},'open',now,deferredUntil);
const reload=JSON.parse(JSON.stringify(group));
const grouped={...base,sources:[...base.sources,{provider:'gmail',id:'related',quote:'The documents are attached.'}]};
assert.equal(matchingAttentionID(grouped,[reload]),'group');
const merged=prepareWorldItem(grouped,reload,'group','identity','refresh',now);
assert.equal(merged.snoozedUntil,deferredUntil);
assert.equal(queryWorldItems([merged],[]).items[0].snoozedUntil,deferredUntil);
const resumed={roots:['root'],pages:[]};
projectWorldItems(resumed,[{...merged,attentionContentVersion:1}]);
refreshItemPage(resumed.pages[0],Date.parse(deferredUntil)-1);
assert.equal(resumed.pages[0].activities.length,0,'merged evidence must not immediately undo Later');
refreshItemPage(resumed.pages[0],Date.parse(deferredUntil));
assert.equal(resumed.pages[0].activities.length,1,'the grouped finding returns exactly when due');
const newObligation={...base,sources:[{provider:'gmail',id:'thread',quote:'Please send a separate signed approval.'}]};
assert.equal(matchingAttentionID(newObligation,[reload]),null,'materially distinct obligations do not inherit deferral');
assert.equal(prepareWorldItem(newObligation,undefined,'new','new-identity','refresh',now).snoozedUntil,undefined);
const continuedEvidence=prepareWorldItem(newObligation,reload,'group','changed-identity','approved-continuation',now);
assert.equal(continuedEvidence.snoozedUntil,deferredUntil,'approved continuation keeps the finite user decision');
assert.equal(prepareWorldItem(grouped,{...reload,snoozedUntil:until},'group','identity','refresh',now).snoozedUntil,until,'custom times survive unchanged');
console.log('PASS one-click default, grouped merge/reload, finite reappearance, distinct new evidence and custom snooze preservation');
const mail='Thread, newest first. RECEIVED Status: UNREAD Subject: You need to verify your identity. You will need to verify your identity to publish to Google Play.';
const saved={...existing,sources:[{provider:'gmail',id:'local',remoteId:'thread:abc',quote:mail}]};
const reread=(quote:string,remoteId='thread:abc')=>({...base,id:'saved',sources:[{provider:'gmail',id:'thread',remoteId,quote}]});
assert.equal(needsTaskContinuityReview(reread(mail.replace('UNREAD','READ')),saved,'new','old'),false,'read state alone is the same evidence');
assert.equal(needsTaskContinuityReview(reread('You will need to **verify your identity** to publish'),saved,'new','old'),false,'a shorter quote of the saved passage is the same evidence');
assert.equal(needsTaskContinuityReview(reread('New message: please also send the tax form. '+mail),saved,'new','old'),true,'a longer quote can carry a new request');
assert.equal(needsTaskContinuityReview(reread('verify your identity to publish',"thread:other"),saved,'new','old'),true,'another thread is other evidence');
assert.equal(needsTaskContinuityReview(reread('identity'),saved,'new','old'),true,'a tiny quote proves nothing');
console.log('PASS re-reading the saved passage of the same source is not a changed task');
