import assert from 'node:assert/strict';
import {contextLayout} from '../core/context/context-layout.ts';
import {validateConversationHistory} from '../core/companion/conversation-history.ts';
const original=contextLayout({themes:[{theme:'library'},{theme:'studio'}]});
assert.deepEqual(original.places.map(p=>p.position),[[0,0,2],[0,0,17],[0,0,-13]]);
const next=contextLayout({themes:[{theme:'library'},{theme:'studio'},{theme:'health'}],previous:JSON.stringify(original)});
assert.deepEqual(next.places.slice(0,3),original.places);
assert.throws(()=>contextLayout({themes:[{theme:'unknown'}]}));
assert.throws(()=>contextLayout({themes:[null]}));
assert.deepEqual(contextLayout({themes:[],previous:'broken'}).places[0].position,[0,0,2]);
const colliding={...original,places:original.places.map(p=>({...p,position:[0,0,2]}))};
assert.deepEqual(contextLayout({themes:[{theme:'library'},{theme:'studio'}],previous:JSON.stringify(colliding)}),original);
const all=contextLayout({themes:['home','library','studio','factory','cafe','family','calendar','finance','archive','rocket','health','vision'].map(theme=>({theme}))});
assert.equal(all.places.length,12);
for(const a of all.places)for(const b of all.places)if(a!==b)assert.ok(Math.hypot(a.position[0]-b.position[0],a.position[2]-b.position[2])>=12);
validateConversationHistory([{key:'k',view:'v',text:'👨‍👩‍👧‍👦'.repeat(12000)}],true);
assert.throws(()=>validateConversationHistory([{key:'k',view:'v',text:'x'.repeat(12001)}],true));
assert.throws(()=>validateConversationHistory(Array(81).fill({}),false));
assert.throws(()=>validateConversationHistory([null],false));
validateConversationHistory([{}],false); // Preserve existing read compatibility; strict validation applies on write.
assert.throws(()=>validateConversationHistory([{}],true));
console.log('PASS shared context placement, previous-layout preservation, overlap rejection and conversation bounds');
const {defaultSourceChecks,dueSourceCheck,startSourceCheck,reconcileSourceCheck}=await import('../core/scheduling/source-checks.ts');
const paused={id:'gmail',provider:'gmail',enabled:false,intervalMinutes:60,nextAt:9000};
assert.deepEqual(defaultSourceChecks([paused],['gmail','notion'],100),[{id:'notion',provider:'notion',enabled:true,intervalMinutes:30,nextAt:100}]);
assert.deepEqual(defaultSourceChecks([],['notion'],100,[{provider:'notion',intervalMinutes:45}]),[{id:'notion',provider:'notion',enabled:true,intervalMinutes:45,nextAt:100}],'new checks use the Applet registration interval');
{
 // The host hands the Applet registrations to shared core instead of patching intervals itself.
 const {readFileSync}=await import('node:fs');
 const host=readFileSync(new URL('../platform/electron/src/modules/attention/center.ts',import.meta.url),'utf8');
 assert.match(host,/core\('sourceChecksDefault',\{[^}]*\bregistrations\b/,'the Electron host passes registrations to sourceChecksDefault');
}
assert.equal(dueSourceCheck([paused],['gmail'],100,undefined,true),null,'first mail must not bypass pause');
const active={...paused,enabled:true};
assert.equal(dueSourceCheck([active],['gmail'],100),null);
assert.equal(dueSourceCheck([active],[],100,undefined,true),null,'first mail must not bypass connection eligibility');
assert.deepEqual(dueSourceCheck([active],['gmail'],100,'gmail',true),active);
const started=startSourceCheck(active,100);
assert.equal(started.nextAt,3700);
const finished={...started,lastStatus:'ok'};
assert.deepEqual(reconcileSourceCheck(finished,paused),{...finished,enabled:false,nextAt:9000});
assert.equal(reconcileSourceCheck(finished,{...active,nextAt:1}).nextAt,3700,'unchanged configuration keeps scheduled next run');
assert.equal(active.nextAt,9000,'rules never mutate stored input');
console.log('PASS source schedule defaults, eligibility, due time and concurrent pause/reconfiguration');
const {worldEvent}=await import('../core/items/world-events.ts');
assert.equal(worldEvent('snapshot',{text:'private'}),null);
assert.equal(worldEvent('browser',{operation:'status'}),null);
assert.equal(worldEvent('worldAudio',{operation:'start'}),null);
assert.deepEqual(worldEvent('agentChat',{text:'private',apiKey:'secret',target:'email',provider:'gmail',moduleId:'app-mail',id:'opaque',level:Infinity,place:{private:'nested'}}),{body:{provider:'gmail',moduleId:'app-mail'},applet:'app-mail'});
assert.deepEqual(worldEvent('worldItemStatus',{id:'item-1',enabled:false,level:0,region:'x'.repeat(121)}),{body:{id:'item-1',enabled:false,level:0}});
assert.equal(worldEvent('open',{provider:'🦊'.repeat(120)}).applet,'🦊'.repeat(120));
console.log('PASS event privacy allowlist, bounded identifiers, transport exclusion and scalar state');
const {recentWorldHistory}=await import('../core/items/world-events.ts');
const history=[{kind:'open',body:{provider:'gmail',status:'open'},at:'newest'},{kind:'agentChat',body:{},at:'chat'},{kind:'open',body:{status:'open',provider:'gmail'},at:'duplicate'},{kind:'done',body:{itemId:'one'},at:'older'},{kind:'open',body:{provider:'gmail',status:'open'},at:'oldest'}];
assert.deepEqual(recentWorldHistory(history,2),[{provider:'gmail',status:'open',kind:'open',at:'newest'},{itemId:'one',kind:'done',at:'older'}]);
assert.equal(recentWorldHistory(history,8).length,3,'only consecutive events are collapsed');
assert.equal(recentWorldHistory(history,0).length,0);
assert.equal(history[0].at,'newest');
console.log('PASS recent-history ordering, conversation exclusion and consecutive deduplication');
const {validateAgentCapabilities,validateAgentEvent}=await import('../contracts/agent.ts');
const caps={streaming:true,tools:true,cancel:true,steer:false,memory:false,sessions:true};
assert.deepEqual(validateAgentCapabilities({...caps,privateTransport:'secret'}),caps);
assert.throws(()=>validateAgentCapabilities({...caps,tools:1}));
assert.throws(()=>validateAgentCapabilities({}));
assert.deepEqual(validateAgentEvent({type:'delta',text:'Hello',privateTransport:'secret'}),{type:'delta',text:'Hello'});
assert.deepEqual(validateAgentEvent({type:'model_required'}),{type:'model_required'});
assert.throws(()=>validateAgentEvent({type:'tool',id:'t',name:'read',args:[]}));
console.log('PASS shared Agent capability/event validation and transport metadata exclusion');
const {validateContextAnalysis,validateContextLayout,contextChunks}=await import('../core/context/context-validation.ts');
const knowledge={sourceId:'s',theme:'home',topic:'Mail',summary:'Summary',facts:[{text:'Fact',quote:'Evidence'}]};
assert.equal(validateContextAnalysis([knowledge],[{id:'s',revision:'v2'}],['s'],['home'])[0].sourceRevision,'v2');
assert.throws(()=>validateContextAnalysis([], [{id:'s',revision:'v2'}],['s'],['home']));
assert.throws(()=>validateContextAnalysis([{...knowledge,topic:'x'.repeat(101)}],[{id:'s',revision:'v2'}],['s'],['home']));
assert.throws(()=>validateContextAnalysis([knowledge],[{id:'s',revision:'v2'}],[],['home']));
assert.deepEqual(validateContextLayout(original,['library','studio']),original);
assert.throws(()=>validateContextLayout(colliding,['library','studio']));
assert.throws(()=>validateContextLayout({...original,places:[...original.places,original.places[0]]},['library','studio']));
const unicode='你好🌎 e\u0301\n'.repeat(12000),chunks=contextChunks(unicode);
assert.equal(chunks.join(''),unicode);assert.ok(chunks.every(s=>Buffer.byteLength(s)<=24000));
assert.deepEqual(contextChunks('👨‍👩‍👧‍👦',1),['👨‍👩‍👧‍👦']);assert.deepEqual(contextChunks(''),[]);
console.log('PASS context field validation, source coverage, layout limits and lossless Unicode chunking');
const {receiveAppletActivity,describeAppletActivity,finishAppletActivity,appletActivitySnapshot}=await import('../core/applets/applet-activity.ts');
let activity=receiveAppletActivity(undefined,{callId:'a',phase:'reading'},'turn')!;
activity=receiveAppletActivity(activity,{callId:'b',phase:'reading'},'turn')!;
activity=receiveAppletActivity(activity,{callId:'a',phase:'complete',count:2},'turn')!;
assert.equal(activity.calls.length,1);assert.equal(activity.succeeded,true);
assert.equal(receiveAppletActivity(activity,{callId:'unknown',phase:'complete'},'turn'),null);
assert.equal(receiveAppletActivity(activity,{callId:'b',phase:'complete'},'other'),null);
assert.throws(()=>describeAppletActivity(activity,{summary:'fake',needsAttention:true},'other'));
assert.equal(describeAppletActivity(activity,{summary:'Ready',needsAttention:true},'turn').summary,'Ready');
assert.equal(finishAppletActivity(activity,'turn',true).failed,false);
assert.equal(finishAppletActivity(activity,'turn',false).failed,true);
// A background analysis turn reading the same app keeps Fox's chat turn able to describe what it read.
const taken=receiveAppletActivity(activity,{callId:'analysis',phase:'reading'},'analysis')!;
assert.equal(taken.turn,'analysis');assert.equal(taken.succeeded,false);
assert.equal(describeAppletActivity(taken,{summary:'Read',needsAttention:false},'turn').summary,'Read');
assert.throws(()=>describeAppletActivity(taken,{summary:'fake',needsAttention:false},'analysis'));
const closed=finishAppletActivity(taken,'turn',false);
assert.deepEqual(closed.calls,['analysis']);assert.equal(closed.failed,false);
assert.throws(()=>describeAppletActivity(closed,{summary:'late',needsAttention:false},'turn'));
const projection=appletActivitySnapshot('gmail',true,'connected',[{provider:'gmail',status:'open',kind:'task'}],{lastStatus:'error'},activity);
assert.equal(projection.failed,true);assert.equal(projection.needsAttention,true);assert.equal(projection.running,true);
assert.equal(appletActivitySnapshot('gmail',false,'reading',[],{lastStatus:'running'},activity).running,false);
assert.equal(activity.calls.length,1);
const {sourcesReading}=await import('../core/applets/status.ts');
const synthesizing=appletActivitySnapshot('gmail',true,'connected',[],{lastStatus:'complete'},undefined,undefined,true);
assert.deepEqual([synthesizing.running,synthesizing.synthesizing,sourcesReading([synthesizing])],[false,true,true],'read mail awaiting Attention synthesis is still being read');
assert.equal(sourcesReading([appletActivitySnapshot('gmail',true,'connected',[],{lastStatus:'complete'},undefined)]),false);
const {appletStatus,appletIndicator}=await import('../core/applets/status.ts');
const wakes=Date.parse('2026-09-27T12:00:00Z'),snoozedLink=(now:number)=>[{provider:'gmail',...appletActivitySnapshot('gmail',true,'connected',[{provider:'gmail',status:'open',kind:'task',snoozedUntil:'2026-09-27T12:00:00Z'}],undefined,undefined,now)}];
assert.deepEqual([appletStatus({provider:'gmail'},snoozedLink(wakes-1)).phase,appletStatus({provider:'gmail'},snoozedLink(wakes-1)).label],['connected','Connected · No saved items need attention'],'a snoozed item is quiet until its time');
assert.deepEqual([appletStatus({provider:'gmail'},snoozedLink(wakes)).label,appletIndicator({provider:'gmail'},snoozedLink(wakes)).label],['Needs attention · 1 saved item needs attention','Needs attention']);
console.log('PASS Applet concurrent reads, turn isolation, cancellation and persisted attention/error projection');

import {updateOnboarding} from '../core/onboarding/onboarding.ts';
import {APP_DEFINITIONS} from '../core/applets/catalog.ts';
const initialSetup={version:1,presets:['home'],completed:false};
const placed=updateOnboarding(initialSetup,{operation:'region',region:'work',sourceIds:['s','s'],connectionIds:['c']});
assert.deepEqual(initialSetup,{version:1,presets:['home'],completed:false});
assert.deepEqual(placed.regionSources.work,['s']);
assert.equal(updateOnboarding(placed,{operation:'region',region:'library',connectionIds:['c']}).connectionRegions.c,'work');
assert.throws(()=>updateOnboarding(initialSetup,{operation:'presets',presets:['work']}));
assert.deepEqual(updateOnboarding(placed,{operation:'presets',presets:['work','home','work']}).presets,['home','work']);
assert.equal(updateOnboarding({...initialSetup,introStep:3},{operation:'intro',step:1}).introStep,3);
assert.throws(()=>updateOnboarding(initialSetup,{operation:'intro',step:1.5}));
assert.throws(()=>updateOnboarding(initialSetup,{operation:'note',title:'\u200b',text:'ok',preset:'home'}));
assert.throws(()=>updateOnboarding(initialSetup,{operation:'note',title:'Note',text:'😀'.repeat(6001),preset:'home'}));
assert.throws(()=>updateOnboarding(initialSetup,{operation:'note',title:'Note',text:'ok',preset:'work',moduleKey:'sleep'}));
assert.ok(updateOnboarding(initialSetup,{operation:'note',title:'👩‍👩‍👧‍👧'.repeat(160),text:'ok',preset:'work',moduleKey:'notes'}).establishedRegions.includes('work'));
const hidden=updateOnboarding(initialSetup,{operation:'removeApplet',applet:'app-mail'});
assert.deepEqual(updateOnboarding(hidden,{operation:'unlock',applet:'app-mail'}).hiddenApplets,[]);
assert.deepEqual(updateOnboarding(hidden,{operation:'unlock',applet:'app-mail'}).unlockedApplets,[...new Set([...APP_DEFINITIONS.filter(a=>a.installByDefault!==false).map(a=>a.id),'app-mail'])],'absent roster means default Applets and is materialized on unlock');
assert.ok(updateOnboarding(initialSetup,{operation:'unlock',applet:'app-chatgpt'}).unlockedApplets.includes('app-chatgpt'),'unlocking an optional Applet adds it to the default roster');
assert.deepEqual(updateOnboarding({...hidden,unlockedApplets:[]},{operation:'unlock',applet:'app-mail'}).unlockedApplets,['app-mail']);
assert.throws(()=>updateOnboarding(hidden,{operation:'moveApplet',applet:'app-mail'}));
assert.equal(updateOnboarding({...initialSetup,journeyItemId:'old'},{operation:'journey',stage:'finish'}).journeyItemId,undefined);
assert.equal(updateOnboarding(initialSetup,{operation:'complete'}).completed,true,'tour completion needs no model or source');
// Worlds set up before a game existed get it once; a removed game stays removed; new setups choose for themselves.
const games=APP_DEFINITIONS.filter(a=>a.game).map(a=>a.id);assert.equal(games.length,5);assert.ok(games.includes('app-random-game'));
const earlier={...initialSetup,completed:true,unlockedApplets:['app-gmail'],hiddenApplets:['app-snake']};
const offered=updateOnboarding(earlier,{operation:'offerGames'});
assert.deepEqual(offered.unlockedApplets,['app-gmail',...games.filter(id=>id!=='app-snake')]);assert.deepEqual(offered.offeredGames,games);
assert.deepEqual(updateOnboarding({...offered,unlockedApplets:['app-gmail']},{operation:'offerGames'}).unlockedApplets,['app-gmail'],'games are offered only once');
assert.equal(updateOnboarding(initialSetup,{operation:'offerGames'}).offeredGames,undefined,'an unfinished setup chooses its own Applets');
assert.deepEqual(updateOnboarding(initialSetup,{operation:'setup',applets:['app-gmail']}).offeredGames,games);
// Worlds offered the first five games swap Breakout for the Random game that now holds it.
const firstFive={...initialSetup,completed:true,gamesOffered:true,unlockedApplets:['app-gmail','app-game-2048','app-breakout']};
const moved=updateOnboarding(firstFive,{operation:'offerGames'});
assert.deepEqual(moved.unlockedApplets,['app-gmail','app-game-2048','app-random-game']);assert.equal(moved.gamesOffered,undefined);
assert.deepEqual(updateOnboarding({...firstFive,hiddenApplets:['app-breakout']},{operation:'offerGames'}).unlockedApplets,['app-gmail','app-game-2048'],'a removed Breakout keeps the Random game away too');
console.log('PASS onboarding progress, placement, immutable inputs, Unicode notes, optional Applet roster and the one-time Games offer');

import {recordBrowserVisit,searchBrowserHistory} from '../core/browser/browser-history.ts';
const visits=[{url:'https://example.com/A',title:'Notebook',text:'paper',visitedAt:100},{url:'https://example.com/b',title:'Paper',text:'notebook',visitedAt:200}];
assert.equal(recordBrowserVisit(visits,{...visits[0],visitedAt:250},[true,true]),null,'unchanged same-day snapshot is throttled');
assert.equal(recordBrowserVisit(visits,{...visits[0],url:'https://example.com/a',visitedAt:250},[true,true]).length,3,'URL paths are case sensitive');
assert.equal(recordBrowserVisit(visits,{...visits[0],visitedAt:500},[true,true]).length,2);
assert.equal(recordBrowserVisit(visits,{...visits[0],visitedAt:500},[false,false]).length,3);
assert.equal(searchBrowserHistory(visits,'notebook',0,null,null).items[0].url,visits[0].url,'title outranks newer body matches');
assert.equal(searchBrowserHistory(visits,'',0,100,200).total,1,'inclusive after, exclusive before');
assert.equal(searchBrowserHistory([...visits,{...visits[0],visitedAt:300}],'',0,null,null).total,2);
assert.equal(searchBrowserHistory(visits,'',1,null,null).items[0].visitedAt,100);
assert.equal(visits.length,2,'record does not mutate loaded history');
assert.equal(searchBrowserHistory([{...visits[0],text:'👩‍👩‍👧‍👧'.repeat(2201)}],'',0,null,null).items[0].text,'👩‍👩‍👧‍👧'.repeat(2200));
console.log('PASS browser-history ranking, URL identity, throttle, local-day input, date bounds, paging and Unicode snippets');

const legacySetup=updateOnboarding({completed:false,introStep:0} as any,{operation:'note',title:'Draft',text:'Original',preset:'development',moduleKey:'code'});
assert.deepEqual(legacySetup.presets,['home','development']);
assert.throws(()=>updateOnboarding(initialSetup,{operation:'intro',step:10}));
assert.throws(()=>updateOnboarding(initialSetup,{operation:'setup',applets:['app-not-a-real-applet']}));
const keptHidden=updateOnboarding({...initialSetup,hiddenApplets:['app-gmail','app-youtube']},{operation:'setup',applets:['app-gmail']});
assert.deepEqual(keptHidden.hiddenApplets,['app-youtube']);
console.log('PASS legacy Windows setup normalization, valid catalog selection and unselected hidden-state preservation.');

let yieldingActivity=receiveAppletActivity(undefined,{callId:'partial',phase:'reading'},'yield-turn')!;
yieldingActivity=receiveAppletActivity(yieldingActivity,{callId:'partial',phase:'yielded'},'yield-turn')!;
assert.equal(yieldingActivity.failed,false);assert.equal(yieldingActivity.succeeded,false);assert.equal(yieldingActivity.calls.length,0);

const {configureSourceCheck}=await import('../core/scheduling/index.ts');
const runningCheck={id:'gmail',provider:'gmail',enabled:true,intervalMinutes:60,lastStatus:'running',lastSuccessAt:12,nextAt:5000};
assert.deepEqual(configureSourceCheck(runningCheck,{provider:'gmail',enabled:false},['gmail'],200),{...runningCheck,enabled:false,lastStatus:'cancelled',nextAt:200});
assert.deepEqual(configureSourceCheck(undefined,{provider:'gmail',enabled:true},['gmail'],200),{id:'gmail',provider:'gmail',enabled:true,intervalMinutes:30,nextAt:200});
assert.equal(configureSourceCheck(runningCheck,{provider:'gmail',intervalMinutes:1440},['gmail'],200).intervalMinutes,1440);
assert.equal(configureSourceCheck(runningCheck,{provider:'gmail',intervalMinutes:15},['gmail'],200).intervalMinutes,15);
for(const intervalMinutes of [null,false,'30',14,1441,15.5,Infinity])assert.throws(()=>configureSourceCheck(runningCheck,{provider:'gmail',intervalMinutes},['gmail'],200));
for(const enabled of [null,0,'false'])assert.throws(()=>configureSourceCheck(runningCheck,{provider:'gmail',enabled},['gmail'],200));
assert.throws(()=>configureSourceCheck(runningCheck,{provider:'gmail'},[],200),'configuration never grants source access');
assert.throws(()=>configureSourceCheck(runningCheck,{provider:'notion'},['notion'],200),'cannot change stored identity');
assert.throws(()=>configureSourceCheck(runningCheck,{provider:'gmail'},['gmail'],NaN));
assert.equal(runningCheck.lastStatus,'running');assert.equal(runningCheck.nextAt,5000,'inputs remain immutable');
console.log('PASS shared check configuration: authorized identity, partial internal updates, bounded intervals and pause semantics');
