// The Theme contract is frozen per version. A change that would break a theme package written against the frozen
// version fails here, in PR CI, before it ships:
// 1. Types: the frozen declarations (ui/themes/frozen/contract-v<N>.d.ts) and the current contract must agree in both
//    directions. What a package hands the host (theme, manifest, presentation, mounts) must still be accepted, and what
//    the host hands a package (contexts, state, items, actions) must still carry every field the package may read.
// 2. Behaviour: a frozen package (scripts/fixtures/theme-contract-v<N>/) that uses every part of the contract must
//    still compile and validate.
// Additive, optional changes pass; update the snapshot with `node scripts/theme-contract-check.ts --freeze` in the same
// PR. Anything else needs a new contract version (BUILD_THEME_CONTRACT_VERSION) with its own snapshot and fixture.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import {BUILD_THEME_CONTRACT_VERSION} from '../ui/themes/build-theme-contract.ts';
import {validateBuildTheme} from './build-theme-source.ts';

const root=fileURLToPath(new URL('../',import.meta.url));
const contract=path.join(root,'ui/themes/build-theme-contract.ts');
const snapshot=path.join(root,`ui/themes/frozen/contract-v${BUILD_THEME_CONTRACT_VERSION}.d.ts`);
const fixture=path.join(root,`scripts/fixtures/theme-contract-v${BUILD_THEME_CONTRACT_VERSION}`);
const options:ts.CompilerOptions={target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,strict:true,skipLibCheck:true,allowImportingTsExtensions:true,types:[]};

/** The contract's public declarations, as a package sees them. */
function declarations():string{
 let out='';
 const host=ts.createCompilerHost({...options,declaration:true,emitDeclarationOnly:true});
 host.writeFile=(_name,text)=>{out=text;};
 const result=ts.createProgram([contract],{...options,declaration:true,emitDeclarationOnly:true},host).emit();
 assert.equal(result.emitSkipped,false,'the contract emits declarations');
 return '// Frozen Theme contract v'+BUILD_THEME_CONTRACT_VERSION+' (ui/themes/build-theme-contract.ts). Generated by `node scripts/theme-contract-check.ts --freeze`; never edit by hand.\n'+out;
}

const freeze=process.argv.includes('--freeze'),freezeTo=async()=>{await fs.writeFile(snapshot,declarations());console.log('Froze Theme contract v'+BUILD_THEME_CONTRACT_VERSION+' at '+path.relative(root,snapshot));};
// A new contract version starts its own snapshot; an existing one is refrozen only after the checks below pass.
const frozen=await fs.readFile(snapshot,'utf8').catch(async()=>{
 if(!freeze)throw Error(`Contract v${BUILD_THEME_CONTRACT_VERSION} has no frozen snapshot. Run node scripts/theme-contract-check.ts --freeze and add a frozen fixture package.`);
 await freezeTo();process.exit(0);
});

// What a package produces flows to the host: frozen → current. What the host provides flows to a package: current → frozen.
const fromPackage=['BuildTheme','BuildThemeManifest','ThemePresentation','ThemeScene','ThemeHud','ThemeSound','ThemeMount','ThemeWorldMount','ThemeWorldMark'];
const toPackage=['ThemeAppletContext','ThemeWorldContext','ThemeWorldState','ThemeWorldApplet','ThemeWorldEvent','ThemeItem','ThemeActions','ThemeScene','ThemePresentation','ThemeRecord'];
// A type added since the freeze has nothing frozen to compare with; the next --freeze adds it.
const shipped=(name:string)=>new RegExp(`export (interface|type) ${name}\\b`).test(frozen);
const probe=path.join(root,'ui/themes/__theme_contract_probe__.ts');
const source=`import type * as F from './frozen/contract-v${BUILD_THEME_CONTRACT_VERSION}.d.ts';\nimport type * as C from './build-theme-contract.ts';\n`+
 fromPackage.filter(shipped).map(name=>`export const from_${name}=(v:F.${name}):C.${name}=>v;\n`).join('')+
 toPackage.filter(shipped).map(name=>`export const to_${name}=(v:C.${name}):F.${name}=>v;\n`).join('');
const host=ts.createCompilerHost(options),read=host.readFile,exists=host.fileExists;
host.readFile=file=>file===probe?source:read(file);host.fileExists=file=>file===probe||exists(file);
const program=ts.createProgram([probe],{...options,noEmit:true},host);
// Only the probe's own assignments are judged; the contract's implementation is type-checked by `npm run check`.
const diagnostics=ts.getPreEmitDiagnostics(program,program.getSourceFile(probe));
assert.equal(diagnostics.length,0,'The Theme contract changed incompatibly with frozen v'+BUILD_THEME_CONTRACT_VERSION+':\n'+ts.formatDiagnostics(diagnostics,{getCurrentDirectory:()=>root,getCanonicalFileName:f=>f,getNewLine:()=>'\n'}));

// Removing an optional field still type-checks, but breaks a package that sets or reads it: every frozen member must remain.
const checker=program.getTypeChecker();
const exportsOf=(file:string)=>{const sf=program.getSourceFile(file)!,symbol=checker.getSymbolAtLocation(sf)!;return new Map(checker.getExportsOfModule(symbol).map(s=>[s.name,s]));};
const frozenExports=exportsOf(snapshot),currentExports=exportsOf(contract);
for(const [name,symbol] of frozenExports){
 const current=currentExports.get(name);
 assert(current,`Contract v${BUILD_THEME_CONTRACT_VERSION} no longer exports ${name}`);
 if(!(symbol.flags&(ts.SymbolFlags.Interface|ts.SymbolFlags.TypeAlias)))continue;
 const walk=(f:ts.Type,c:ts.Type,where:string,depth:number)=>{
  if(depth>4)return;
  if(checker.isArrayType(f)||checker.isTupleType(f))return;
  for(const member of checker.getPropertiesOfType(f)){
   // Only the contract's own fields; built-in members of arrays, functions and strings are not the contract's to freeze.
   if(!member.declarations?.some(d=>d.getSourceFile().fileName===snapshot))continue;
   const other=checker.getPropertyOfType(c,member.name);
   assert(other,`${where}.${member.name} was removed from the Theme contract`);
   const decl=member.valueDeclaration||member.declarations?.[0],otherDecl=other.valueDeclaration||other.declarations?.[0];
   if(decl&&otherDecl)walk(checker.getNonNullableType(checker.getTypeOfSymbolAtLocation(member,decl)),checker.getNonNullableType(checker.getTypeOfSymbolAtLocation(other,otherDecl)),where+'.'+member.name,depth+1);
  }
 };
 walk(checker.getDeclaredTypeOfSymbol(symbol),checker.getDeclaredTypeOfSymbol(current),name,0);
}

// The frozen package still compiles against the current contract and passes import validation.
const checked=await validateBuildTheme(fixture);
assert.equal(checked.manifest.contractVersion,BUILD_THEME_CONTRACT_VERSION);

if(freeze){await freezeTo();process.exit(0);}
// A compatible change still keeps the snapshot current, so the next change is compared with what shipped.
assert.equal(frozen,declarations(),'The Theme contract changed compatibly. Run node scripts/theme-contract-check.ts --freeze and commit the snapshot.');
console.log(`PASS Theme contract v${BUILD_THEME_CONTRACT_VERSION}: frozen types accepted both ways, no frozen field removed, the frozen package compiles and validates, snapshot current`);
