# Writes core/artifacts/ready/getty-center-art.ts: the pictures the Getty Center guide carries inside its page, as
# data URIs (a made Applet's page can load nothing else). The miniature is render.png from render.mjs, cropped to
# what it drew; Fox and the stop pictures are reduced copies of registered assets. Needs Pillow.
import base64,io,json,os
from PIL import Image
here=os.path.dirname(os.path.abspath(__file__));root=os.path.normpath(os.path.join(here,'../../../../..'))
assets=os.path.join(root,'resources/styles/builtin/assets')
def uri(im,q):
    b=io.BytesIO();im.save(b,'WEBP',quality=q,method=6);return 'data:image/webp;base64,'+base64.b64encode(b.getvalue()).decode()
render=Image.open(os.path.join(here,'render.png')).convert('RGBA');box=render.getbbox();W,H=render.size
miniature=render.crop(box);cw,ch=miniature.size
pins={k:[round((x/100*W-box[0])/cw*100,1),round((y/100*H-box[1])/ch*100,1)] for k,(x,y) in json.load(open(os.path.join(here,'pins.json'))).items() if k!='hall'}
art={'hero':uri(miniature.resize((640,round(ch*640/cw)),Image.LANCZOS),68)}
# Fox waving: row 4, column 4 of the expression atlas (assets/companion/expressions/README.md).
atlas=Image.open(os.path.join(assets,'companion/expressions/atlas.png')).convert('RGBA')
fox=atlas.crop((951,949,1254,1254));fox=fox.crop(fox.getbbox());fox.thumbnail((112,112),Image.LANCZOS);art['fox']=uri(fox,72)
for key,scene in [('tram','public-transit'),('museum','museum'),('garden','gardening'),('cafe','coffee-meetup'),('exhibit','exhibition')]:
    art[key]=uri(Image.open(os.path.join(assets,'attention/scenes',scene+'.webp')).convert('RGB').resize((180,120),Image.LANCZOS),52)
out=['// Generated by resources/styles/builtin/drafts/getty-guide/compose.py; do not edit by hand.',
 '/** Where each place is on the miniature, in percent of its width and height. */',
 'export const GETTY_PINS:Record<string,[number,number]>='+json.dumps(pins,separators=(',',':'))+';',
 '/** The pictures the page carries, as data URIs. */',
 'export const GETTY_ART={']+[f" {k}:'{v}'," for k,v in art.items()]+['};','']
open(os.path.join(root,'core/artifacts/ready/getty-center-art.ts'),'w').write('\n'.join(out))
print(sum(len(v) for v in art.values()),'bytes of pictures')
