// Frozen Theme contract v3 (ui/themes/build-theme-contract.ts). Generated by `node scripts/theme-contract-check.ts --freeze`; never edit by hand.
/** The one Theme contract (v3). A theme is static: pictures, sounds and JSON, no code and no stylesheet. The host
 * draws the World and every Applet page itself and reads from the theme only what is declared here.
 * Worldlet bundles one theme, the Village (ui/theme-packages/village). */
export declare const BUILD_THEME_CONTRACT_VERSION = 3;
/** Business events a theme may give a sound. Adding one is a product decision, not a theme's. */
export declare const THEME_SOUND_EVENTS: readonly ["applet.arrived", "mail.received", "task.working", "task.succeeded", "task.failed", "task.cancelled"];
export type ThemeSoundEvent = typeof THEME_SOUND_EVENTS[number];
/** The shared HUD pieces a theme may paint, each a nine-slice image laid over the shared element (ui/themes/theme-surfaces.css).
 * The companion (Fox, its bubble, panel and nameplate) and the loading and first-use pages are not a theme's to replace. */
export declare const THEME_HUD_PARTS: readonly ["attention", "note", "back", "log", "button", "card", "frame"];
export type ThemeHudPart = typeof THEME_HUD_PARTS[number];
/** The shared HUD's material. A piece left out keeps the shared look. */
export interface ThemeHud {
    /** Nine-slice images: slice insets (top, right, bottom, left) in image pixels, drawn at `width` CSS pixels. */
    skin: Partial<Record<ThemeHudPart, {
        image: string;
        slice: readonly [number, number, number, number];
        width: number;
    }>>;
}
export interface ThemeSound {
    events: Partial<Record<ThemeSoundEvent, string>>;
}
/** The colour roles an Artifact uses: paper, ink and brass, and one accent per tone (what a card is about). */
export declare const THEME_ARTIFACT_COLORS: readonly ["paper", "ink", "brass", "moss", "teal", "honey", "sage", "clay", "plum"];
export type ThemeArtifactColor = typeof THEME_ARTIFACT_COLORS[number];
/** How the theme's Artifacts look (core/artifacts/README.md#theme-driven-artifacts), as static files: the host's
 * generator reads the rules and prompt, sees the reference pictures and may place the materials in a page it writes;
 * the host's own card fills its template with the same colours. Nothing here runs. */
export interface ThemeArtifact {
    /** Design rules for a generated Artifact (Markdown). */
    style: string;
    /** The prompt the generator receives with the content, the room and the capabilities (Markdown). */
    prompt: string;
    /** Pictures of finished Artifacts, the visual standard; the first is the primary one. */
    references: readonly {
        image: string;
        role: string;
    }[];
    /** Pictures a generated Artifact may place, by id. */
    materials?: readonly {
        id: string;
        image: string;
        usage: string;
    }[];
    /** `#rrggbb` per colour role; a role left out keeps the host's. */
    colors?: Partial<Record<ThemeArtifactColor, string>>;
}
/** The theme's type and colours. */
export interface ThemeTokens {
    bodyFont: string;
    displayFont: string;
    bodySize: number;
    titleSize: number;
    ink: string;
    paper: string;
    accent: string;
    focus: string;
    radius: number;
    controlHeight: number;
}
export interface ThemePresentation {
    tokens: ThemeTokens;
    fonts: readonly {
        file: string;
        license: string;
    }[];
    hud?: ThemeHud;
    sound?: ThemeSound;
    /** The theme's own picture of each Applet, by Applet key. The host shows it wherever it pictures that Applet (the World, lists, history, onboarding); an Applet left out keeps the host's picture. */
    icons?: Readonly<Record<string, string>>;
    /** How the theme's Artifacts look. Left out, Artifacts keep the host's card. */
    artifact?: ThemeArtifact;
}
/** theme.json. Every other file in the package is a picture, a sound, a font, a licence text or JSON. */
export interface BuildThemeManifest {
    contractVersion: 3;
    id: string;
    updatedAt?: string;
    title: string;
    assets: 'assets';
    presentation: 'presentation.json';
}
export declare function themeAssetPath(v: unknown): string;
export declare function parseBuildThemeManifest(value: unknown): BuildThemeManifest;
export declare function parseThemePresentation(value: unknown): ThemePresentation;
