// Frozen Theme contract v2 (ui/themes/build-theme-contract.ts). Generated by `node scripts/theme-contract-check.ts --freeze`; never edit by hand.
/** The one Theme contract (Sim contract v2). Every theme package and the host compile against this file.
 * Worldlet bundles any number of packages; the person switches between them in one step (build-theme.ts). */
export declare const BUILD_THEME_CONTRACT_VERSION = 2;
export type ThemeRect = readonly [number, number, number, number];
export type ThemeRecord = Readonly<Record<string, unknown>>;
export interface ThemeItem {
    id: string;
    title: string;
    summary?: string;
    context?: string;
    start?: string;
    end?: string;
    local?: boolean;
    curated?: boolean;
    record?: ThemeRecord;
}
export interface ThemeActions {
    openItem(id: string): void;
    /** Present only when the host actually supports writes for this applet. */
    records?: {
        save(record: ThemeRecord): Promise<void> | void;
        remove(id: string): Promise<void> | void;
    };
}
export interface ThemeScene {
    /** Shared art/HTML coordinate system; contain, never independently stretch the artwork. */
    size: readonly [number, number];
    background: string;
    slots: Record<string, ThemeRect>;
    hud: {
        top: ThemeRect;
        companion: ThemeRect;
        speech: ThemeRect;
        attention: ThemeRect | 'shared';
        today: ThemeRect | 'shared';
        dialog: ThemeRect | 'shared';
    };
}
/** Business events a theme may give a sound. Adding one is a product decision, not a theme's. */
export declare const THEME_SOUND_EVENTS: readonly ["applet.arrived", "mail.received", "task.working", "task.succeeded", "task.failed", "task.cancelled"];
export type ThemeSoundEvent = typeof THEME_SOUND_EVENTS[number];
/** The shared HUD pieces a theme may paint, each a nine-slice image laid over the shared element (ui/themes/theme-surfaces.css).
 * The companion (Fox, its bubble, panel and nameplate) and the loading and first-use pages are not a theme's to replace. */
export declare const THEME_HUD_PARTS: readonly ["attention", "note", "back", "log", "button", "card", "frame"];
export type ThemeHudPart = typeof THEME_HUD_PARTS[number];
/** The shared HUD's material. A piece left out keeps the shared look. */
export interface ThemeHud {
    /** Nine-slice images: slice insets (top, right, bottom, left) in image pixels, drawn at `width` CSS pixels. */
    skin: Partial<Record<ThemeHudPart, {
        image: string;
        slice: readonly [number, number, number, number];
        width: number;
    }>>;
}
export interface ThemeSound {
    events: Partial<Record<ThemeSoundEvent, string>>;
}
export interface ThemePresentation {
    tokens: {
        bodyFont: string;
        displayFont: string;
        bodySize: number;
        titleSize: number;
        ink: string;
        paper: string;
        accent: string;
        focus: string;
        radius: number;
        controlHeight: number;
    };
    fonts: readonly {
        file: string;
        license: string;
    }[];
    world: ThemeScene;
    applets: Record<string, ThemeScene>;
    fallback: ThemeScene;
    hud?: ThemeHud;
    sound?: ThemeSound;
}
export interface ThemeAppletContext {
    host: HTMLElement;
    applet: {
        id: string;
        title: string;
    };
    scene: ThemeScene;
    items: readonly Readonly<ThemeItem>[];
    data: {
        now?: number;
        sample?: boolean;
        connected?: boolean;
        reading?: boolean;
        error?: string;
    };
    actions: ThemeActions;
    invalidate(): void;
    /** Optional richer host reader; presentation owns its placement. */
    renderDefault(target: HTMLElement): void;
    /** Published URL of a package-relative `assets/...` path. Packages never hard-code where the host serves them. */
    asset(path: string): string;
}
export interface ThemeMount {
    dispose(): void;
}
export interface ThemeWorldApplet {
    id: string;
    key: string;
    title: string;
    region: string;
    visible: boolean;
    status?: string;
    count?: number;
    /** The host's own picture of this Applet (its shared device art, or the icon a person's own Applet carries). Themes without their own art for an Applet show this rather than a placeholder. */
    icon?: string;
}
export interface ThemeWorldState {
    view: {
        id: string;
        level: 'overview' | 'area' | 'applet';
    };
    applets: readonly ThemeWorldApplet[];
    areas: readonly {
        id: string;
        title: string;
    }[];
    interaction: {
        placementArea: string | null;
        framedArea: string | null;
        inset: number;
        hoveredApplet: string | null;
        hoveredArea: string | null;
    };
    pins: Readonly<Record<string, readonly (string | null)[]>>;
    environment: ThemeRecord;
    motion: boolean;
}
export interface ThemeWorldContext {
    host: HTMLElement;
    scene: ThemeScene;
    state: ThemeWorldState;
    navigate(target: {
        kind: 'applet' | 'area';
        id: string;
    }): void;
    menu(id: string, x: number, y: number): void;
    moveApplet(id: string, area: string, slot?: number): void;
    /** Published URL of a package-relative `assets/...` path. */
    asset(path: string): string;
}
export interface ThemeWorldMount extends ThemeMount {
    update(state: ThemeWorldState): void;
    event(event: {
        type: 'mail.received' | 'applet.arrived';
        ids: readonly string[];
    }): boolean;
    /** CSS pixels relative to host. Used by the companion and host accessibility surfaces. */
    anchor(id: string): {
        x: number;
        y: number;
    } | null;
    bounds(id: string): {
        x: number;
        y: number;
        width: number;
        height: number;
    } | null;
}
export interface BuildTheme {
    contractVersion: 2;
    id: string;
    renderWorld(context: ThemeWorldContext): ThemeWorldMount;
    /** Must handle every applet, including IDs added after the theme was authored. */
    renderApplet(context: ThemeAppletContext): ThemeMount;
}
export interface BuildThemeManifest {
    contractVersion: 2;
    id: string;
    updatedAt?: string;
    title: string;
    entry: 'entry.ts';
    stylesheet: 'theme.css';
    assets: 'assets';
    presentation: 'presentation.json';
    applets: string[];
}
export declare function themeAssetPath(v: unknown): string;
export declare function parseBuildThemeManifest(value: unknown): BuildThemeManifest;
export declare function parseThemePresentation(value: unknown): ThemePresentation;
