// Frozen Theme contract v2 (ui/themes/build-theme-contract.ts). Generated by `node scripts/theme-contract-check.ts --freeze`; never edit by hand.
/** The one Theme contract (Sim contract v2). Every theme package and the host compile against this file.
 * Worldlet bundles any number of packages; the person switches between them in one step (build-theme.ts). */
export declare const BUILD_THEME_CONTRACT_VERSION = 2;
export type ThemeRect = readonly [number, number, number, number];
export type ThemeRecord = Readonly<Record<string, unknown>>;
export interface ThemeItem {
    id: string;
    title: string;
    summary?: string;
    context?: string;
    start?: string;
    end?: string;
    local?: boolean;
    curated?: boolean;
    record?: ThemeRecord;
}
export interface ThemeActions {
    openItem(id: string): void;
    /** Present only when the host can read more items for this Applet. */
    loadMore?(): void;
    /** Present only when the host actually supports writes for this applet. */
    records?: {
        save(record: ThemeRecord): Promise<void> | void;
        remove(id: string): Promise<void> | void;
    };
}
export interface ThemeScene {
    /** Shared art/HTML coordinate system; contain, never independently stretch the artwork. */
    size: readonly [number, number];
    background: string;
    slots: Record<string, ThemeRect>;
    hud: {
        top: ThemeRect;
        companion: ThemeRect;
        speech: ThemeRect;
        attention: ThemeRect | 'shared';
        today: ThemeRect | 'shared';
        dialog: ThemeRect | 'shared';
    };
}
/** Business events a theme may give a sound. Adding one is a product decision, not a theme's. */
export declare const THEME_SOUND_EVENTS: readonly ["applet.arrived", "mail.received", "task.working", "task.succeeded", "task.failed", "task.cancelled"];
export type ThemeSoundEvent = typeof THEME_SOUND_EVENTS[number];
/** The shared HUD pieces a theme may paint, each a nine-slice image laid over the shared element (ui/themes/theme-surfaces.css).
 * The companion (Fox, its bubble, panel and nameplate) and the loading and first-use pages are not a theme's to replace. */
export declare const THEME_HUD_PARTS: readonly ["attention", "note", "back", "log", "button", "card", "frame"];
export type ThemeHudPart = typeof THEME_HUD_PARTS[number];
/** The shared HUD's material. A piece left out keeps the shared look. */
export interface ThemeHud {
    /** Nine-slice images: slice insets (top, right, bottom, left) in image pixels, drawn at `width` CSS pixels. */
    skin: Partial<Record<ThemeHudPart, {
        image: string;
        slice: readonly [number, number, number, number];
        width: number;
    }>>;
}
export interface ThemeSound {
    events: Partial<Record<ThemeSoundEvent, string>>;
}
export interface ThemePresentation {
    tokens: {
        bodyFont: string;
        displayFont: string;
        bodySize: number;
        titleSize: number;
        ink: string;
        paper: string;
        accent: string;
        focus: string;
        radius: number;
        controlHeight: number;
    };
    fonts: readonly {
        file: string;
        license: string;
    }[];
    world: ThemeScene;
    applets: Record<string, ThemeScene>;
    fallback: ThemeScene;
    hud?: ThemeHud;
    sound?: ThemeSound;
    /** The theme's own picture of each Applet, by Applet key. The host shows it wherever it pictures that Applet (the World, lists, history, onboarding); an Applet left out keeps the host's picture. */
    icons?: Readonly<Record<string, string>>;
}
export interface ThemeAppletContext {
    host: HTMLElement;
    applet: {
        id: string;
        title: string;
    };
    scene: ThemeScene;
    items: readonly Readonly<ThemeItem>[];
    data: {
        now?: number;
        sample?: boolean;
        connected?: boolean;
        reading?: boolean;
        error?: string;
        /** What the items cover when it is not everything (for example "Last 30 days"). */
        scope?: string;
    };
    actions: ThemeActions;
    invalidate(): void;
    /** Optional richer host reader; presentation owns its placement. */
    renderDefault(target: HTMLElement): void;
    /** Published URL of a package-relative `assets/...` path. Packages never hard-code where the host serves them. */
    asset(path: string): string;
}
export interface ThemeMount {
    dispose(): void;
}
export interface ThemeWorldApplet {
    id: string;
    key: string;
    title: string;
    region: string;
    visible: boolean;
    status?: string;
    count?: number;
    /** This Applet's picture: the icon a person's own Applet carries, else this theme's `icons` entry, else the host's device art. Show it rather than a placeholder. */
    icon?: string;
    /** The Applet's lamp as the host shows it. A theme with lamps in its art lights them; the host draws the lamp's label and action. */
    lamp?: ThemeLampState;
    connected?: boolean;
    /** Set for the person's own Applets (core/applets/MY-APPLETS.md): which kind it is. */
    mine?: string;
    /** A thing that is not an Applet (a trip, a parcel). It is shown only while it is open. */
    object?: boolean;
    /** The catalog Applet whose picture this one shares, when it is not its own `key`. */
    art?: string;
    /** When the person last used it or it arrived (ms since 1970). Themes that place Applets put recent ones first. */
    usedAt?: number;
    /** While it is open, the host's Applet stage draws this Applet's own picture in front. A theme can stop drawing its device behind it. */
    staged?: boolean;
    /** Coding Applets: the weekly allowance left. `remaining` is a percentage; neither is set while it is unknown. */
    allowance?: {
        remaining?: number;
        resetsAt?: number;
        unavailable?: boolean;
    };
}
export type ThemeLampState = 'off' | 'ready' | 'processing' | 'error';
export interface ThemeWorldState {
    view: {
        id: string;
        level: 'overview' | 'area' | 'applet';
    };
    applets: readonly ThemeWorldApplet[];
    areas: readonly {
        id: string;
        title: string;
        /** The look the person chose for the area, when the theme offers several. */
        look?: string;
    }[];
    interaction: {
        placementArea: string | null;
        framedArea: string | null;
        inset: number;
        hoveredApplet: string | null;
        hoveredArea: string | null;
        /** First use: areas and Applets can't be opened or moved yet. */
        locked?: boolean;
        /** Something sits over the World (the tour, a dialog, an attention preview): no hover, no lamp actions. */
        covered?: boolean;
        /** The open Applet shows an item's detail beside it. */
        detailOpen?: boolean;
        /** The open Applet shows its website instead of its own contents. */
        website?: boolean;
    };
    pins: Readonly<Record<string, readonly (string | null)[]>>;
    environment: ThemeRecord;
    motion: boolean;
    /** Nobody can see the World right now (Fox floats on the desktop, or the window is hidden). Stop drawing. */
    paused?: boolean;
    /** Applets that arrive next, before `applet.arrived` shows them: a theme that places Applets puts them where they will land. */
    arriving?: readonly string[];
}
/** A place the World marks for the host's shared overlays: the accessible button, the name, the lamp label and the
 * attention mark the host draws there. CSS pixels relative to the World's host element. */
export interface ThemeWorldMark {
    kind: 'applet' | 'area' | 'area-add' | 'slot';
    id: string;
    x: number;
    y: number;
    visible: boolean;
    /** Slot marks: the place's index in its area, as moveApplet takes it. */
    slot?: number;
    /** Applet marks: show the name beside the Applet. */
    label?: boolean;
    hovered?: boolean;
    /** Applet marks: where the lamp sits and where the attention mark hangs, relative to x and y. */
    lamp?: {
        x: number;
        y: number;
    };
    attention?: {
        x: number;
        y: number;
    };
}
export interface ThemeWorldContext {
    host: HTMLElement;
    scene: ThemeScene;
    state: ThemeWorldState;
    navigate(target: {
        kind: 'applet' | 'area';
        id: string;
    }): void;
    menu(id: string, x: number, y: number): void;
    moveApplet(id: string, area: string, slot?: number): void;
    /** Published URL of a package-relative `assets/...` path. */
    asset(path: string): string;
    /** Report where the host draws its shared overlays. A theme that calls it draws no buttons, names or lamp labels of its own. */
    marks?(marks: Readonly<Record<string, ThemeWorldMark>>): void;
    /** Leave the open area or Applet, as the host's Back does. */
    back?(): void;
    /** Open an area's own panel (its Applets and places), as its area mark does. */
    openArea?(id: string): void;
}
export interface ThemeWorldEvent {
    type: 'mail.received' | 'applet.arrived';
    ids: readonly string[];
    /** Arrivals: they fly in from the middle of the window, each starting as its icon. */
    from?: 'center';
    icons?: Readonly<Record<string, string>>;
    /** Arrivals: they are already in place; only settle them (their shadows), don't fly them in. */
    settled?: boolean;
}
export interface ThemeWorldMount extends ThemeMount {
    update(state: ThemeWorldState): void;
    /** Whether the theme played it. An arrival may return a promise that settles when the Applets have landed. */
    event(event: ThemeWorldEvent): boolean | Promise<boolean>;
    /** CSS pixels relative to host. Used by the companion and host accessibility surfaces. */
    anchor(id: string): {
        x: number;
        y: number;
    } | null;
    bounds(id: string): {
        x: number;
        y: number;
        width: number;
        height: number;
    } | null;
    /** The World stays drawn behind an open Applet (blurred, its device in front). Otherwise the host hides it. */
    behindApplet?: boolean;
    /** What is on screen now, for the zoom between the World and an Applet. */
    picture?(): HTMLCanvasElement | null;
    /** Renderer facts for the product's own checks. */
    metrics?(): ThemeRecord;
}
export interface BuildTheme {
    contractVersion: 2;
    id: string;
    renderWorld(context: ThemeWorldContext): ThemeWorldMount;
    /** Must handle every applet, including IDs added after the theme was authored. */
    renderApplet(context: ThemeAppletContext): ThemeMount;
}
export interface BuildThemeManifest {
    contractVersion: 2;
    id: string;
    updatedAt?: string;
    title: string;
    entry: 'entry.ts';
    stylesheet: 'theme.css';
    assets: 'assets';
    presentation: 'presentation.json';
    applets: string[];
}
export declare function themeAssetPath(v: unknown): string;
export declare function parseBuildThemeManifest(value: unknown): BuildThemeManifest;
export declare function parseThemePresentation(value: unknown): ThemePresentation;
