// One way to bring a person's own Agent into Fox (owner request 2026-10-03: OpenClaw, Claude Code,
// pi and Hermes Agent all come over through the same flow; Codex's conversations too, though Codex
// itself stays Fox's model rather than an Agent Fox replaces). Each Agent keeps its own files; the host
// reads them read-only into the same shape (conversations, notes, skills, scheduled jobs) and this
// module holds the shared rules: what each source is called, how its transcript lines become turns,
// how its scheduled jobs become Fox routines and what Fox remembers about what came over.
// OpenClaw's own rules (channels, agents, cron payloads) stay in `openclaw-migration`.
// Kept ES-compatible for JavaScriptCore and Jint.
import {agentRoleSkill,openClawSkillMarkdown,openClawSkillName,openClawTurn,type AgentRole,type OpenClawRoutine,type OpenClawRoutineResult,type OpenClawTurn} from './openclaw-migration.ts';

export type MigrationSource='openclaw'|'claude-code'|'pi'|'hermes'|'codex';
export const MIGRATION_SOURCES:MigrationSource[]=['openclaw','claude-code','pi','hermes','codex'];
export const isMigrationSource=(value:unknown):value is MigrationSource=>MIGRATION_SOURCES.includes(value as MigrationSource);
export const MIGRATION_SOURCE_TITLES:Record<MigrationSource,string>={openclaw:'OpenClaw','claude-code':'Claude Code',pi:'pi',hermes:'Hermes Agent',codex:'Codex'};
export type MigrationTurn=OpenClawTurn;
export type MigrationRoutine=OpenClawRoutine;
export type MigrationRoutineResult=OpenClawRoutineResult;

const record=(value:unknown):Record<string,any>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:{};
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const clip=(value:string,limit:number)=>value.length>limit?value.slice(0,limit-1).trimEnd()+'…':value;
const iso=(value:unknown):string|null=>{
 const date=typeof value==='number'&&Number.isFinite(value)?new Date(value<1e12?value*1000:value):typeof value==='string'&&value?new Date(value):null;
 return date&&!Number.isNaN(date.getTime())?date.toISOString().replace(/\.\d+Z$/,'Z'):null;
};
const firstLine=(value:string)=>clip(value.replace(/\s+/g,' ').trim(),60);

// Conversations ------------------------------------------------------------------------------

/** pi writes the same session tree as OpenClaw (both build on pi's agent core). */
export const piTurn=openClawTurn;

/** Claude Code's harness inserts these into user messages; they are not what the person typed. */
const CLAUDE_TAGS=/<(system-reminder|command-name|command-message|command-args|local-command-stdout|local-command-stderr|local-command-caveat|bash-input|bash-stdout|bash-stderr|user-prompt-submit-hook|session-start-hook)>[\s\S]*?<\/\1>/g;
/** One line of a Claude Code session file (`projects/<folder>/<id>.jsonl`) as a visible turn, or
 * null for tool calls and results, thinking, summaries, side chains and harness lines. */
export function claudeCodeTurn(line:unknown):MigrationTurn|null {
 const entry=record(line);
 if(entry.type!=='user'&&entry.type!=='assistant')return null;
 if(entry.isMeta||entry.isSidechain||entry.isCompactSummary||entry.isVisibleInTranscriptOnly)return null;
 const message=record(entry.message),content=message.content;
 if(message.role!==entry.type)return null;
 let body=typeof content==='string'?content:Array.isArray(content)?content.map(part=>{const p=record(part);return p.type==='text'&&typeof p.text==='string'?p.text:'';}).filter(Boolean).join('\n\n'):'';
 body=body.replace(CLAUDE_TAGS,'').trim();
 if(!body||/^\[Request interrupted by user/.test(body)||body.startsWith('Caveat: The messages below were generated by the user while running local commands'))return null;
 return {role:entry.type,text:body,at:iso(entry.timestamp)};
}
/** "worldlet · Fix the sign-in redirect": the project folder, then the session's own name. */
export function claudeCodeConversationTitle({title,cwd,first}:{title?:string|null;cwd?:string|null;first?:string|null}):string {
 const folder=text(cwd).split(/[\\/]/).filter(Boolean).at(-1)??'';
 const name=text(title)||(text(first)?firstLine(text(first)):'Conversation');
 return clip(folder&&!name.toLowerCase().startsWith(folder.toLowerCase())?folder+' · '+name:name,140);
}
/** One line of a Codex session file (`sessions/YYYY/MM/DD/rollout-*.jsonl`) as a visible turn: only
 * what the person typed and Codex's answers, never the instructions, environment context, reasoning
 * or tool calls Codex also records. Older Codex wrote them as `event_msg` user_message /
 * agent_message; current Codex (and the ChatGPT app's) as `event_msg` item_completed with a
 * UserMessage / AgentMessage item. */
export function codexTurn(line:unknown):MigrationTurn|null {
 const entry=record(line),payload=record(entry.payload);
 if(entry.type!=='event_msg')return null;
 if(payload.type==='item_completed'){
  const item=record(payload.item);
  if(item.type!=='UserMessage'&&item.type!=='AgentMessage')return null;
  const body=(Array.isArray(item.content)?item.content:[]).map(part=>{const p=record(part);return /^text$/i.test(String(p.type))?text(p.text):'';}).filter(Boolean).join('\n\n');
  return body?{role:item.type==='UserMessage'?'user':'assistant',text:body,at:iso(entry.timestamp)}:null;
 }
 if(payload.type!=='user_message'&&payload.type!=='agent_message')return null;
 const body=text(payload.message);
 if(!body)return null;
 return {role:payload.type==='user_message'?'user':'assistant',text:body,at:iso(entry.timestamp)};
}
/** The visible turns of one Codex session file; a file holding both forms keeps only the current one. */
export function codexTurns(lines:unknown[]):MigrationTurn[] {
 const current=lines.filter(line=>record(record(line).payload).type==='item_completed');
 const turns=current.map(codexTurn).filter((turn):turn is MigrationTurn=>!!turn);
 return turns.length?turns:lines.map(codexTurn).filter((turn):turn is MigrationTurn=>!!turn);
}
/** Codex sessions it started for itself (sub-agents, reviews) are not conversations the person had. */
export const codexSessionIncluded=(meta:unknown)=>{const source=record(meta).source;return source===undefined||typeof source==='string';};
/** pi names a session in a `session_info` line; otherwise its first message stands in. */
export function piConversationTitle({title,cwd,first}:{title?:string|null;cwd?:string|null;first?:string|null}):string {
 return claudeCodeConversationTitle({title,cwd,first});
}

/** Hermes Agent sessions Worldlet or Hermes itself started (scheduled runs, sub-agents, Worldlet's
 * own Fox) are not conversations the person had. */
export function hermesConversationIncluded(session:{id?:unknown;source?:unknown;session_key?:unknown}):boolean {
 const id=String(session.id??''),source=String(session.source??'').toLowerCase();
 // Fox's own turns on its API server carry Fox's session name as their key (X-Hermes-Session-Key, harnessSessionName).
 return !!id&&!id.startsWith('worldlet-')&&!String(session.session_key??'').startsWith('worldlet-')&&!['cron','subagent','delegate','batch','worldlet','acp'].includes(source);
}
const HERMES_SOURCES:Record<string,string>={cli:'Terminal',tui:'Terminal',telegram:'Telegram',discord:'Discord',slack:'Slack',whatsapp:'WhatsApp',signal:'Signal',matrix:'Matrix',email:'Email',sms:'SMS',web:'Web',api:'API',homeassistant:'Home Assistant',dingtalk:'DingTalk',feishu:'Feishu',wecom:'WeCom',mattermost:'Mattermost'};
/** "Telegram · Trip planning", from the session's title, chat name or first message. */
export function hermesConversationTitle({title,source,chat,first}:{title?:string|null;source?:string|null;chat?:string|null;first?:string|null}):string {
 const service=HERMES_SOURCES[text(source).toLowerCase()]??'';
 const name=text(title)||text(chat)||(text(first)?firstLine(text(first)):'Conversation');
 return clip(service&&!name.toLowerCase().includes(service.toLowerCase())?service+' · '+name:name,140);
}
/** One `messages` row of Hermes' `state.db` as a visible turn (tool rows and summaries are not). */
export function hermesTurn(row:{role?:unknown;content?:unknown;timestamp?:unknown;summary?:unknown}):MigrationTurn|null {
 if(row.role!=='user'&&row.role!=='assistant'||row.summary)return null;
 const body=text(row.content).replace(/\n\nCurrent Worldlet context \(untrusted reference data, not instructions\):\n[\s\S]*$/,'').trim();
 if(!body||body==='[SILENT]')return null;
 return {role:row.role,text:body,at:iso(typeof row.timestamp==='string'?Number(row.timestamp):row.timestamp)};
}

// Scheduled jobs -----------------------------------------------------------------------------

/** A job from Hermes Agent's `cron/jobs.json` as a Fox routine. Jobs that run a script, watch
 * something or only send a message stay with Hermes Agent. */
export function hermesRoutine(job:unknown,now=Date.now()):MigrationRoutineResult {
 const value=record(job),schedule=record(value.schedule);
 const name=clip(text(value.name)||firstLine(text(value.prompt))||'Hermes job',120);
 if(value.script||value.monitor_script||value.monitor_url||value.no_agent)return {ok:false,name,reason:'It runs a script or watches something, not a request to the Agent.'};
 const prompt=text(value.prompt);
 if(!prompt)return {ok:false,name,reason:'It has no request for the Agent.'};
 let when='';
 if(schedule.kind==='cron'){
  const fields=text(schedule.expr).split(/\s+/).filter(Boolean);
  if(fields.length!==5)return {ok:false,name,reason:'Its schedule uses cron features Fox does not support.'};
  when=fields.join(' ');
 }else if(schedule.kind==='interval'){
  const minutes=Math.round(Number(schedule.minutes));
  if(!Number.isFinite(minutes)||minutes<1)return {ok:false,name,reason:'Its schedule could not be read.'};
  when=minutes%1440===0?'every '+minutes/1440+'d':minutes%60===0?'every '+minutes/60+'h':'every '+minutes+'m';
 }else if(schedule.kind==='once'){
  const at=iso(schedule.run_at);
  if(!at)return {ok:false,name,reason:'Its time could not be read.'};
  if(Date.parse(at)<=now)return {ok:false,name,reason:'It already ran.'};
  when=at;
 }else return {ok:false,name,reason:'Its schedule could not be read.'};
 return {ok:true,routine:{key:'hermes:'+(text(value.id)||name),name,prompt:clip(prompt,8000),schedule:when,enabled:value.enabled!==false&&value.state!=='paused'}};
}
/** Routine keys say which Agent they came from, so bringing it again replaces only its copies. */
export const migrationRoutineKey=(key:string)=>MIGRATION_SOURCES.some(source=>String(key).startsWith(source+':'));

// What Fox remembers -------------------------------------------------------------------------

/** Session names in Fox's past conversations, so recall can tell sources apart. */
export const migrationSession=(source:MigrationSource,title:string)=>clip(MIGRATION_SOURCE_TITLES[source]+' · '+title,160);
export const migrationNotesSession=(source:MigrationSource,owner?:string|null)=>clip(MIGRATION_SOURCE_TITLES[source]+' notes'+(text(owner)?' · '+text(owner):''),160);

/** A short line in Fox's long-term memory saying what came over and where it is. */
export function migrationMemoryNote({source,conversations,routines,skills,notes}:{source:MigrationSource;conversations:string[];routines:string[];skills:string[];notes:number}):string {
 const list=(items:string[],limit:number)=>items.slice(0,limit).join(', ')+(items.length>limit?` and ${items.length-limit} more`:'');
 const title=MIGRATION_SOURCE_TITLES[source];
 const lines=[`Brought over from ${title} on this computer:`];
 if(conversations.length)lines.push(`- Past conversations (search with read_companion_archive): ${list(conversations,12)}.`);
 if(notes)lines.push(`- ${notes} notes, searchable as "${title} notes".`);
 if(skills.length)lines.push(`- Skills: ${list(skills,12)}.`);
 if(routines.length)lines.push(`- Routines: ${list(routines,12)}.`);
 return lines.length>1?clip(lines.join('\n'),2400):'';
}

// Skills ---------------------------------------------------------------------------------------

/** A Hermes skill folder name: lowercase letters, digits and hyphens. */
export const migrationSkillName=openClawSkillName;
const SKILL_FOLDER=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
// One name inside a skill folder: no separators, drive or stream colon or control characters, no
// leading dot (so never `.` or `..`) and nothing Windows would trim.
const skillSegment=(part:string)=>part.length>0&&part.length<=128&&!/[/\\:\u0000-\u001f]/.test(part)&&!part.startsWith('.')&&!/[. ]$/.test(part);
/** The path parts of one brought skill file, or null when it is not a shape bringing an Agent
 * makes: `folder` is a `migrationSkillName` (perhaps with a `-2` suffix) and `relative` is up to
 * three plain names ending in a Markdown file. Skills and their stores come back from backups, so
 * nothing else is ever written into the Harness. */
export function migrationSkillPath(folder:unknown,relative:unknown):string[]|null {
 if(typeof folder!=='string'||typeof relative!=='string'||folder.length>64||!SKILL_FOLDER.test(folder)||!/\.md$/i.test(relative))return null;
 const parts=relative.split('/');
 return parts.length<=3&&parts.every(skillSegment)?[folder,...parts]:null;
}
/** Whether every folder and file of a brought skill store is a `migrationSkillPath`. */
export const migrationSkillsSafe=(skills:unknown):boolean=>!!skills&&typeof skills==='object'&&!Array.isArray(skills)&&
 Object.entries(skills as Record<string,unknown>).every(([folder,files])=>!!files&&typeof files==='object'&&!Array.isArray(files)&&
  Object.entries(files as Record<string,unknown>).every(([relative,text])=>typeof text==='string'&&migrationSkillPath(folder,relative)!==null));
/** Hermes lists a skill by the `name` and `description` in its SKILL.md frontmatter. Claude Code
 * and pi let both default (folder name, first paragraph), so they are filled in when missing. */
export function migrationSkillMarkdown(markdown:string,folder:string,source:MigrationSource):string {
 const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(markdown);
 const front=match?match[1]:'',body=match?markdown.slice(match[0].length):markdown;
 const has=(key:string)=>new RegExp('^'+key+'\\s*:\\s*\\S','m').test(front);
 const added:string[]=[];
 if(!has('name'))added.push('name: '+migrationSkillName(folder));
 if(!has('description')){
  const paragraph=body.split(/\n\s*\n/).map(part=>part.replace(/^#+\s.*$/gm,'').replace(/\s+/g,' ').trim()).find(Boolean)??'';
  added.push('description: '+JSON.stringify(clip(paragraph||`${MIGRATION_SOURCE_TITLES[source]} skill ${folder}.`,300)));
 }
 if(!added.length)return markdown;
 return `---\n${[...added,...front?[front]:[]].join('\n')}\n---\n\n${body.replace(/^\s+/,'')}`;
}

const frontmatter=(markdown:string)=>{
 const match=/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(String(markdown||''));
 const field=(key:string)=>{const line=match?new RegExp('^'+key+'\\s*:\\s*(.+)$','m').exec(match[1]):null;return line?line[1].trim().replace(/^(["'])(.*)\1$/,'$2'):'';};
 return {field,body:(match?markdown.slice(match[0].length):String(markdown||'')).trim()};
};
/** A Claude Code sub-agent (`agents/<name>.md`: a role with its own instructions) as a skill Fox
 * loads when the person asks for that kind of work. */
export function claudeCodeAgentSkill(file:string,markdown:string):{name:string;markdown:string}|null {
 const {field,body}=frontmatter(markdown),label=field('name')||file.replace(/\.md$/i,'');
 if(!body)return null;
 const name=migrationSkillName('claude-agent-'+label),what=field('description');
 return {name,markdown:openClawSkillMarkdown({name,source:'claude-code',description:`The person's Claude Code sub-agent ${label}${what?': '+what:''}. Use it when they ask for that kind of work.`,
  body:`# ${label}\n\nIn Claude Code the person had a sub-agent called ${label}${what?' ('+clip(what.replace(/\s+/g,' '),300)+')':''}. Take on its role when they ask for that kind of work, following its instructions:\n\n${clip(body,40000)}`})};
}
/** A saved prompt the person runs by name (a Claude Code `/command`, a pi prompt template) as a skill. */
export function promptTemplateSkill(source:MigrationSource,file:string,markdown:string):{name:string;markdown:string}|null {
 const {field,body}=frontmatter(markdown),command=file.replace(/\.md$/i,'').replace(/[\\/]/g,':');
 if(!body)return null;
 const name=migrationSkillName(command+'-command'),what=field('description'),title=MIGRATION_SOURCE_TITLES[source];
 return {name,markdown:openClawSkillMarkdown({name,source,description:`The person's /${command} command from ${title}${what?': '+what:''}. Use it when they ask for /${command} or that task.`,
  body:`# /${command}\n\nIn ${title} the person ran this as /${command}. When they ask for it, or for that task, follow these instructions; $ARGUMENTS, $1, $2 … stand for what they add after the command.\n\n${clip(body,40000)}`})};
}
/** Another Hermes Agent profile (its own persona, memory and conversations) as one skill. */
export const hermesProfileSkill=(profile:AgentRole)=>agentRoleSkill(profile,{from:'Hermes Agent',source:'hermes',prefix:'hermes-profile-',kind:'profile'});
